<form id="browse_filter" style="display:none" method="post" action="<?php echo url('browsefilter') ?>">
	<input type="hidden" name="orderby" value="<?php echo isset($orderby) ? $orderby : 'pid DESC'?>"/>
	<input type="hidden" name="pageRows" value="<?php echo isset($pageRows) ? $pageRows : '60'?>"/>
	<input type="hidden" name="listMode" value="<?php echo isset($listMode) ? $listMode : 'photo'?>"/>
	 <?php if(isset($filter) && count($filter['tids']) > 0 && $tagsList[$filter['tids'][0]]->path_alias == 'tag-plus-size'):?>
	<input type="hidden" name="tid_path_alias" value="tag-plus-size"/>
	<?php else:?>
	<input type="hidden" name="tid_path_alias" value=""/>
	<?php endif;?>
	<!--
	<input type="hidden" name="fileds" value="<?php echo isset($pageRows) ? $pageRows : '60'?>"/>
	<input type="hidden" name="listMode" value="<?php echo isset($listMode) ? $listMode : 'photo'?>"/>
	-->
</form>