<div class="body-left">

<div id="wrapper-left">

<div id="cat-lists" class="widget">

<div class="w-head ordinary">
	<h2 class="side-subcat-title">User Home</h2>
</div>
<div class="side-subcat-div side-subcat-div1">
    <ul><li class="side-subcat"><span class="top-cat">My Orders</span></li>
		<li><a href="<?php echo url('order/list/first');?>">Order History</a></li>
	</ul>
    <ul><li class="side-subcat"><span class="top-cat">Account settings</span></li>
        <li><a href="<?php echo url('user/panel');?>">Member Home</a></li>
        <li><a href="<?php echo url('user/info');?>">Personal Information</a></li>
        <li><a href="<?php echo url('user/pwd');?>">Change Password</a></li>
    </ul>
    
    <ul><li class="side-subcat"><span class="top-cat">Functions</span></li>
            <li><a href="<?php echo url('user/logout');?>">Log Out</a></li>
    </ul>
</div>

</div>
</div>
<?php ?>
</div>