<div class="widget">
<div class="w-head">
<h3><a href="#" id="active">User information</a>&nbsp;&nbsp;&nbsp;&nbsp;<span><a href="<?php echo url('user/pwd');?>">User Password Information</a></span></h3>
</div>
            <div class="uc-wrapper w-content">
<?php if(count(getMessages(false)) > 0):?>
<div class="result_box"><?php echo themeMessages(); ?></div>
<?php endif;?>
            <form action="" method="post">
        		<div class="user_edit">
                  <table cellspacing="1" cellpadding="3" class="form">
                    <tbody>
                      <tr>
                        <th>Username:</th>
                        <td><input type="text" readonly="readonly" value="<?php echo isset($user->name) ? $user->name : null ?>" class="elmbBlur input readonly"></td>
                      </tr>
                      <tr>
                        <th>Nickname:</th>
                        <td><input type="text" name="nickname" value="<?php echo isset($user->nickname) ? $user->nickname : null ?>" title="Nickname"/></td>
                      </tr>
                      <tr>
                        <th>Birthday:<span class="explanation required">*</span><span style="padding-left:5px; font-style:italic; color:#777;font-weight:normal;">Format : YYYY-MM-DD</span></th>
                        <td><input type="text" name="birthday" value="<?php if (isset($user) && $user->birthday != '') echo plain(substr($user->birthday, 0, 4) . '-' . intval(substr($user->birthday, 4, 2)) . '-' . intval(substr($user->birthday, 6, 2))) ?>"  class="elmbBlur input" title="Birthday"/></td>
                      </tr>
                     <tr>
                        <th>E-mail:<span class="explanation required">*</span></th>
                        <td><input type="text" name="email" value="<?php echo isset($user->email) ? $user->email : null ?>"  class="non-empty elmbBlur input" title="Email can't for empty"/></td>
                      </tr>
                      <tr>
                        <th>Telephone:</th>
                        <td><input type="text" name="phone" value="<?php echo isset($user->phone) ? $user->phone : null ?>" class="elmbBlur input"/></td>
                      </tr>
                      <tr>
                        <th>Mobile:</th>
                        <td><input type="text" name="mobile" value="<?php echo isset($user->mobile) ? $user->mobile : null ?>" class="elmbBlur input"/></td>
                      </tr>
                      <tr>
                        <th>Region:</th>
                        <td><input type="text" name="area" value="<?php echo isset($user->area) ? $user->area : null ?>" class="elmbBlur input"/></td>                      </tr>
                      <tr>
                        <th>Postcode:</th>
                        <td><input type="text" name="postcode" value="<?php echo isset($user->postcode) ? $user->postcode : null ?>" class="elmbBlur input"/></td>
                      </tr>
                     <tr>
                     	<th>&nbsp;</th>
                        <td>
                  <button class="button" type="submit">Save Changes</button>
	              <button class="button" type="reset">Reset Form</button>
                        </td>
				     </tr>
                    </tbody>
                  </table>
               </div>
                </form>
            </div>
</div>