

<!-- 页脚部分开始 -->
<div class="footer">

<!-- 用户帮助内容模块，展示一些帮助内容的列表，这个内容很重要，你可以重新组织，但这个功能需要-->
<div id="customerHelp" class="w-bp">
  <div>
  <?php if(isset($helpList) && isset($articleTypeList)):
  $articleTypeCount = 0;
  foreach($helpList as $index => $articleList):
  	if($index != 'news'):
  	$articleTypeCount++;
  	if($articleTypeCount > 4):
  		break;
  	endif;
  	?>
  <dl><dt><?php echo $articleTypeList[$index]->name;?></dt><?php 
          	foreach ($articleList as $v):
          ?><dd><a href="<?php echo url($v->url)?>"><?php echo $v->title;?></a></dd><?php 
          	endforeach;
          ?></dl>
  <?php endif;
  endforeach;
  endif?>
  </div>
</div>
<!-- 用户帮助内容模块结束 -->

<!-- 邮件订阅功能模块，这个功能可以要，也可以不要，看你的设计-->
<div class="widget w-customeGuide" id="customerGuide">
	<div class="col" id="newsLetter">
		<fieldset><h3>Subscribe to our <em>Newsletter</em></h3><p>Get updates, discounts, and special offers from today!</p>
			<input type="text" class="text" value="Enter Your Email" id="mailAddress"><button id="submitMailAddress" class="textbtnGray">Subscribe</button>
		</fieldset></div>
</div>
<!-- 结束邮件订阅功能模块 -->


<!-- 版权信息开始  -->
<div id="copyright">
<span class="floatleft">
           	<?php $siteInfo = Bl_Config::get('siteInfo');echo $siteInfo['copyright'];?>
        </span>

<span style="float:right;">
			Any Questions Please Email to: <a href="mailto:<?php echo $siteInfo['email'];?>"><?php echo $siteInfo['email'];?></a>
</span>

</div>
<!-- 版权信息结束 -->


</div>
<!-- 页脚部分结束 -->


