<div id="overlay" style="width: 100%; height:100%; position:fixed; left:0; top: 0; background:#000; opacity:.6;z-index:1000001;display:none"></div>
<div id="wholesale-box" style="width:450px;height:490px;z-index:1000002;display:none;background:#fff;text-align:center">
		<div>
	    	<h1 style="background-color: #F6E3FD;color:#DB7595;padding:10px;">Retailer &amp; Wholesaler</h1>
                <div id="alert_info">
                    <p>If you are a wholesaler or want to become our retailer, please fill out this form and we'll reply the wholesale pricelist as soon as possible.</p>
                </div>
	        <div>
	        	<div id="message" style="display:none">
	        		<p style="font-size: 14px;font-weight: bold;margin-bottom: 10px;">Thanks for your interest in lingerieinterest.com!</p>
	        		<p>If you are a wholesaler customer or want to become our retailer, please visit our wholesale price website:<a style="color:#f00;font-size: 14px;font-weight: bold;margin: 0px 5px;text-decoration: underline;" href="http://www.iwantlingerie.com/">http://www.iwantlingerie.com/</a>.For any other questions, please contact support@lingerieinterest.com. Thank you!</p>
	        	</div>
	            <form method="post">
					<div>
		            	<div>
		                    <span>Name:</span><br />
		                    <input type="text" value="" name="name"  class="elmbBlur"/>*
		                </div>
		                <div>
		                	<span>Email:</span> <br />
		                    <input value="" name="email" class="elmbBlur"/>*
		                </div>
		                <div>
		                	<span>Country:</span> <br />
		                    <input value="" name="country" class="elmbBlur"/>*
		                </div>
		                <div>
		                	<span>Phone Number:</span> <br />
		                    <input value="" name="phone" class="elmbBlur"/>*
		                </div>
		                <div>
		                	<span>Website:</span> <br />
		                    <input value="" name="website" class="elmbBlur"/>
		                </div>
                        <div>
		                	<span>Comments:</span> <br />
		                    <textarea name="comment" style="border:1px solid #D9D9D9;width:200px;height:100px;color:#666;"></textarea>
		                </div>
	                </div>
	            </form>
	            <div>
			        <div>
			        	<input id="confirm-btn" type="button" class="button confirm" value="Confirm"/>
			            <input id="cancel-btn" type="button" class="button cancel" value="Close"/>
			        </div>
		        </div>
	        </div>
	    </div>
</div>