<form name="cart_quantity_frm" method="post" class="widget pr-fields disable_on_submit" action="<?php echo url('cart/productpost');?>" id="prOrder">
    <input type="hidden" value="<?php echo isset($product->pid) ? $product->pid : null ?>" name="pid">
	<div id="errorInfo" class="errorInfo">Please complete your selection(s) before adding to cart.<em></em></div>
	<div class="clearfix prOrderOptions">
<div class="fl">
	<?php foreach ($product->fields as $fieldName => $field):
    if(!empty($product->{'field_' . $fieldName})):
    ?>
			<?php if ($field->multiple):
			  		if($field->required==1){
			    		$sel_cont = ' class=" required" title="Choose at least one '.$field->name.'"';
            		}else{
              			$sel_cont = '';
            		}?>
            		<div class="custom-select">
            		<dl>
            		<dt><label><span>Please Select </span><?php echo $field->name;?><span class="required">&nbsp;*</span></label></dt>
            		<dd class="<?php echo $fieldName;?>">
	                  <?php foreach ($product->{'field_' . $fieldName} as $k => $v):
	                    if($v):
	                      if(isset($field->default_value) && $field->default_value && $field->default_value == $v ):?>
	                          <button class="button" value="<?php echo $v;?>"><?php echo $v;?></button>
	                  <?php else:?>
	                      <button class="button"  value="<?php echo $v;?>"><?php echo $v;?></button>
	                  <?php endif;
	                  endif;
	                  endforeach;?>
            		</dd>
            		</dl>
	             <?php if($field->required == 1):?>
		             <p class="error_notice error" style="display:none;">Choose At Least 1 <?php echo $fieldName;?>. </p>
		             <p class="success_notice" style="display:none;"></p>
		         <?php endif;?>	
                  </div>

	             <?php if(isset($field->default_value) && $field->default_value && in_array($field->default_value,$product->{'field_' . $fieldName}) ):?>
	             	<input type="hidden" value="<?php echo $field->default_value?>" name="data[<?php echo $field->name;?>]" id="attr_<?php echo $fieldName;?>"/>
	             <?php else:?>
	             	<input id="attr_<?php echo $fieldName;?>" type="hidden" value="" name="data[<?php echo $field->name?>]">
	             <?php endif;?>
	            <?php else:?>
	            	<label><?php echo isset($product->{'field_' . $fieldName}) ? plain($product->{'field_' . $fieldName}) : null;?></label>
              		<input type="hidden" id="attr_'.$field->field_name.'" value="<?php echo plain($product->{'field_' . $fieldName});?>" name="data[<?php echo $field->name;?>]"/>
            <?php endif;?>
    <?php endif;
    endforeach; ?>
</div>
	<div class="custom-input last">
	
	<table id="tb" class="table-prOrderOpts"><tbody>
		<tr>
		<th>Quantity: </th>
		<td><div class="fl">
			<input type="text" size="3"  class="numcheck" value="<?php echo isset($product->sell_min) && $product->sell_min ? $product->sell_min : 1 ?>" name="qty" title="<?php echo isset($product->sell_min) ? $product->sell_min : 0 ?>,<?php echo isset($product->sell_max) ? $product->sell_max : 0 ?>" value="1" />  Unit(s)</div>
		</td>
		</tr>
	</tbody>
	</table>	
	</div>

	<div><a class="cart-add" href="javascript:void(0);"><input type="submit" value="Add to shopping cart" alt=""  class="add2Cart button" name="cart"></a></div>
  </div>
</form>
