<div class="footer">
<div id="customerHelp" class="w-bp">
  <div>
  <?php if(isset($helpList) && isset($articleTypeList)):
  $articleTypeCount = 0;
  foreach($helpList as $index => $articleList):
  	if($index != 'news'):
  	$articleTypeCount++;
  	if($articleTypeCount > 4):
  		break;
  	endif;
  	?>
  <dl><dt><?php echo $articleTypeList[$index]->name;?></dt><?php 
          	foreach ($articleList as $v):
          ?><dd><a href="<?php echo url($v->url)?>"><?php echo $v->title;?></a></dd><?php 
          	endforeach;
          ?></dl>
  <?php endif;
  endforeach;
  endif?>
<dl>
<dt>Popular Products</dt>
<dd><a href="http://www.spicyclubwear.com/">sexy club wear</a></dd>
<dd><a href="http://www.spicyclubwear.com/">sexy club dresses</a></dd>
<dd><a href="http://www.spicyclubwear.com/">wholesale clubwear</a></dd>
</dl>


  </div>
</div>
<div class="clear"></div>
<div id="copyright">
<span class="floatleft">
           	<?php $siteInfo = Bl_Config::get('siteInfo');echo $siteInfo['copyright'];?>
        </span>
<span style="float:right;">
			Any Questions Please Email to: <a href="mailto:<?php echo $siteInfo['email'];?>"><?php echo $siteInfo['email'];?></a>
</span>
</div>


</div>