<?php if ($recommandProductList) :?>
<div id="p-best" class="p-widget">
  <h2><span>POPULAR IN THIS CATEGORY </span><b></b></h2>
<div class="productlist">
<?php
  shuffle($bestProductList);
  $best_count = 0;
  foreach ($bestProductList as $v):
  if($best_count >= 3)
    break;
  $best_count++;
?>
<dl><dt><a title="<?php echo $v->name;?>" href="<?php echo url($v->url) ?>">
		<img alt="" src="<?php echo urlimg('118x178',$v->filepath)?>"></a></dt>
	<dd><a title="<?php echo $v->name;?>" href="<?php echo url($v->url) ?>"><?php
		  if (strlen($v->name) > 40){
		    echo substr(str_replace(',', ', ', $v->name) , 0, 40). ' ...';
		  }
		  else{
		    echo str_replace(',', ', ', $v->name);
		  }
		?></a>
		<span class="price"><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?> <?php echo isset($v->price)? c($v->price) : null;?></span>
	</dd>
</dl>
<?php endforeach;?>
</div>
</div>
<?php endif;?>