<div class="navigation">
<ul class="topnav">
<li><a href="<?php echo url("");?>">Home</a></li>
<?php if(isset($category) && $category):
    $_first_category_class = true;
    foreach ($category as $c):
?><li class="<?php echo $_first_category_class ? 'first' : ''; $_first_category_class = false;?> dropdown">
	<a class="navItem " href="<?php echo url($c->path_alias . '.html');?>"><?php echo isset($c->name)? $c->name : null;?></a>
<?php
  //if have sub categories
  if(isset($c->sub) && $c->sub):?>
  
<ul class="sub-nav-container">
<?php   foreach($c->sub as $s):?>
		<li><a href="<?php echo url($s->path_alias . '.html');?>"><?php echo isset($s->name) ? $s->name : null; ?></a></li>
<?php 	endforeach;?>
</ul>
<?php endif;?>
</li>
<?php endforeach;
	endif;?>
</ul>
</div>