<?php global $user; $this->user = $user;?>
<div id="global_action">
	<div id="utility" class="innercontainer">
<div class="container">
<div id="header">
   <div>
	<div id="welcome_section">		
		<div class="currency">
			<ul id="cur_selector" class="dropdown">
			<li><a title="" href="#" id="yourCurrency"><?php
                      if (!isset($_SESSION['currency'])) {
                        $_SESSION['currency'] = 'USD';
                      }
                      echo $_SESSION['currency']
                    ?></a>
			<ul>
             	<li><a title="USD" class="flag USD" rel="nofollow" href="#" target="_top">USD</a></li>
             	<li><a title="GBP" class="flag GBP" rel="nofollow" href="#" target="_top">GBP</a></li>
            </ul>
            </li>
		   </ul>
		</div>
	<div id="user_panel" class="top_a">
	<ul>
	</ul>
	</div>	
	</div>
      <div class="logo"><a href="<?php echo url('')?>"><img src="<?php echo themeResourceURI('images/logo.png');?>"  width="280" height="101"/></a></div>
    <div class="Sign-Join">
	<div id="shoppingCart"><span>Cart&nbsp;<em class="cart_item_number"><?php echo isset($goodsInCart)? $goodsInCart : 0; ?></em> &nbsp;Item</span>
		<a class="button top-checkout" href="<?php echo url('cart');?>" style="">Check Out</a>
	</div>
	<div id="up_signup">
<?php if ($user->uid): ?>
			<a href="<?php echo url('order/list/');?>">My Orders</a> or 
			<a href="<?php echo url('user/logout') ?>">Logout</a>
<?php else: ?>
			<a href="<?php echo url('user/login');?>">Sign In</a> or 
			<a href="<?php echo url('user/register');?>">Join Free</a>
<?php endif;?>
</div>
<br class="clears" />

	<div class="search1">&nbsp;</div>
    <form action="<?php echo url('pitems');?>" method="post" id="search">
      <input name="keyword" id="search_keyword" type="text" class="text" value="<?php echo isset($search_keywords) ? plain($search_keywords) : 'sexy lingerie';?>" onfocus="if(this.value=='What would you like to save on today'){this.value='';}"  onblur="if(this.value==''){this.value='sexy lingerie';}" />
      <a id="header_search_keyword" href="javascript:void(0)">
        <button type="submit"></button>
      </a>
      </form>

	</div>


<br class="clears" />
<?php $this->render('parts/navigation.phtml');?>



</div>
</div>
</div>
</div>
</div>
