<div class="body-left">

<div id="wrapper-left">

<div id="cat-lists" class="widget">
<div class="side-subcat-div">
<?php if(isset($helpList)):foreach($helpList as $k=>$article_list):?>

    <ul><li><?php echo ucwords($k);?></li>
<?php foreach ($article_list as $v):?>
		<li><a href="<?php echo url($v->url)?>" class="<?php if($articleInfo->title == $v->title) echo 'red'?>"><?php echo ucwords($v->title);?></a></li>
<?php endforeach;?>
	</ul>
<?php endforeach;endif;?>
</div>

</div>
</div>
<?php ?>
</div>