<div class="w-head">
<h1>Order History</h1>
</div>

<div class="w-content">
 <h4 style="margin-top:20px;">You can find orders by selecting a date period below.</h4>
            <div class="user_edit">
                <form action="<?php echo url('order/list');?>" method="post" id="form_order">
                <table border="0" class="OrderHistory">
                <tbody>
                <tr>
                	<th>Order No.</th>
                	<th>Order Status</th>
                	<th></th>
                </tr>
                <tr>
                	<td><input type="text" value="<?php echo isset($number) ? $number : null?>" name="number"/></td>
	                <td>
		                <div class="custom-select">
			                <select name="status">
			                	<option value="any">Any</option>
			                	<option value="0">Pending</option>
				                <option value="1">Processing</option>
				                <option value="2">Shipped</option>
				                <option value="-1">Cancelled</option>
			                </select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		                </div>
	                </td>
	                <td></td>
                </tr>
                <tr>
	                <th>Start Date</th>
	                <th>End Date</th>
	                <th></th>
                </tr>
				<tr>
	                <td align="left"><input type="text" class="datepicker" name="startTime" value="<?php echo isset($startTime) ? $startTime : null?>"/></td>
	                <td><input type="text" value="<?php echo isset($endTime) ? $endTime : null?>" name="endTime" class="datepicker" /></td>
	                <td><button class="button order-search" type="submit"><span><span>Search</span></span></button></td>
				</tr>
                </tbody>
                </table>
                </form>
                <table class="u-order-tbl" cellpadding="0" cellspacing="0">
					<thead>
						<tr>
	                      <th>Order ID</th>
	                      <th>Last Update</th>
	                      <th align="center">Order Status</th>
	                      <th align="center">Payment Status</th>
	                      <th align="right">Total</th>
	                      <th align="right">Details</th>
	                    </tr>
                	</thead>
                <tbody>
<?php foreach ($ordersList as $k => $v) : ?>
                <tr>
                <td>
                <a href="<?php echo url('order/info/'.$v->oid);?>"><?php echo isset($v->number)? $v->number : null;?>   </a></td>
                <td><?php echo isset($v->created) && $v->created ? date('Y-m-d H:i:s', $v->created) : null ;?></td>
                <td align="center">
<?php if($v->status==0): echo 'Pending';
	  elseif($v->status==1): echo 'Processing';
	  elseif($v->status==2): echo 'Shipped';
	  elseif($v->status==-1): echo 'Cancelled';
	  elseif($v->status==-2): echo 'Deleted';
	  endif;?></td>
                <td align="center">
<?php if($v->status_payment==0): echo 'Not Paid';
	  elseif($v->status_payment==1): echo 'Paid';
	  endif;?></td>
                <td align="right"><?php echo isset($v->pay_amount) ? c($v->pay_amount) : null; ?></td>
                <td align="right"><a href="<?php echo url('order/info/' . $v->oid)?>">View</a></td>
                </tr>
 <?php endforeach; ?>
                </tbody>
                </table>
                
<?php $this->render('modules/pagination.phtml');?>
				</div>
</div>
