<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body><div style="width:100%;height:100%;background:#000000">
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>
<div class="main-content">
<h1 id="breadcrumb"><a href="<?php echo url("");?>">Home</a>&nbsp;&gt;&nbsp; Payment Successful</h1>
<?php $this->render('modules/ads_topslot.phtml')?>
<div class="general">
<div class="widget wide">
    <div class="w-head">
        <h2><span>Payment Completed</span></h2>
    </div>
</div>
<div class="shoppingContainers">
<div style="background-color:#CCFFCC"><?php echo themeMessages(); ?></div>
<div class="widget inner">
    <div class="w-head">
        <h2><span>Payment Successful!</span></h2>
    </div>
    <div class="w-content">
          <h2> <?php foreach (getMessages() as $message): echo $message['message']; endforeach;?></h2>
        <table cellspacing="0" cellpadding="0" class="u-order-tbl" style="text-align:left;">
        <tbody>
        <?php if (isset($orderInfo)): ?>
            <tr>
                <th>Order No:</th>
                <td><?php echo isset($orderInfo->number)? $orderInfo->number : null;?></td>
                <th>Create at:</th>
                <td><?php echo isset($orderInfo->created)? date('F d, Y H:i:s',$orderInfo->created) : null;?></td>
            </tr>
            <tr>
                <th>Shipping Method:</th>
                <td><?php echo isset($orderInfo->shipping->name)? $orderInfo->shipping->name : null;?></td>
                <th>Payment Method:</th>
                <td><?php echo isset($orderInfo->payment->name) ? $orderInfo->payment->name : null;?></td>
            </tr>

            <tr>
                <th>Payable total:</th>
                <td><div><?php echo isset($orderInfo->pay_amount) ? c($orderInfo->pay_amount) : null?></div></td>
                <th>Payment Online</th>
                 <td><?php if(!isset($orderInfo->payment->online) || $orderInfo->payment->online) : echo isset($submitform) ? $submitform : null; endif;?></td>
            </tr>
         <?php endif;?>
        </tbody>
        </table>
        
                	<form action="<?php echo $user->uid ? url('order/info/'.$orderInfo->oid) : url('user/login');?>">
                		<input type="submit" class="button light" value="View Your Order Information"/>
                	</form>
        
        </div>
    </div>
</div>

</div>

</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
</div>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>