<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body><div style="width:100%;height:100%;background:#000000">
<?php global $user ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>


<div class="main-content">
<h1 id="breadcrumb"><a href="<?php echo url("");?>">Home</a>&nbsp;&gt;&nbsp; Password Recovery</h1>
<?php $this->render('modules/ads_topslot.phtml')?>

<div class="widget">
<div class="w-head">
	<h2 class="top">
		Create New Password <a class="big block fr" href="<?php echo url('')?>">&lt;&lt; Return Home</a>
	</h2>
	</div>
<form method="post" action="<?php echo url('user/editPassword/')?>">

	<div class="body">
		<p>Welcome back <?php echo $username?>! Please set new password below for future login.</p>
		
		<?php echo themeMessages()?>
		
			<input type="hidden" name="token" value="<?php echo $token?>"/>
			<input type="hidden" name="username" value="<?php echo $username?>"/>
			
		<p><span class="label">Password：</span><span class="red">*</span>
			<span style="position: relative;">
				<input type="password"  name="newpwd"  class="elmbBlur"/>
			</span>
		</p>
		<p><span class="label">Confirm Password: </span><span class="red">*</span>
			<span style="position: relative;">
				<input type="password"  name="newpwd2"  class="elmbBlur"/>
			</span>
			<button type="submit" class="textbtn">Submit</button>
		</p>
	</div>
	<p class="bottom"><a class="big block fr" href="<?php echo url('user/login')?>">&lt;&lt; Return Home</a></p>

</form>
</div>



</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
</div>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>