<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body><div style="width:100%;height:100%;background:#000000">
<?php global $user ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>
<div class="main-content">
<?php $this->render('parts/breadcrumb.phtml')?>
<?php $this->render('modules/ads_topslot.phtml')?>

<?php $this->render('contents/p_intro.phtml')?>
<?php $this->render('parts/body_left.phtml'); ?>
</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
</div>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/products.js'; ?>" type="text/javascript"></script>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>