<?php echo $this->render('before_body.phtml'); ?>
<body>
<?php echo $this->render('header.phtml'); ?>

<?php global $user ?>

<div id="wrapper">
<section class="widget-dfp widget"><img src="<?php echo $tpldir ?>/images/pay-method.png"></section>


<div id="wrapper-l">
<div id="cart" class="widget w-shCart">

<?php echo themeMessages(); ?>

<div class="w-p w-shCartHeader">
    <a title="Continue Shopping" class="textbtn contShopping left" href="<?php echo url('browse/all.html');?>">Shop More</a>
    <a href="<?php echo url('cart');?>" class="textbtn contShopping left">Update Cart</a>
    <a href="javascript:submit_shopping_cart('delete')" class="textbtnGray contShopping left clearcartBtn">Clear Cart</a>
        <?php if($user->uid):?>
        	<a title="Proceed to Checkout" class="litb-btn ir checkoutBtn right" href="javascript:submit_shopping_cart('checkout')">Proceed to Checkout</a>
        <?php else:?>
        	<a title="Proceed to Checkout" class="litb-btn ir checkoutBtn right" href="<?php echo url('user/login/')?>">Proceed to Checkout</a>
        <?php endif?>
    </div>
<form class="w-shCartCont" id="itemsForm" method="post" action="<?php echo url('cart/cartpost');?>">
	<input id="cart_submit" type="hidden" name="checkout">
	
    <div class="w-rHeadingV2">
        <h2><span>Shopping Cart</span></h2>
    </div>
    <div class="mainbox">
        <table width="100%" class="#">
            <thead>
                <tr>
                    <th class="prDesc">ITEM</th>
                    <th>ITEM PRICE</th>
                    <th class="prQuant">QUANTITY</th>
                    <th class="prAmount">PRICE</th>
                </tr>
            </thead>
            <tfoot>
                <tr class="scTotalSaving">
                    <td class="label">YOUR TOTAL SAVINGS:</td>
                    <td colspan="3"><strong><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?> -<span class="numVal"><?php echo isset($cartInfo->total_save_amount) ? c($cartInfo->total_save_amount) : null?></span></strong></td>
                </tr>
                                <tr class="scSumAmount">
					<td colspan="4">
						<table width="100%">
							<tbody>
							<tr>
								<td class="savingTips">We automatically apply all eligible promotions to offer you the lowest possible price.</td>
								<td class="label nowrap">
									<strong>CART TOTAL</strong>
									<span>
									<?php
									if ($cartInfo->product){
									  echo '(' . count($cartInfo->product) . ' item)';
									} 
									?>
									</span>
										<strong class="totalPrice"><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?> <span class="numVal"><?php echo isset($cartInfo->goods_amount) ? c($cartInfo->goods_amount) : null?></span></strong>
									</td>
							</tr>
						</tbody></table>
					</td>
				</tr>
            </tfoot>
            <tbody>
            
            
<?php
if ($cartInfo->product) :
foreach ($cartInfo->product as $k => $v) : ?>
                <tr id="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>" class="">
                
    <td class="productList grid-m-l">
        <dl>
            <dt>
                <a href="<?php echo url($v->url);?>" title="<?php echo isset($v->name) ? $v->name : null ?>"><img height="85" alt="<?php echo isset($v->name) ? $v->name : null ?>" title="<?php echo isset($v->name) ? $v->name : null ?>" src="<?php echo urlimg('118x178', $v->filepath) ?>"></a>
            </dt>
            
            <dd>
            	<input type="hidden" class="checkitem" name="cart_item_id_checked[]" checked value="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>">
                <h4><a href="<?php echo url($v->url);?>" title="<?php echo isset($v->name) ? $v->name : null ?>"><?php echo isset($v->name) ? $v->name : null ?></a></h4>
				
                <?php if(isset($v->data) && $v->data):
                          foreach($v->data as $dk => $dv):
                            echo '<p class="prAttr">'.$dk.'&nbsp;-&nbsp;'.$dv.'</p>';
                          endforeach;
                          else:
                            echo '&nbsp;';
                          endif;
                ?>

                <div class="countDown">
                        <div class="countDown-wrapper">
                        	<div class="countDown-sign"></div>
                        	<div class="countDown-value"><?php echo (isset($v->price) && isset($v->list_price)) ? round(($v->list_price - $v->price)*100/$v->list_price) : '--';?></div>
                        </div>
                </div>
                <p></p>
            </dd>
        </dl>
    </td>
    <td class="prPrice">
                <p class="listPrice"><del><?php echo isset($v->list_price) ? c($v->list_price) : null;?></del></p>
                <p class="price"><?php echo isset($v->price) ? c($v->price) : null;?></p>
        		<p class="savingPrice"><span>SAVE&nbsp;</span><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?> <span class="numVal"><?php echo (isset($v->price) && isset($v->list_price)) ? ' -'. c($v->list_price - $v->price) : '--';?></span></p>
    </td>
    <td class="prQuant">
        <p>
			    <input type="hidden" value="<?php echo isset($v->pid) ? $v->pid : null ?>" name="pids[]"/>
                <input type="hidden" value="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>" name="cart_item_ids[]"/>
                <input value="<?php echo isset($v->qty) ? $v->qty : null ?>" name="qtys[]" size="3" alt="<?php echo isset($v->qty) ? $v->qty : null ?>" id="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>" class="ajax_qty elmbBlur" title="<?php echo $v->sell_min ? $v->sell_min : 0 ?>,<?php echo $v->sell_max ? $v->sell_max : 0 ?>" rel="<?php echo isset($v->price) ? $v->price : null ?>"/>
        </p>
    </td>
    <td class="prAmount">
        <span class="payPrice"><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?> <span class="numVal"><?php echo isset($v->qty) ? c($v->price * $v->qty) : null;?></span></span><br><a href="<?php echo url('cart/deleteproductfromcart/'.$v->cart_item_id);?>" title="Remove" class="remove ir">Remove</a>
    </td>
</tr>



<?php endforeach;
endif;?>

			</tbody>
        </table>
    </div>
</form>
<div class="w-p w-shCartFooter">
    <div class="widget">
        <a title="Continue Shopping" class="textbtn contShopping left" href="<?php echo url('product/list');?>">Shop More</a>
    	<a href="<?php echo url('cart');?>" class="textbtn contShopping left">Update Cart</a>
        <?php if (isset($cartInfo->product) && count($cartInfo->product) > 0): ?>
        <a href="javascript:submit_shopping_cart('delete')" class="textbtnGray contShopping left clearcartBtn">Clear Cart</a>
        <?php endif;?>
         
        <?php if($user->uid):?>
        	<a title="Proceed to Checkout" class="litb-btn ir checkoutBtn right" href="javascript:submit_shopping_cart('checkout')">Proceed to Checkout</a>
        <?php else:?>
        	<a title="Proceed to Checkout" class="litb-btn ir checkoutBtn right" href="<?php echo url('user/login/')?>">Proceed to Checkout</a>
        <?php endif?>
    </div>
</div>
</div>
</div>
<div id="wrapper-r">
<!-- widget-sc-sidetips-a -->
<div class="w-p sidebox"><h3>Shop With Confidence</h3><p>Shopping on IWantLingerie.com is safe and secure - guaranteed!</p></div>
<!-- widget-sc-sidetips-a_eof --><!-- widget-sc-sidetips-b -->
<div class="w-p sidebox"><h3>Satisfaction Guaranteed</h3><p>IWantLingerie.com cares about your complete satisfaction. We offer a comprehensive return policy on all items, allowing you to shop with confidence.</p></div>
<!-- widget-sc-sidetips-b_eof --><!-- widget-sc-sidetips-c -->
<div class="w-p sidebox">
    <h3>Privacy Policy</h3>
    <p>IWantLingerie.com respects your privacy. We do NOT share or in any way distribute any personal, business or contact information you may provide.</p>
</div>
<!-- widget-sc-sidetips-c_eof --></div>
</div>
<?php echo $this->render('footer.phtml'); ?>
</body>
<?php echo $this->render('after_body.phtml'); ?>
</html>
