<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>


<div class="main-content">
<h1 id="breadcrumb"><a href="<?php echo url("");?>">Home</a>&nbsp;&gt;&nbsp; Password Recovery</h1>
<?php $this->render('modules/ads_topslot.phtml')?>


<div class="widget">
<div class="w-head">
	<h2>Create New Password</h2>
</div>
<div class="user_edit">
		<p>Welcome back <?php echo $username?>! Please set new password below for future login.</p>
		<?php echo themeMessages()?>
<form method="post" action="<?php echo url('user/editPassword/')?>">
			<input type="hidden" name="token" value="<?php echo $token?>"/>
			<input type="hidden" name="username" value="<?php echo $username?>"/>
		<table>
			<tbody>
			<tr><th>Password：*</th>
			<td><input type="password"  name="newpwd"  class="elmbBlur"/></td>
			</tr>
			<tr><th>Confirm Password: *</th>
			<td><input type="password"  name="newpwd"  class="elmbBlur"/></td>
			</tr>
			<tr><th></th>
			<td><button type="submit" class="button">Submit</button></td></tr>
			</tbody>
		</table>
</form>
</div>
</div>

</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>