<?php echo $this->render('before_body.phtml'); ?>
<body>
<?php echo $this->render('header.phtml'); ?>

<?php $seoKeyList = array('corsets'=>20, 'corset'=>6, 'cheap corsets'=>6, 'corsets and bustiers'=>6, 'sexy corset'=>2, 'corset lingerie'=>2, 'bustier corset' =>2, 'sexy corsets'=>1, 'garter lingerie'=>1, 'lingerie corsets'=>1, 'cheap corsets and bustiers'=>1);
$seoKeys = array_keys($seoKeyList);
?>

<div class="bodyer">

<h1 id="breadcrumb"><?php echo themeBreadcrumb() ?></h1>

  <div class="body_right">
        <?php echo $this->render('body_left.phtml'); ?>
        <div class="head_d"></div>

        <!--  <div class="Title_head_there margin">Shop by Price</div>-->
        <?php echo $this->render('priceindex.phtml'); ?>
        <div class="Shop_d"></div>

    </div>



  <div class="body_left">
        <div class="general">
<?php 
	if(isset($termInfo) && $termInfo):
?>
            <div class="Product_narration">
                <div class="top"><?php echo $termInfo->name;?></div>
                <div>
					<?php echo isset($termInfo->description) ? $termInfo->description : null;?>
                </div>
            </div>
<?php 
	endif;
?>


<div class="widget w-resultNavBar"> 
    <!--  
    <p>We found <strong>481</strong> results. </p>
    -->
    <p> <strong><?php echo $productCount ?></strong> product items <?php if (isset($termInfo) && ($termInfo != '')) {echo 'under '. $termInfo->name .'.';}?>  </p>
    <div class="widget w-pagination">
    <ul>

	<!-- first show previous page if page > 1 -->
	<?php echo $pagination;?>
    <!-- end of previous page show -->

</ul>
</div>
</div>

            
            	<form id="browse_filter" style="display:none" method="POST" action="<?php echo url('browsefilter') ?>">
            		<input type="hidden" name="orderby" value="<?php echo isset($orderby) ? $orderby : 'pid DESC'?>"/>
            		<input type="hidden" name="pageRows" value="<?php echo isset($pageRows) ? $pageRows : '16'?>"/>
            		<input type="hidden" name="listMode" value="<?php echo isset($listMode) ? $listMode : 'photo'?>"/>
            	</form>



<div class="widget w-resultSortBarNew" id="resultSortBarNew">
            <div class="sort-by">
            	<span class="sort-label">Sort: </span> 
            	<?php if(!isset($orderby) || $orderby == 'pid DESC' || $orderby == ''){
            	  echo '<span>Default</span>';
            	}else{
            	  echo '<a rel="nofollow" onclick="" href="javascript:filter_option(\'orderby\', \'pid DESC\')">Default</a>';
            	}
            	echo ' | ';
            	?>
            	
            	<?php if(isset($orderby) && $orderby == 'updated DESC'){
            	  echo '<span>New Arrival</span>';
            	}else{
            	  echo '<a rel="nofollow" onclick="" href="javascript:filter_option(\'orderby\', \'updated DESC\')">New Arrival</a>';
            	}
            	echo ' | ';
            	?>

            	<?php if(isset($orderby) && $orderby == 'sell_price ASC'){
            	  echo '<span>Low Price</span>';
            	}else{
            	  echo '<a rel="nofollow" onclick="" href="javascript:filter_option(\'orderby\', \'sell_price ASC\')">Low Price</a>';
            	}
            	echo ' | ';
            	?>

            	<?php if(isset($orderby) && $orderby == 'sell_price DESC'){
            	  echo '<span>High Price</span>';
            	}else{
            	  echo '<a rel="nofollow" onclick="" href="javascript:filter_option(\'orderby\', \'sell_price DESC\')">High Price</a>';
            	}
            	?>
            </div>
    <div class="right">
        <dl class="viewType">
        	            <dd class="gallery">
    
	    <span>gallery</span></dd>
			<dd class="list"><a rel="nofollow" href="">List</a></dd>
            
        </dl>
        <dl class="showType">
            <dt>Show:</dt>
            <dd>
                    <select class="pageRows" name="pageRows">
                      <option value="16" <?php if (!isset($pageRows) || $pageRows == '16') echo 'selected'?>>16</option>
                      <option value="24" <?php if (isset($pageRows)&& $pageRows == '24') echo 'selected'?>>24</option>
                      <option value="48" <?php if (isset($pageRows)&& $pageRows == '48') echo 'selected'?>>48</option>
                      <option value="96" <?php if (isset($pageRows) && $pageRows == '96') echo 'selected'?>>96</option>
                      <option value="192" <?php if (isset($pageRows) && $pageRows == '192') echo 'selected'?>>192</option>
                    </select>    
            </dd>            
        </dl>
    </div>
</div>
            
            
                <div class="w-productList w-grid w-relatedProdsGrid w-p10">
                <?php
                  if(isset($productList) && $productList):
                    $seoKeyCount = 0;
                    $showItemCount = 0;
                    $nextSEOKey = '';
                    foreach ($productList as $k => $v):
                    if($showItemCount > 0 && $showItemCount % 4 == 0){
                      echo '<br class="clear"/>';
                    }
                    $showItemCount++;

                    if($seoKeyCount == 0){
                      $nextSEOKey = next($seoKeys);
                      $seoKeyCount = $seoKeyList[$nextSEOKey];
                    }
                    $seoKeyCount--;
                ?>
                	<dl>
                		<dt>
                			<a href="<?php echo url($v->url);?>" title="<?php echo $v->name . ' in ' . $nextSEOKey;?>">
                			<img width="160" height="240" alt="<?php $nameSplit =  split(',', $v->name);
                			echo $nameSplit[0]. ', '. $nextSEOKey. ', ';
                			if(key_exists(1, $nameSplit)){
                			  echo $nameSplit[1];
                			}
                			?>" title="<?php echo $v->name /*. ', ' . $termInfo->name*/;?>" src="<?php echo urlimg('160x240',$v->filepath)?>">
                			<em class="iconDiscount">
                			<?php
                			  echo round((1 - $v->price / $v->list_price) * 100, 0);
                			?>
							</em>
                			</a>
                		</dt>
                		<dd class="prodName">
                		<a href="<?php echo url($v->url);?>" title="<?php echo $v->name;?>"><?php /*echo '<b>'.$termInfo->name . ' </b>';*/?><?php echo $v->name;?></a>
                		</dd>
                        <dd class="oldPrice"><?php echo isset($v->list_price)? c($v->list_price) : null;?></dd>
                		<dd class="price"><a rel="nofollow" href="<?php echo url($v->url);?>" title="<?php echo $v->name;?>"><?php echo isset($v->price)? c($v->price) : null;?></a></dd>
                		<dd class="review">
                		<!--  stars  -->
                		<?php if(isset($v->pid) && $v->pid):?>
                            <?php echo widgetCallFunction('fivestars', 'getaveragestars', $v->pid)?>
                            <!--  <span class="review_count" style="display:none">122 reviews</span><br/> -->
                        <?php endif;?>
                        <!-- end of stars <span class="star starS5"><em>5 stars of 5</em></span>-->
                          <form method="POST" action="<?php echo url('cart/productpost');?>"><p>
                          <input type="hidden" value="<?php echo isset($v->pid) ? $v->pid : null ?>" name="pid">
                          <input type="hidden" value="1" name="qty">
                          <?php if($v->status):
                          
  $default_fields = array();
  $canOrderDirectly = true;
  foreach ($v->fields as $fieldName => $field){
    if(!empty($v->{'field_' . $fieldName})){
      if ($field->multiple){
        if(count($v->{'field_' . $fieldName})==1){
          //we can use default field value to make the direct order.
          $default_fields[$fieldName] = $v->{'field_' . $fieldName}[0];
        }else{
          //need go to details page and make the value.
          $canOrderDirectly = false;
          break;
        }
      }
    }
  }
  if($canOrderDirectly){
    foreach($default_fields as $field_name=>$field_value){
      echo '<input name="'.$field_name.'" type="hidden" value="'.$field_value.'">';
      echo '<input name="data['.$field_name.']" type="hidden" value="'.$field_value.'">';
    }
    echo '<input type="submit" class="buynow" value="" name="cart">';
  }else{
    echo '<a class="textbtn contShopping left" href="'.url($v->url).'">View Details</a>';
  }
?>

                          <?php endif;?>
                          
                          </p>
                          </form>
                		</dd>
                	</dl>
                <?php endforeach;
                   endif;
                ?>
                </div>
            
            
<div class="widget w-resultSortBarNew" id="resultSortBarNew">
            <div class="sort-by sort-bottom">
            	<span class="sort-label">Sort: </span> 
            	<?php if(!isset($orderby) || $orderby == 'pid DESC' || $orderby == ''){
            	  echo '<span>Default</span>';
            	}else{
            	  echo '<a rel="nofollow" onclick="" href="javascript:filter_option(\'orderby\', \'pid DESC\')">Default</a>';
            	}
            	echo ' | ';
            	?>
            	
            	<?php if(isset($orderby) && $orderby == 'updated DESC'){
            	  echo '<span>New Arrival</span>';
            	}else{
            	  echo '<a rel="nofollow" onclick="" href="javascript:filter_option(\'orderby\', \'updated DESC\')">New Arrival</a>';
            	}
            	echo ' | ';
            	?>

            	<?php if(isset($orderby) && $orderby == 'sell_price ASC'){
            	  echo '<span>Low Price</span>';
            	}else{
            	  echo '<a rel="nofollow" onclick="" href="javascript:filter_option(\'orderby\', \'sell_price ASC\')">Low Price</a>';
            	}
            	echo ' | ';
            	?>

            	<?php if(isset($orderby) && $orderby == 'sell_price DESC'){
            	  echo '<span>High Price</span>';
            	}else{
            	  echo '<a rel="nofollow" onclick="" href="javascript:filter_option(\'orderby\', \'sell_price DESC\')">High Price</a>';
            	}
            	?>
            </div>


    <div class="right">

    <div class="widget w-pagination">
    <ul>

	<!-- first show previous page if page > 1 -->
	<?php echo $pagination;?>
    <!-- end of previous page show -->

</ul>
</div>

    </div>
</div>
            



<?php if(isset($docvar3)):?>
<div id="advanced_intro-w">
  <?php echo $docvar3;?>
</div>
<?php endif;?>





<!--recommendProductList-->
        </div>
        <div class="general_bottom"></div>

    </div>


</div>

<?php echo $this->render('footer.phtml'); ?>
</body>
<?php echo $this->render('after_body.phtml'); ?>
</html>