<div class="body-left body-left1">
<div class="wrapper-left">
<div id="cat-lists" class="widget">
<div class="w-head ordinary">
	<h2 class="side-subcat-title">Articles </h2>
</div>

<div class="side-subcat-div">

<?php if(isset($helpList)):foreach($helpList as $k=>$article_list):?>
	<div class="article-cat"><?php echo ucwords($k);?></div>
    <ul>
<?php foreach ($article_list as $v):?>
		<li><a href="<?php echo url($v->url)?>" class="<?php if($articleInfo->title == $v->title) echo 'red'?>"><?php echo ucwords($v->title);?></a></li>
<?php endforeach;?>
	</ul>
<?php endforeach;endif;?>
</div>


</div>
</div>
<?php ?>
</div>
