<div class="body-left">
<div id="personal-center">

<div id="cat-lists" class="widget">

<div class="w-head ordinary">
  <h2 class="side-subcat-title"><img src="<?php echo themeResourceURI('images/a_left_bg2.png');?>" /></h2>
</div>
<div class="side-subcat-div side-subcat-div1">
    <ul>
        <li class="a_le">My Orders</li>
		<li><a href="<?php echo url('order/list/first');?>">Order History</a></li>
	</ul>
    <ul><li class="a_le">Account settings</li>
        <li><a href="<?php echo url('user/panel');?>">Member Home</a></li>
        <li><a href="<?php echo url('user/info');?>">Personal Information</a></li>
        <li><a href="<?php echo url('user/pwd');?>">Change Password</a></li>
        <li><a href="<?php echo url('user/logout');?>">Exit</a></li>
    </ul>	
</div>

</div>
</div>
</div>