<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php $this->render('parts/header.phtml');?>

<div class="main-content">

<div class="general">

<div class="error-content">
	<h2>404 Page Not Found</h2>
	
	<div class="info-list">
	    <p>Woops, The Url: <?php echo url($ex->getUri());?> is no longer existed.</p>
	    <p>Return <a href="<?php echo $siteInfo['siteurl'];?>">Home</a></p>
	<?php
	if ($debug):
	  $router = $ex->getRouter();
	?>
	    <p><?php echo $ex->getMessage(); ?></p>
	    <p><label>Uri</label> : /<?php echo plain($ex->getUri()) ?></p>
	    <p><label>Router - folder</label> : <?php echo plain($router['folder']) ?></p>
	    <p><label>Router - controller</label> : <?php echo plain($router['controller']) ?></p>
	    <p><label>Router - action</label> : <?php echo plain($router['action']) ?></p>
	    <p><label>Router - arguments</label> : <?php echo plain(implode(' | ', $router['arguments'])) ?></p>
	<?php endif;?>
	</div>
</div>

</div>
</div>

<?php echo $this->render('parts/footer.phtml'); ?>

</body>
</html>