<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php $this->render('parts/header.phtml');?>

<div class="main-content">
<div class="general">
<div class="error-content">
	<h2>General Error</h2>
	<div class="info-list">
		<p>Woops, Seems some unexpected things happen...</p>
		<p>Return <a href="<?php echo $siteInfo['siteurl'];?>">Home</a></p>
		<?php if ($debug): ?>
    		<p><?php echo $ex->getMessage(); ?></p>
		<?php endif ?>
	</div>
</div>
</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
</body>
<?php echo $this->render('parts/after_body.phtml'); ?>
</html>