<div class="widget w-resultSortBar">
	<div class="f_left num_show">We found <span class="b" id="products-num"><?php echo $productCount;?></span> items for your choices.</div>
	<?php $this->render('contents/c_sortoptions.phtml');?>
	<?php $this->render('contents/c_viewoptions.phtml')?>
</div>
<br class="clears" />

<div class="tab plus-choice" style="margin-top:10px;">
        <ul class="tab_head clearfix">
        <?php if(isset($filter) && count($filter['tids']) > 0 && $tagsList[$filter['tids'][0]]->path_alias == 'tag-plus-size'):?>
          <li id="all-products">
            <h3><a rel="nofollow" onclick="" href="javascript:filter_option('tid_path_alias', '')">All Products</a></h3>
          </li>
          <li id="plus-size"  class="active">
            <h3>Plus Size</h3>
          </li>
        <?php else:?>
          <li id="all-products"  class="active">
            <h3>All Products</h3>
          </li>
          <li id="plus-size">
            <h3><a rel="nofollow" onclick="" href="javascript:filter_option('tid_path_alias', 'tag-plus-size')">Plus Size</a></h3>
          </li>
        <?php endif;?> 
        </ul>
</div>



<?php $this->render('modules/pagination.phtml');?>

<?php $this->render('contents/c_productlist.phtml');?>
<br class="clears"/>

<?php $this->render('modules/pagination.phtml');?>

<br class="clears"/>
