<div class="widget w-resultSortBar">
	<div class="f_left num_show">We found <span class="b" id="products-num"><?php echo $productCount;?></span> items for your choices.</div>
	<?php $this->render('contents/c_sortoptions.phtml');?>
	<?php $this->render('contents/search_viewoptions.phtml')?>
</div>
<br class="clears" />
<?php $this->render('modules/pagination.phtml');?>

<?php $this->render('contents/c_productlist.phtml');?>
<br class="clears"/>

<?php $this->render('modules/pagination.phtml');?>

<br class="clears"/>
