<?php if(isset($termInfo) && $termInfo):?>
	<div class="cat-intro">
		<h1><?php echo $termInfo->name;?></h1>
		<?php if(isset($termInfo->filepath) && $termInfo->filepath != ''):?>
		<div class="cat-intro-wrapper" style="border:none;">
		<img alt="<?php echo $termInfo->name;?>" src="<?php echo urlimg(null, $termInfo->filepath);?>"/>
		</div>
		<?php endif;?>
		<div class="cat-intro-wrapper">
		<p class="cat-summary"><?php echo isset($termInfo->description) ? $termInfo->description : null;?></p>
		<div class="extend">
		<?php echo $docvar6;?>
		</div>
		</div>
		
    </div>
<?php endif;?>