<?php global $user ?>
<fieldset class="widget inner" id="shipAddr">
    <div class="w-head">
		<h2><span>Shipping Address</span></h2>
    </div>
    <div class="main-section">
	<ul>
		<li style="display:none;"><a class="textbtn" href="#" id="addAddress">Add a New Shipping Address</a></li>
        <li class="removeBorder editAddr" id="addressForm">
        	<input type="hidden" name="edit_address_id" id="addressId"/>
			<a style="display:none;" href="#" class="cancel" id="cancelAddr">Cancel</a>
			<p class="explanation"><span class="required">*</span>&nbsp;<span class="indicates">Indicates required fields.</span></p>
			<table class="tb-shippingAddr" cellspacing="0" cellpadding="0">
			<tbody>
				<tr>
                    <th valign="bottom"><label>First Name<span class="required">*</span></label></th>
					<th valign="bottom"><label>Last Name<span class="required">*</span>:</label></th>
				</tr>
				<tr>
					<td><input type="text" class="text elmbBlur" id="delivery_first_name" name="delivery_first_name" value="<?php echo isset($address->delivery_first_name) ? $address->delivery_first_name : ''; ?>"/>
					<p class="errorInfo"></p></td>
					<td><input type="text" class="text elmbBlur" title="recipient last name can't for empty" id="delivery_last_name" name="delivery_last_name" value="<?php echo isset($address->delivery_last_name) ? $address->delivery_last_name : ''; ?>"/>
						<p class="errorInfo"></p></td>
				</tr>
				<tr>
					<th valign="bottom" colspan="2"><label>Email Address:</label></th>
					</tr>
					<tr>
					<td colspan="2"><input type="text" class="text elmbBlur readonly" title="E-mail can't for empty" id="delivery_email" name="delivery_email" readonly="readonly" value="<?php echo isset($user->email) ? $user->email : ''; ?>"/>
						<p class="explanation">(Same as your account email.)</p>
						<p class="errorInfo"></p>
					</td>
					</tr>
					<tr>
					<th valign="bottom"><label>Delivery Address<span class="required">*</span>:</label></th>
					<th valign="bottom"><label>City<span class="required">*</span>:</label></th>
					</tr>
					<tr>
					<td>
						<input type="text" class="text elmbBlur" title="Delivery Address can't for empty" id="delivery_address" name="delivery_address" value="<?php echo isset($address->delivery_address) ? $address->delivery_address : ''; ?>"/>						<p class="errorInfo"></p>
					<td>
						<input type="text" class="text elmbBlur" title="Receiving city can't for empty" id="delivery_city" name="delivery_city" value="<?php echo isset($address->delivery_city) ? $address->delivery_city : ''; ?>"/>									<p class="errorInfo"></p>
					</td>
					</td>
				</tr>

				<tr>
					<th valign="bottom"><label>Destination Country<span class="required">*</span>:</label></th>
					<th valign="bottom"><label>State/Province/Region<span class="required">*</span>:</label></th>
				</tr>
				<tr>
					<td>
                        <div class="custom-select"><select name="select" class="select usebox elmbBlur" id="select_countries" title="Country can not for empty">
<?php foreach($countries as $k => $v) : ?>
                             <option value="<?php echo $k ?>" <?php if(isset($address->delivery_cid) && $address->delivery_cid == $k) echo 'selected'; ?>><?php echo $v ?></option>
<?php endforeach;?>
                        </select>
                        </div>
					</td>
					<td>
						<div id="zoneId" <?php if(isset($address->delivery_province) && $address->delivery_pid == 0) echo 'style="display:none;"'; ?>>
                        <select name="select" class="select usebox elmbBlur" id="select_provinces">
                        <?php foreach($provinces as $k => $v) : ?>
                            <option value="<?php echo $k ?>" <?php if(isset($address->delivery_pid) && $address->delivery_pid == $k) echo 'selected'; ?>><?php echo $v ?></option>
                        <?php endforeach;?>
                        </select>
                        </div>
        			<div id="state" <?php if(isset($address->delivery_province) && $address->delivery_pid == 0) echo 'style="display:table-row;"'; else echo 'style="display:none;"' ?>>
        				<input type="text" class="text elmbBlur" id="delivery_or_province" name="delivery_or_province" value="<?php echo isset($address->delivery_province) ? $address->delivery_province : ''; ?>"/>
					</div>
					</td>
				</tr>
				<tr>
					<th valign="bottom"><label>ZIP/Postal Code<span class="required">*</span>:</label></th>


					<th valign="bottom"><label>Phone Number<span class="required">*</span>:</label></th>
					</tr>
					<tr>
					<td>
						<input type="text" class="text elmbBlur" title="Postal Code can't for empty" id="delivery_postcode" name="delivery_postcode" value="<?php echo isset($address->delivery_postcode) ? $address->delivery_postcode : ''; ?>"/>									<p class="errorInfo"></p>
					</td>
					<td>
						<input type="text" class="text elmbBlur" title="Telephone and mobile phone can not also be empty" id="delivery_mobile" name="delivery_mobile" value="<?php echo isset($address->delivery_mobile) ? $address->delivery_mobile : ''; ?>" />
						<p class="errorInfo"></p>
						<p class="clearfix"></p>
					</td>
				</tr>
			</tbody>
			</table>
			<input type="reset" style="display:none;" id="resetAddr"/>
	    </li>
    </ul>
    </div>
</fieldset>