<?php if (isset($bestProductList)&& $bestProductList) :?>
<div id="p-best" class="p-widget">
<h2>POPULAR</h2>
<div class="grid">
<dl><dd><img height="1" width="100%" src="<?php echo $this->themeResourceURI('images/gry_dot.gif');?>"></dd></dl>
<?php
  shuffle($bestProductList);
  $best_count = 0;
  foreach ($bestProductList as $v):
  if($best_count >= 3)
    break;
  $best_count++;
?>
<dl>
	<dt><a title="<?php echo $v->name;?>" href="<?php echo url($v->url) ?>"><img alt="<?php echo $v->name;?>" src="<?php echo urlimg('118x178',$v->filepath)?>"></a></dt>
	<dd><a title="<?php echo $v->name;?>" href="<?php echo url($v->url) ?>"><?php echo $v->name;?></a></dd>
	<dd><a><?php echo $v->price;?></a></dd>
</dl>
<dl><dd><img height="1" width="100%" src="<?php echo $this->themeResourceURI('images/gry_dot.gif');?>"></dd></dl>
<?php endforeach;?>

</div>
</div>
<?php endif;?>