<div class="w-prodImages" id="product-image-intro">
<div id="w-prodthumbnails">

	<div id="thumbnailsUp" class="thumbnailsBtn"><a href="javascript:void(0)">Thumb Up</a></div>
	<ul id="thumblist" class="clearfix" style="margin-top:25px;">
	<?php if($product->fid):?>
	<li><a href="javascript:void(0);"  class="zoomThumbActive" 
	rel="{gallery: 'gal1', smallimage: '<?php echo urlimg('410x615_water_mark',$product->filepath)?>',largeimage: '<?php echo urlimg('water_mark', $product->filepath);?>" rev="<?php echo urlimg('water_mark', $file->filepath);?>"><img width="65" height="85" src="<?php echo urlimg('118x178', $product->filepath) ?>" border="0" /></a></li><?php 
	endif;?>
	<?php
        $thumbnail_count = 0;
        foreach ($product->files as $i => $file):
          $thumbnail_count++;
        ?>
        <li><a href="javascript:void(0)"
	<?php if($product->filepath == $file->filepath){echo 'class="zoomThumbActive"';};?> 
        rel="{gallery: 'gal1', smallimage: '<?php echo urlimg('410x615_water_mark', $file->filepath) ?>',largeimage: '<?php echo urlimg('water_mark', $file->filepath);?>'}" 
        style="margin-top: 0px;<?php if($thumbnail_count > 5) echo 'display:none;'?>">
        <img src="<?php echo urlimg('60x90', $file->filepath) ?>" alt="<?php echo isset($file->alt)? plain($file->alt):null; ?>" border="0" />
        </a></li>
    <?php endforeach ?>
    	
	</ul>
	<div id="thumbnailsDown" class="thumbnailsBtn"><a href="javascript:void(0)" <?php if(count($product->files) > 4) echo 'class="hasItem"';?>>Thumb Down</a></div>
</div>

	<div id="w-featurePics">
    	<a href="<?php echo urlimg('water_mark', $product->filepath);?>" rel="gal1" class="jqzoom">
    		<img id="main-display-pic" src="<?php echo urlimg('410x615_water_mark', $product->filepath);?>"/>
   		</a>
	</div>
</div>