<?php if (isset($product->related)&& $product->related ) :
			$related_count = 0;?>

<div id="p-related" class="p-widget">
<h2>RELATED</h2>
<div class="grid">
<?php foreach ($product->related as $v):
      if(!isset($v))
      	continue;
      if($related_count >= 3)
        break;
      $related_count++;?>
<dl><dt><a title="<?php echo $v->name;?>" href="<?php echo url($v->url) ?>"><img alt="<?php echo $v->name;?>" src="<?php echo urlimg('60x90',$v->filepath)?>"></a></dt>
</dl>
<?php endforeach;?>
</div>
</div>
<?php endif;?>