<div class="search_viewoptions filter">
    <div class="showType">
    <ul>
    <?php if (isset($pageRows) && ($pageRows == 'all'|| $pageRows == '1000')):?>
    	<li><p>Show : <a class="select" href="javascript:void(0)">60</a> Items / all Items</p></li>
    	<?php else:?>
    	<li><p>Show : 60 Items / <a class="select" href="javascript:void(0)">all</a> Items</p></li>
    	<?php endif;?>
    </ul>
    </div>
</div>