<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php $this->render('parts/header.phtml');?>

<div class="main-content">
<div class="general cat">
<div class="main-block1">
<?php $this->render('contents/c_intro.phtml');?>
<?php if($termInfo->name != 'Corset Tops'):?>
<div class="widget" id="productlist">
<?php else:?>
<div class="widget small" id="productlist">
<?php endif; ?>
<div class="w-head cat-filters"> 
<?php $this->render('contents/c_filter_form.phtml');?>
<div class="widget w-resultSortBar">
	<p class="product-count"><?php echo $productCount;?> Items</p>
	<?php $this->render('modules/pagination.phtml');?>
	<?php $this->render('contents/c_viewoptions.phtml')?>
</div>
</div>

<?php $this->render('contents/c_productlist.phtml');?>

<br class="clear"/>
<div class="widget w-resultSortBar">
	<?php $this->render('contents/c_sortoptions.phtml');?>
	<?php $this->render('modules/pagination.phtml');?>
	<?php $this->render('contents/c_viewoptions.phtml')?>
</div>
</div>

<!-- extral intro for this category -->
<?php if(isset($docvar3)):?>
<div class="advanced_intro"><?php echo $docvar3;?></div>
<!-- end of extral intro -->
<?php endif;?>
<?php echo $this->render('contents/c_comments.phtml');?>
</div>

<?php $this->render('parts/body_left.phtml'); ?>
</div>
</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
</body>
<?php echo $this->render('parts/after_body.phtml'); ?>
</html>