

<!-- 最上面的目录列表部分，你可以将它和logo部分换顺序，里面的结构最好不换。但是对于鼠标移到主目录，子目录需要出现的效果应该在设计时考虑-->
<div class="navigation">
<ul class="topnav">
<li><a href="<?php echo url("");?>">Home</a></li>
<?php if(isset($category) && $category):
    $_first_category_class = true;
    foreach ($category as $c):
?><li class="<?php echo $_first_category_class ? 'first' : ''; $_first_category_class = false;?> dropdown">
	<a class="navItem " href="<?php echo url($c->path_alias . '.html');?>"><?php echo isset($c->name)? $c->name : null;?></a>
<?php
  //if have sub categories
  if(isset($c->sub) && $c->sub):?>
  
  <!-- 目录的子目录列表 -->
<ul class="sub-nav-container">
<?php   foreach($c->sub as $s):?>
		<li><a href="<?php echo url($s->path_alias . '.html');?>"><?php echo isset($s->name) ? $s->name : null; ?></a></li>
<?php 	endforeach;?>
</ul>
<!-- 结束目录的子目录列表 -->
<?php endif;?>
</li>
<?php endforeach;
	endif;?>
</ul>
</div>
<!-- 结束最上面的目录列表部分 -->

