<div class="w-head cat-filters"> 
<div class="pySort">
	<?php $this->render('contents/search_viewoptions.phtml')?>
	<?php $this->render('contents/search_filter_form.phtml');?>
<div class="widget w-resultSortBar" id="resultSortBar">
	<?php $this->render('contents/c_sortoptions.phtml')?>
	<?php $this->render('modules/pagination.phtml');?>
	</div>
</div>
</div>
<br class="clear"/>
<?php $this->render('contents/c_productlist.phtml');?>
<br class="clear"/>
<div class="w-head cat-filters"> 
<div class="pySort">
	<?php $this->render('contents/search_viewoptions.phtml')?>
	<div class="widget w-resultSortBar">
	<?php $this->render('contents/c_sortoptions.phtml');?>
	<?php $this->render('modules/pagination.phtml');?>
	</div>
</div>
</div>