<div class="footerWrap">
<div class="wrapper">

<div class="footer">

<div class="footContent">

<div class="footLinks">

<div class="customerHelp">
  <div>
  <?php if(isset($helpList) && isset($articleTypeList)):
  $articleTypeCount = 0;
  foreach($helpList as $index => $articleList):
  	if(strcasecmp($index, 'news')):
  	$articleTypeCount++;
  	if($articleTypeCount > 4):
  		break;
  	endif;?>
  <ul><li class="footHeader"><?php echo $articleTypeList[$index]->name;?></li>
  			<?php foreach ($articleList as $v):?>
  			<li><a href="<?php echo url($v->url)?>"><?php echo $v->title;?></a></li>
          	<?php endforeach;?>
   </ul>
  <?php endif;endforeach;endif?>
  </div>
</div>


</div>

<div class="mailer">
   <div class="mailerHead">
     <img src="<?php echo $this->themeResourceURI('images/mailer.jpg');?>" alt="Sign up for special promotions and updates">
   </div>
  <input type="text" class="text" value=" ENTER EMAIL ADDRESS" id="mailAddress"><button id="submitMailAddress" class="textbtnGray">JOIN</button>
</div>


</div>
<div style="clear:both;"></div>

<div class="copyright">
	<span class="legal">
           	<?php $siteInfo = Bl_Config::get('siteInfo');echo $siteInfo['copyright'];?>
    </span>
    <span class="support-email">
    		Support Email: <a href="mailto:<?php echo $siteInfo['email'];?>"><?php echo $siteInfo['email'];?></a>
    </span>
</div>
<div style="clear:both;"></div>
</div>

</div>
</div>
<script>
// Include the UserVoice JavaScript SDK (only needed once on a page)
UserVoice=window.UserVoice||[];(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/PtKVJ5jukabVi1r1QmwfQ.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})();

//
// UserVoice Javascript SDK developer documentation:
// https://www.uservoice.com/o/javascript-sdk
//

// Set colors
UserVoice.push(['set', {
  accent_color: '#448dd6',
  trigger_color: 'white',
  trigger_background_color: 'rgba(46, 49, 51, 0.6)'
}]);

// Identify the user and pass traits
// To enable, replace sample data with actual user traits and uncomment the line
UserVoice.push(['identify', {
  //email:      'john.doe@example.com', // User’s email address
  //name:       'John Doe', // User’s real name
  //created_at: 1364406966, // Unix timestamp for the date the user signed up
  //id:         123, // Optional: Unique id of the user (if set, this should not change)
  //type:       'Owner', // Optional: segment your users by type
  //account: {
  //  id:           123, // Optional: associate multiple users with a single account
  //  name:         'Acme, Co.', // Account name
  //  created_at:   1364406966, // Unix timestamp for the date the account was created
  //  monthly_rate: 9.99, // Decimal; monthly rate of the account
  //  ltv:          1495.00, // Decimal; lifetime value of the account
  //  plan:         'Enhanced' // Plan name for the account
  //}
}]);

// Add default trigger to the bottom-right corner of the window:
UserVoice.push(['addTrigger', { mode: 'contact', trigger_position: 'bottom-right' }]);

// Or, use your own custom trigger:
//UserVoice.push(['addTrigger', '#id', { mode: 'contact' }]);

// Autoprompt for Satisfaction and SmartVote (only displayed under certain conditions)
UserVoice.push(['autoprompt', {}]);
</script>
