<div class="navigation">
<ul class="topnav">
<li class="dropdown"><a href="<?php echo url("");?>" class="navItem">Home</a></li>
<?php if(isset($category) && $category):
    $_first_category_class = true;
    foreach ($category as $c):
?><li class="<?php echo $_first_category_class ? 'first' : ''; $_first_category_class = false;?> dropdown">
	<a class="navItem " href="<?php echo url($c->path_alias . '.html');?>"><?php echo isset($c->name)? $c->name : null;?></a>
<?php
  //if have sub categories
  if(isset($c->sub) && $c->sub):?>
<ul class="sub-nav-container">
<?php   foreach($c->sub as $s):?>
		<li><a href="<?php echo url($s->path_alias . '.html');?>"><?php echo isset($s->name) ? $s->name : null; ?></a></li>
<?php 	endforeach;?>
</ul>
<?php endif;?>
</li>
<?php endforeach;
	endif;?>
	
<!-- brandings -->
<?php if(isset($brands) && count($brands) > 0):?>
<li class="dropdown" style="float:right;">
	<span style="padding: 8px 7px 0px 7px;margin: 0;display: block;outline: 0;text-transform: uppercase;font-family: georgia;color: rgb(173, 0, 141);">Brands</span>
<ul class="sub-nav-container" style="right:0;left:inherit;">
<?php  foreach ($brands as $v):?>
		<li><a href="<?php echo url('+'.$v->path_alias . '.html');?>"><?php echo isset($v->name) ? $v->name : null; ?></a></li>
<?php 	endforeach;?>
</ul>
<?php endif;?>
</li>

<!-- end of brandings -->
</ul>
</div>