<?php global $basePath ?>
<script type="text/javascript">var basePath = '<?php echo plain($basePath) ?>';</script>
<script language="javascript" src="<?php echo url('scripts/jquery-1.7.2.min.js') ?>" type="text/javascript"></script>
<script language="javascript" src="<?php echo url('scripts/jquery-ui-1.8.19.custom.min.js') ?>" type="text/javascript" ></script>
<?php if (isset($_SESSION['preview'])): ?>
<script language="javascript" src="<?php echo url('scripts/preview.js') ?>" type="text/javascript"></script>
<?php endif ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/front.js';?>" type="text/javascript"></script>
<script src="<?php echo $tpldir .'/javascripts/jquery.KinSlideshow-1.1.js';?>" type="text/javascript"></script>
<script src="<?php echo $tpldir .'/javascripts/jquery.jqzoom-core.js';?>" type="text/javascript"></script>
<script src="<?php echo $tpldir .'/javascripts/jquery.bpopup.min.js';?>" type="text/javascript"></script>
<script src="<?php echo $tpldir. '/javascripts/after_body.js';?>" type="text/javascript"></script>