<div class="footer">
<div id="customerHelp" class="w-bp">
  <div class="menu">
  <?php if(isset($helpList) && isset($articleTypeList)):
  $articleTypeCount = 0;
  foreach($helpList as $index => $articleList):
  	if($index != 'News'):
  	$articleTypeCount++;
  	if($articleTypeCount > 4):
  		break;
  	endif;
  	?>
  <ul><li><h3><?php echo $articleTypeList[$index]->name;?></h3></li>
  <?php 
          	foreach ($articleList as $v):
          ?><li><a href="<?php echo url($v->url)?>"><?php echo $v->title;?></a></li><?php 
          	endforeach;
          ?></ul>
  <?php endif;
  endforeach;
  endif?>


<div class="widget w-customeGuide" id="customerGuide">
	<div class="col" id="newsLetter">
		<fieldset><h3>Subscribe to our <em>Newsletter</em></h3><p>Get updates, discounts, and special offers from today!</p>
			<input type="text" class="text" value="Enter Your Email" id="mailAddress"><button id="submitMailAddress"><em></em></button>
		</fieldset></div>
</div>
    </div>
</div>
<div class="clears"></div>
<div id="copyright">
<span class="floatleft">
           	<?php $siteInfo = Bl_Config::get('siteInfo');echo $siteInfo['copyright'];?>

</span>
</div>
</div>