<?php global $user;?>
<div id="global_action">
	<div id="utility" class="innercontainer">
      <div class="search">
      <form action="<?php echo url('pitems');?>" method="post">
           <input name="keyword" id="search_keyword" type="text" class="text" value="<?php echo isset($search_keywords) ? plain($search_keywords) : 'sexy lingerie';?>" onfocus="if(this.value=='What would you like to save on today'){this.value='';}"  onblur="if(this.value==''){this.value='sexy lingerie';}" />
           <a id="header_search_keyword" href="javascript:void(0)"><button type="submit"><span><em></em></span></button></a>
      </form>
     </div>

	<div id="welcome_section">
		<div class="currency">
			<ul id="cur_selector" class="dropdown">
<?php	if ($currencyList && count($currencyList) >0) :
            foreach ($currencyList as $k => $v) :
                if ($v->visible) :?>
             	<li><a title="<?php echo $v->name ?>" class="flag <?php echo $v->name?>" rel="nofollow" href="#" target="_top"><?php echo $v->name; ?></a></li>
<?php 			endif;
            endforeach;
         endif; ?>
            </ul>
		</div>
	</div>
    <div class="logo"><a href="<?php echo url('');?>"><img src="<?php echo themeResourceURI('images/logo.png')?>"/></a></div>
<div id="header">
	<div id="user_panel">
	<ul>
		<li id="up_signup">
<?php if ($user->uid): ?>
			<a href="<?php echo url('order/list/');?>" rel="nofollow" class="red">My Orders</a>
			<a href="<?php echo url('user/logout') ?>" rel="nofollow" class="red">Logout</a>
<?php else: ?>
			<a href="<?php echo url('user/login');?>" rel="nofollow" class="red">Sign In</a>
			<a href="<?php echo url('user/register');?>" rel="nofollow" class="red">Join Free</a>
<?php endif;?>
		</li>
	</ul>
	</div>
	
	<div id="shoppingCart"> 
    	<a name="HEADER" id="bag" href="<?php echo url('cart');?>" title="shopping bag">
    		<em></em>Shopping Bag<span class="cart_item_number"><?php echo isset($goodsInCart)? $goodsInCart : 0; ?></span>
    	</a>
 	</div>

</div>
</div>
</div>