<?php if(isset($newProductList) && $newProductList):?>
<div class="widget">
<div class="w-head">
<h2>New Arrivals</h2>
<a class="more tiny" href="<?php echo url('new-arrivals.html');?>">&gt; View All New Arrivals</a>
</div>
<div id="p_new_arrival" class="grid">
<?php
	$item_count = 0;
    	foreach ($newProductList as $v):
        $item_count++;
?>
<dl>
	<dt><a title="<?php echo $v->name;?>" href="<?php echo url($v->url);?>" title="<?php echo $v->name;?>">
		<img alt="<?php echo $v->name;?>" title="<?php echo $v->name;?>" src="<?php echo urlimg('187x276', $v->filepath);?>">
			<em class="iconDiscount"><span><?php echo round((1 - $v->price / $v->list_price) * 100, 0);?></span></em>
      	</a>
    </dt>
    <dd class="prodName"><a href="<?php echo url($v->url);?>" title="<?php echo $v->name;?>"><?php echo str_replace(',', ', ', $v->name);?></a></dd>
    <dd class="oldPrice"><?php echo isset($v->list_price)? c($v->list_price) : null;?></dd>
    <dd class="price"><?php echo isset($v->price)? c($v->price) : null;?></dd>
</dl>
<?php if($item_count % 4 == 0):echo '<br class="clear">'; endif;endforeach;?>
</div>
</div>
<?php endif;?>