<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php $this->render('parts/header.phtml');?>
<div class="main-content">
<div class="widget fancy">
  <table width="100%" cellpadding="0" cellspacing="0">
    <tbody>
    <tr>
      <td width="20%"><span class="step_count step_count_active"><font><font>1.</font><font>Shopping Cart</font></font></span></td>
      <td width="7%"><span class="arrow spirit"></span></td>
      <td width="20%"><span class="step_count"><font><font>2.</font><font>Place Order</font></font></span></td>
      <td width="7%"><span class="arrow spirit"></span></td>
      <td width="20%"><span class="step_count"><font><font>3.</font><font>Payment</font></font></span></td>
      <td width="6%"><span class="arrow spirit"></span></td>
      <td width="20%"><span class="step_count"><font><font>4.</font><font>Payment Completed</font></font></span></td>
    </tr>
  </tbody></table>
</div>
<div class="clears"></div>
<?php if(count(getMessages(false)) > 0):?>
<div class="result_box"><?php echo themeMessages(); ?></div>
<?php endif;?>

<?php $this->render('contents/cart_list.phtml');?>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>