<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user; ?>
<?php $this->render('parts/header.phtml'); ?>

<div class="main-content">
<div class="widget fancy">
  <table width="100%" cellpadding="0" cellspacing="0">
    <tbody><tr>
      <td width="20%"><span class="step_count">1.Shopping Cart</span></td>
      <td width="7%"><span class="arrow spirit"></span></td>
      <td width="20%"><span class="step_count">2.Place Order</span></td>
      <td width="7%"><span class="arrow spirit"></span></td>
      <td width="20%"><span class="step_count">3.Payment</span></td>
      <td width="6%"><span class="arrow spirit"></span></td>
      <td width="20%"><span class="step_count step_count_active">4.Payment Completed</span></td>
    </tr>
  </tbody></table>
</div>
<div class="general">
<?php if(count(getMessages(false)) > 0):?>
<div class="result_box"> <?php echo themeMessages(); ?></div>
<?php endif;?>
<div class="shoppingContainers user_edit">

<div class="widget inner">

        <?php foreach (getMessages() as $message): echo ''; endforeach;?>
        <table cellspacing="0" cellpadding="0" class="order-callback">
        <tbody>
        <?php if (isset($orderInfo)): ?>
            <tr>
                <th>Order No:</th>
                <td><?php echo isset($orderInfo->number)? $orderInfo->number : null;?></td>
                <th>Create at:</th>
                <td><?php echo isset($orderInfo->created)? date('F d, Y H:i:s',$orderInfo->created) : null;?></td>
            </tr>
            <tr>
                <th>Shipping Method:</th>
                <td><?php echo isset($orderInfo->shipping->name)? $orderInfo->shipping->name : null;?></td>
                <th>Payment Method:</th>
                <td><?php echo isset($orderInfo->payment->name) ? $orderInfo->payment->name : null;?></td>
            </tr>

            <tr>
                <th>Payable total:</th>
                <td><div><?php echo isset($orderInfo->pay_amount) ? c($orderInfo->pay_amount) : null?></div></td>
                <th>Payment Online</th>
                 <td><?php if(!isset($orderInfo->payment->online) || $orderInfo->payment->online) : echo isset($submitform) ? $submitform : null; endif;?></td>
            </tr>
         <?php endif;?>
            <tr>
            <th colspan="4">
        <div style="margin:5px auto">
                	<form action="<?php echo $user->uid ? url('order/info/'.$orderInfo->oid) : url('user/login');?>">
                		<input type="hidden" class="button light" value="View Your Order Information"/>
                		<button type="submit" class="button"><span><span>View Your Order Information</span></span></button>
                	</form>
        </div></th>
            </tr>
                 </tbody>
        </table>
    </div>
</div>

</div>

</div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>