<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/header.phtml'); ?>

<div class="main-content">
<div class="widget">

<div class="user_edit user_edit1">
<div class="w-head">
	<h2>Create New Password</h2>
</div>

<?php if(count(getMessages(false)) > 0):?>
<div class="result_box"><?php echo themeMessages(); ?></div>
<?php endif;?>

		<p>Welcome back <?php echo $username?>! Please set new password below for future login.</p>
		<form method="post" action="<?php echo url('user/editPassword/')?>">
			<input type="hidden" name="token" value="<?php echo $token?>"/>
			<input type="hidden" name="username" value="<?php echo $username?>"/>
		<table><tbody>
		<tr>
			<th>Password<span class="required">*</span>: </th>
			<th>Confirm Password<span class="red">*</span>: </th>
			<th></th>
		</tr>
		<tr>
			<td><input type="password"  name="newpwd"  class="elmbBlur"/></td>
			<td><input type="password"  name="newpwd2"  class="elmbBlur"/></td>
			<td><button type="submit" class="button"><span><span>Submit</span></span></button></td>
		</tr>
		</tbody>
		</table>
</form>
</div>
</div>


</div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>