<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user; ?>

<?php $this->render('parts/header.phtml'); ?>
<div class="main-content">
<div class="general">
<?php $this->render('modules/slider.phtml');?>


<div class="little_banner">
<a href="" rel="nofollow" class="little_banner banner"><img src="<?php echo themeResourceURI('images/free-shipping.png'); ?>" width="210" height="118" alt="always free shipping" style="border:none;"/></a>
<a href="" rel="nofollow"><img src="<?php echo themeResourceURI('images/free-samples.png');?>" width="210" height="118" alt="free sample services"/></a>
<a href="" rel="nofollow"><img src="<?php echo themeResourceURI('images/online-discount.png');?>" width="210" height="118" alt="80% discount"/></a>
<a href="" rel="nofollow"><img src="<?php echo themeResourceURI('images/customer-service.png');?>" width="210" height="118" alt="friendly customer service"/></a>
</div>

<br class="clears" />
<div class="index_main clearfix">
      <div class="tab">
        <ul class="tab_head clearfix">
          <li class="active" id="new_arrival">
            <h3>New Arrival</h3>
          </li>
          <li id="recommend">
            <h3>Recommended</h3>
          </li>
          <li id="discounted">
            <h3>Discounted</h3>
          </li>
        </ul>
        <ul class="tab_body">
          <li class="new_arrival">
            <?php $this->render('modules/new-arrival.phtml');?>
          </li>
          <li class="recommend">
            <?php $this->render('modules/recommand.phtml');?>
          </li>
          <li class="discounted">
            <?php $this->render('modules/discounted.phtml');?>
          </li>
        </ul>
</div>
</div>
</div>
</div>

<?php echo $this->render('parts/footer.phtml'); ?>


<?php echo $this->render('parts/after_body.phtml'); ?>
<script src="<?php echo $tpldir. '/javascripts/jquery.flexslider.js';?>" type="text/javascript"></script>
<script type="text/javascript">
// Can also be used with $(document).ready()
$(window).load(function() {
    $('.flexslider').flexslider(
		{controlNav: "paging",slideshowSpeed: 100000, animationDuration: 600}
	);
	$('.flex-caption').each(function(){
		var flexabstract = $('p.abstract', $(this));
		var flexdetail = $('p.detail', $(this));
		if(!(flexabstract.length&&flexdetail.length)){
			$('h3', $(this)).css({'display':'none'});
		}
		});
});

</script>
</body>
</html>