<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/header.phtml'); ?>

<div class="main-content">
<div class="widget fancy">
<div class="w-head">
<h1>Sign In</h1>
</div>

<?php if(count(getMessages(false)) > 0):?>
<div class="result_box"><?php echo themeMessages(); ?></div>
<?php endif;?>

	<div class="user-forms">
            <div class="user-login">
                <h1>Returning Customer</h1>
                <div class="user-forms-border">

                <div id="client_message" style="display:none"></div>
                <form action="<?php echo url('user/login');?>" method="post">
					<div class="login_content">
	                    <div class="name">
	                    	<span>Username/Email:</span> <br />
	                    	<input type="text" value="" name="username"  class="elmbBlur"/>
	                    </div>
	                    <div class="passwd">
	                    	<span>Password:</span> <br />
	                    	<input type="password" value="" name="password"  class="elmbBlur"/>
	                    </div>
	                    <div>
	                    <div class="login-submit">
	                    <input type="submit" class="login-submit" value="Sign In"/> </div>
	                    </div>
                    	<div class="login-forgetpw"><a href="<?php echo url('user/getPassword')?>">Forget Password? </a></div>
                    </div>
                </form>
                </div>
            </div>

			<div class="user-register-pre">
                <h1>New Customers</h1>
                <div class="user-forms-border">
                	<p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
            	</div>
            	<button onclick="window.location='<?php echo url('user/register');?>';" class="button fr" title="Create an Account" type="button"><span><span>Create an Account</span></span></button>
        	</div>
			</div>

         </div>
</div>


<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>