<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php $this->render('parts/header.phtml');?>

<div class="main-content">
<?php $this->render('parts/breadcrumb.phtml')?>
<div class="general">
<div id="prodcut-channels" class="main-block">

<?php $this->render('contents/c_intro.phtml');?>
<?php $this->render('contents/c_filter_form.phtml');?>


<div class="widget" id="productlist">

<div class="widget w-resultSortBar">
	<div class="f_left num_show">We found <span class="b" id="products-num"><?php echo $productCount;?></span> items for your choices.</div>
	<?php $this->render('contents/c_sortoptions.phtml');?>
	<?php $this->render('contents/c_viewoptions.phtml')?>
</div>


<br class="clears" />
<div class="tab plus-choice" style="margin-top:10px;">
        <ul class="tab_head clearfix">
        <?php if(isset($filter) && count($filter['tids']) > 0 && $tagsList[$filter['tids'][0]]->path_alias == 'tag-plus-size'):?>
          <li id="all-products">
            <h3><a rel="nofollow" onclick="" href="javascript:filter_option('tid_path_alias', '')">All Products</a></h3>
          </li>
          <li id="plus-size"  class="active">
            <h3>Plus Size</h3>
          </li>
        <?php else:?>
          <li id="all-products"  class="active">
            <h3>All Products</h3>
          </li>
          <li id="plus-size">
            <h3><a rel="nofollow" onclick="" href="javascript:filter_option('tid_path_alias', 'tag-plus-size')">Plus Size</a></h3>
          </li>
        <?php endif;?> 
        </ul>
</div>

<?php $this->render('modules/pagination.phtml');?>

<?php $this->render('contents/c_productlist.phtml');?>
<br class="clears"/>

<?php $this->render('modules/pagination.phtml');?>

<br class="clears"/>

</div>

<!-- extral intro for this category -->
<?php if(isset($docvar3)):?>
<div class="advanced_intro"><?php echo $docvar3;?></div>
<!-- end of extral intro -->
<?php endif;?>
<?php echo $this->render('contents/c_comments.phtml');?>
</div>

<?php $this->render('parts/body_left.phtml'); ?>
</div>
</div>

<?php echo $this->render('parts/footer.phtml'); ?>
</body>
<?php echo $this->render('parts/after_body.phtml'); ?>
</html>