<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/header.phtml'); ?>

<div class="main-content">
<div class="widget fancy">
<div class="w-head">
<h1>Create an Account</h1>
</div>

<?php if(count(getMessages(false)) > 0):?>
<div class="result_box"><?php echo themeMessages(); ?></div>
<?php endif;?>

	<div class="user-forms">

	<div id="client_message" style="display:none"></div>
            <div class="user-register">
	        <form action="<?php echo url('user/register');?>" method="post" name="regForm" onsubmit="javascript:return checkRegister()">
                <h1>Personal Information</h1>
                <div class="user-forms-border">
		                <div class="register_content user-info">
		                    <div class="name">
			                    <label><strong>Username:</strong><em  style="color:#CF0275;">*</em></label><br /> 
			                    <input type="text"  name="username"<?php if (isset($_POST['username'])) echo ' value="' . $_POST['username'] . '"' ?> class="elmbBlur"/>
			                    <div class="smallfont">Less than 12 characters</div>
		                    </div>
		                    <div class="email">
			                    <label><strong>E-mail:</strong><em  style="color:#CF0275;">*</em></label> <br />
			                    <input type="text" name="email"<?php if (isset($_POST['email'])) echo ' value="' . $_POST['email'] . '"' ?> class="elmbBlur"/>
		                    </div>
		                </div>
		        </div>
                <h1>Login Information</h1>
		        <div class="user-forms-border">
		                <div class="register_content password">
		                    <div class="passwd">
			                    <label><strong>Password:</strong><em  style="color:#CF0275;">*</em></label> <br />
			                    <input type="password"  name="password"  class="elmbBlur"/>
		                    </div>
		                    <div class="cfm-passwd">
		                    	<label><strong>Confirm Password:</strong><em  style="color:#CF0275;">*</em></label> <br />
		                    	<input type="password"  name="confirm_password"  class="elmbBlur"/>
		                    </div>

		                </div>
		        </div>
		        <div class="button-sets">
		        <p class="required">* Required Fields</p>
		        <p class="back-link"><a class="back-link" href="<?php echo url('');?>"><small>« </small>Back</a></p>
		                    <div class="register-submit">
		                    	<input type="hidden" class="register-submit button" value="create an account" />
		                    	<button class="button"><span><span>Create An Account</span></span></button>
		                    </div>
		        </div>
	                </form>
            	
        	</div>

    </div>
    
</div>

</div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>