

<!-- 一个广告标语，这个你可以去掉，也可以换成图片或者改变位置。 -->
<div class="contentslot popupopen">
     80%+ off Everything! Limited Time Only
</div>
<marquee>Chinese New Year Holiday Notice: Dear customers , we will be on holiday from 2 February to 14 February 2016.  During the holiday, you can still place orders, all the orders will be only processed after we come back to work from holiday, thank you for your cooperation!</marquee>
<!-- 广告标语结束 -->
