<div id="pRate" style="overflow:hidden;padding:10px 0;">
    <a class="button button-small toogleWriteReview" href="#write-a-review" style="float:right; padding-right:20px;">Write a Review</a>
	<div style="padding-top:5px;">
	<?php if(isset($product->pid) && $product->pid):
        echo widgetCallFunction('fivestars', 'getaveragestars', $product->pid, true);
    endif;?>
    <a href="#prReviews">(<span itemprop="reviewCount"><?php echo $commentCount;?></span> Reviews)</a>
    </div>

</div>