<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>

<div class="main-content">
<div class="scart_step4"></div>
<div class="general general1">
<div class="shoppingContainers user_edit">

<div style="background-color:#CCFFCC"><?php echo themeMessages(); ?></div>
<h2> <?php foreach (getMessages() as $message): echo $message['message']; endforeach;?></h2>

<div class="widget1 inner">

        <table cellspacing="0" cellpadding="0" class="order-callback" style="text-align:left;">
        <tbody>
        <?php if (isset($orderInfo)): ?>
            <tr>
                <th style="text-align:left;">Order No:</th>
                <td><?php echo isset($orderInfo->number)? $orderInfo->number : null;?></td>
                <th style="text-align:left;">Create at:</th>
                <td><?php echo isset($orderInfo->created)? date('F d, Y H:i:s',$orderInfo->created) : null;?></td>
            </tr>
            <tr>
                <th style="text-align:left;">Shipping Method:</th>
                <td><?php echo isset($orderInfo->shipping->name)? $orderInfo->shipping->name : null;?></td>
                <th style="text-align:left;">Payment Method:</th>
                <td><?php echo isset($orderInfo->payment->name) ? $orderInfo->payment->name : null;?></td>
            </tr>

            <tr>
                <th style="text-align:left;">Payable total:</th>
                <td><div><?php echo isset($orderInfo->pay_amount) ? c($orderInfo->pay_amount) : null?></div></td>
                <th style="text-align:left;">Payment Online</th>
                 <td><?php if(!isset($orderInfo->payment->online) || $orderInfo->payment->online) : echo isset($submitform) ? $submitform : null; endif;?></td>
            </tr>
            <tr>
            <th colspan="4">
            <div style="margin:5px auto;text-align:left;">
                	<form action="<?php echo $user->uid ? url('order/info/'.$orderInfo->oid) : url('user/login');?>">
            			<button type="submit" class="pay_button"><span><span>View Your Order</span></span></button>
                	</form>
        </div></th>
         <?php endif;?>
            </tr>
        </tbody>
        </table>
       
    </div>
</div>

</div>

</div>

</div>
<?php echo $this->render('parts/footer.phtml'); ?>

<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>