<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>

<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>
<div class="main-content">
<div class="scart_step2"></div>

<?php echo themeMessages(); ?>
<div id="client_message" style="display:none"></div>


<div class="scart_tit fiya">Fill in your address</div>
 <div class="scart_t"><span>Address</span></div>
<div class="general general1">


<form action="" method="post" name="checkoutForm" class="disable_on_submit" onsubmit="javascript: return checkCartShipping()">
    <input type="hidden" name="pids" id="pids" value="<?php echo $pids;?>"/>
    <input type="hidden" name="goods_amount" id="goods_amount" value = "<?php echo isset($cartInfo->goods_amount) ? $cartInfo->goods_amount : '0'; ?>"/>
	<input type="hidden" name="goods_number" id="goods_number" value = "<?php echo isset($cartInfo->goods_number) ? $cartInfo->goods_number : '0'; ?>"/>
	<input type="hidden" name="goods_weight" id="goods_weight" value = "<?php echo isset($cartInfo->goods_weight) ? $cartInfo->goods_weight : '0'; ?>"/>
	<input type="hidden" name="fromcart" value="<?php echo isset($fromcart) ? $fromcart : 0?>"/>
	<input type="hidden" name="ordertoken" value="<?php echo isset($ordertoken) ? $ordertoken : 0?>"/>
	<input type="hidden" id="delivery_cid" name="delivery_cid" />
	<input type="hidden" id="delivery_pid" name="delivery_pid" />
	

<?php $this->render('contents/checkout_shipaddress.phtml');?>
<?php $this->render('contents/checkout_shipmethod.phtml');?>
<?php $this->render('contents/checkout_paymethod.phtml');?>
<?php $this->render('contents/checkout_cartamount.phtml');?>

</form>
</div>


</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>

<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>