<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user; ?>

<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>
<div class="main-content">
<?php $this->render('modules/ads_topslot.phtml')?>
<?php echo $this->render('parts/body_left.phtml'); ?>


<div class="general">
<?php $this->render('modules/slider.phtml');?>
<div id="prodcut-channels" class="main-block">
<?php $this->render('modules/new-arrival.phtml');?>
<?php $this->render('modules/recommand.phtml');?>
<?php $this->render('modules/discounted.phtml');?>
</div>

<div>

<div style="text-align:left;">
<p>Evenings do not have to eventually turn into mundane sleeping sessions as long as you have a fantastic wardrobe of sexy cheap lingerie to constantly give your sweetheart a pleasant surprise. Keep that fire burning with ultra flattering and appealing cheap lingerie sets that come in a variety of styles, cuts, colors and materials. Make no mistake in choosing the right kind of sexy dose of clothing for those long nights in bed, whether it be fiery or sultry.</p>
<p>Different types of sexy cheap lingerie wholesale likewise cater to differing body types and of course, there are a variety of looks cut out for several women's tastes as well as occasions. The lean and long-legged could opt for teddy lingerie while the feminine and prim will look appealing in a variety of babydoll numbers. Vixens with small waistlines on the other hand may well go for cheap wholesale corset lingerie to put much emphasis on their great physique and look absolutely stunning at the same time. Of course, once in a while, it would be great and an even more pleasant surprise if one mixes it up a bit and go with a style that does not match ones personality. This is where the thrill comes in as well to keep things fresh and so nights will always be something to look forward to.</p>
<p>Since different styles also each have varying cuts, those gifted up top will definitely ooze sex appeal in a revealing plunging piece while flat-chested ones may pick a right kind of overbust cheap wholesale corsets that will give the busts some squeeze while at the same time putting much highlight to the tiny waist. The voluptuous and curvy should not worry either because sexy cheap lingerie wholesale are very versatile in size and would look flattering on any body type as long as the wearer knows her assets.</p>
<p>Among others, possible cheap lingerie wholesale cuts are plunging, backless, overbust, underbust, spaghetti strap, halter, tube, open front and open side. Among the materials are chiffon, satin or silk, lace, cotton, spandex and tulle. Some are simpler while others are dramatic in detail and put great attention to embellishments. </p>
<p>Whatever it is that would strike your fancy, wear cheap wholesale corsets with much pizzazz by coupling it with naughty accessories such as handcuffs, blindfold and of course, some nice perfume and an excellent ultra-appealing attitude to boot. Say good bye to boring nights and say hello to nights oozing with much heat with a wardrobe of cheap lingerie wholesale.</p>
</div>

</div>


</div>
</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>


<?php echo $this->render('parts/after_body.phtml'); ?>
<script src="<?php echo $tpldir. '/javascripts/jquery.flexslider.js';?>" type="text/javascript"></script>
<script type="text/javascript">
// Can also be used with $(document).ready()
$(window).load(function() {
    $('.flexslider').flexslider(
		{controlNav: "paging",slideshowSpeed: 3000, animationDuration: 600}
	);
	$('.flex-caption').each(function(){
		var flexabstract = $('p.abstract', $(this));
		var flexdetail = $('p.detail', $(this));
		if(!(flexabstract.length&&flexdetail.length)){
			$('h3', $(this)).css({'display':'none'});
		}
		});
});

</script>
</body>
</html>