<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body style="zoom:1">
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<?php $this->render('parts/navigation.phtml'); ?>
<div class="container">
<div class="main-content">
<div class="general article">

<?php $this->render('contents/a_category.phtml');?>

<div class="main-block main-block1">

<div class="widget">
<div class="w-head">
<h2 class="return"><?php echo $articleInfo->title;?></h2>
</div>
</div>

<!--  here comes the contents -->
<?php echo isset($articleInfo->content) ? $articleInfo->content : null?>
</div>

</div>
<div class="general_bottom"></div>
</div>
</div>

<div class=" clears"></div>

<?php echo $this->render('parts/footer.phtml'); ?>
</body>
<?php echo $this->render('parts/after_body.phtml'); ?>
</html>