<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body style="zoom:1">
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<?php $this->render('parts/navigation.phtml'); ?>

<div class="container">
<div class="main-content">
<div class="user-forms">
<div class="general">
<div class="shoppingContainers user_edit">

<!-- -->
<div class="widget inner">
<div class="w-head">
	<h2 class="return">Payment Received</h2>
</div>


    <div class="w-content">
<div><?php echo themeMessages(); ?></div>
<?php foreach (getMessages() as $message): echo $message['message']; endforeach;?>
        <table cellspacing="0" cellpadding="0" class="order-callback">
        <tbody>
        <?php if (isset($orderInfo)): ?>
            <tr>
                <th width="15%">Order No:</th>
                <td width="35%"><?php echo isset($orderInfo->number)? $orderInfo->number : null;?></td>
                <th width="15%">Create at:</th>
                <td width="35%"><?php echo isset($orderInfo->created)? date('F d, Y H:i:s',$orderInfo->created) : null;?></td>
            </tr>
            <tr>
                <th>Shipping Method:</th>
                <td><?php echo isset($orderInfo->shipping->name)? $orderInfo->shipping->name : null;?></td>
                <th>Payment Method:</th>
                <td><?php echo isset($orderInfo->payment->name) ? $orderInfo->payment->name : null;?></td>
            </tr>

            <tr>
                <th>Payable total:</th>
                <td><div><?php echo isset($orderInfo->pay_amount) ? c($orderInfo->pay_amount) : null?></div></td>
                <th>Payment Online</th>
            <td><?php if(!isset($orderInfo->payment->online) || $orderInfo->payment->online) : echo isset($submitform) ? $submitform : null; endif;?></td>
            </tr>

         <?php endif;?>
        </tbody>
        </table>
 
            <div style="margin:5px auto">
            <form action="<?php echo $user->uid ? url('order/info/'.$orderInfo->oid) : url('user/login');?>">
            <input type="hidden" class="button light" value="View Your Order Information"/>
            <button type="submit" class="button add2Cart"><span><span>View Order</span></span></button>
       	    </form>
            </div> 
        </div>
    </div>
</div>

</div>

</div>
</div>
</div>

<div class=" clears"></div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>