<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body style="zoom:1">
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<?php $this->render('parts/navigation.phtml'); ?>

<div class="container">
<div class="main-content">
<div class="widget">
<div class="w-head">
	<h2 class="return">
		Create New Password
	</h2>
	</div>
<form method="post" action="<?php echo url('user/editPassword/')?>">

	<div class="user_edit">
		<p>Welcome back <?php echo $username?>! Please set new password below for future login.</p>
		
		<?php echo themeMessages()?>
		
			<input type="hidden" name="token" value="<?php echo $token?>"/>
			<input type="hidden" name="username" value="<?php echo $username?>"/>
		<table style="width:60%; padding-top:20px;"><tbody>
		<tr>
			<th style="width:20%">Password<span class="required">*</span>: </th>
			<td style="width:60%"><input type="password"  name="newpwd"  class="elmbBlur"/></td>
		</tr>
		<tr><th>Confirm Password<span class="red">*</span>: </th>
			<td><input type="password"  name="newpwd2"  class="elmbBlur"/></td>
		</tr>
		<tr><th></th><td class="td-buttons"><button type="submit" class="button textbtn">Submit</button></td></tr>
		</tbody>
		</table>
	</div>

</form>


</div>



</div>
</div>

<div class=" clears"></div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>