<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body style="zoom:1">
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<?php $this->render('parts/navigation.phtml'); ?>

<div class="container">

<div class="main-content">
<div class="user-forms">
<div class="widget">
<div class="w-head">
	<h2 class="return">Password Forgotten</h2>
</div>
<div class="user_edit">
		<?php echo themeMessages() ?>
		<p>Enter your user name and email address below. We'll send you an email message containing your new password.</p>

<form method="post" action="<?php echo url('user/getPassword/')?>">

		<table style="margin-top:20px;">
			<tbody>
			<tr><th width="11%">Email address: *</th>
			<td width="47%"><input type="text" value="" class="elmbBlur"  name="email" /></td>
			<td width="42%"><button type="submit" class="button textbtn">Submit</button></td></tr>
			</tbody>
		</table>
</form>


</div>
</div>

</div>
</div>
</div>

<div class=" clears"></div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>