<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body style="zoom:1">
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<?php $this->render('parts/navigation.phtml'); ?>


<div class="container">
<div class="main-content">
<div class="general">

<?php $this->render('modules/slider.phtml');?>

<div id="prodcut-channels" class="main-block">
  <ul class="row">
     <li><a href="#"><img src="<?php echo themeResourceURI('images/sexy-corsets.jpg')?>" /></a></li>
     <li>
     <span><a href="#"><img src="<?php echo themeResourceURI('images/sexy-club-dresses.jpg')?>" /></a></span>
     <hgroup itemprop="name" class="desc"> <h2>Sexy Club Wear</h2> <h3>from $19.99</h3> <h4>Sweet. Soft. Sexy. Always.</h4> </hgroup>
     </li>
     <li><a href="#"><img src="<?php echo themeResourceURI('images/babydoll-lingerie.jpg')?>" /></a></li>
     <li>
     <span><a href="#"><img src="<?php echo themeResourceURI('images/party-dresses.jpg')?>" /></a></span>
     <hgroup itemprop="name" class="desc"> <h2>Sexy Lingerie</h2> <h3>Fashion. Modern</h3> <h4>Most-loved party styles. <br/>From ceremony to streets.</h4> </hgroup>
     </li>
  </ul>
</div>

</div>
</div>
</div>

<div class=" clears"></div>




<?php echo $this->render('parts/footer.phtml'); ?>


<?php echo $this->render('parts/after_body.phtml'); ?>
<script src="<?php echo $tpldir. '/javascripts/jquery.flexslider.js';?>" type="text/javascript"></script>
<script type="text/javascript">
// Can also be used with $(document).ready()
$(window).load(function() {
    $('.flexslider').flexslider(
		{controlNav: "paging",slideshowSpeed: 3000, animationDuration: 600}
	);
	$('.flex-caption').each(function(){
		var flexabstract = $('p.abstract', $(this));
		var flexdetail = $('p.detail', $(this));
		if(!(flexabstract.length&&flexdetail.length)){
			$('h3', $(this)).css({'display':'none'});
		}
	});
});
</script>
</body>
</html>