<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body style="zoom:1">
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<?php $this->render('parts/navigation.phtml'); ?>

<div class="container">
<div class="main-content">
<?php $this->render('contents/p_intro.phtml')?>
<?php $this->render('parts/body_left.phtml'); ?>
</div>
</div>

<div class=" clears"></div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/products.js'; ?>" type="text/javascript"></script>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f911222039d9281"></script>
</body>
</html>