<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body style="zoom:1">
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<?php $this->render('parts/navigation.phtml'); ?>
<div class="container">

<div class="main-content">
<div class="user-forms">

<div class="widget">
<div class="general checkout-result">
  <div class="userlinks body-left">
  <div class="panelSummary">
    <h2 class="return">Now You Can</h2>
    <ul class="userlinks">
		<li><a href="<?php echo url('user/panel');?>">Visit User Center</a></li>
		<li><a href="<?php echo url('user/info');?>">Change Baic Settings</a></li>
		<li><a href="<?php echo url('user/pwd');?>">Change Password</a></li>
		<li><a href="<?php echo url('order/list/first');?>">View Order History</a></li>
		<li><a href="<?php echo url('user/logout');?>">Log Out</a></li>
	</ul>
<a href="<?php echo url('product/list/')?>" class="button continueBtn textbtn">Continue Shopping</a>
</div>
</div>
  <div class="main-block main-block1">
     <h2 class="return">Register Successful</h2>
  <div class="uc-welcome">
    <p class="welcome">Your Account Has Been Created!</p>
  </div>
        <ul class="info-list">
        <li><em></em>You can now take advantage of member privileges to enhance your online shopping experience with us.</li> 
        <li><em></em>If you have ANY questions about the operation of this online shop, please email the store owner.</li>
        <li><em></em>A confirmation has been sent to the provided email address. If you have not received it within the hour, please <a href="<?php echo url('article/contact-us.html')?>" class="red">contact us</a>.</li>  
        </ul>
</div>
</div>
</div>
</div>
</div>
</div>
<div class=" clears"></div>
<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>