<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body style="zoom:1">
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<?php $this->render('parts/navigation.phtml'); ?>
<div class="container">
<div class="main-content">
<div class="general">

<div class="main-block main-block1">
<div class="widget">
<div class="w-head">
<span class="product-count"><?php echo $productCount;?> Items</span>
<h1><?php echo ucwords($keyword)?></h1>
</div>
<div id="productlist">
<div class="w-head cat-filters"> 
<div class="pySort">
	<?php $this->render('contents/search_viewoptions.phtml')?>
	<?php $this->render('contents/search_filter_form.phtml');?>
	
	<div class="widget w-resultSortBar">
	<?php $this->render('contents/c_sortoptions.phtml')?>
	<?php $this->render('modules/pagination.phtml');?>
	</div>
</div>
</div>
<br class="clear"/>
<?php $this->render('contents/c_productlist.phtml');?>

<br class="clear"/>

<div class="w-head cat-filters"> 
<div class="pySort">
	<?php $this->render('contents/search_viewoptions.phtml')?>

	<div class="widget w-resultSortBar">
	<?php $this->render('contents/c_sortoptions.phtml')?>
	<?php $this->render('modules/pagination.phtml');?>
	</div>
</div>
</div>

</div>
</div>

<!-- extral intro for this category -->
<?php if(isset($docvar3)):?>
<div class="advanced_intro"><?php echo $docvar3;?></div>
<!-- end of extral intro -->
<?php endif;?>
<?php echo $this->render('contents/c_comments.phtml');?>
</div>

<?php $this->render('parts/body_left.phtml'); ?>

</div>
<div class="general_bottom"></div>
</div>
</div>
<div class=" clears"></div>
<?php echo $this->render('parts/footer.phtml'); ?>
</body>
<?php echo $this->render('parts/after_body.phtml'); ?>
</html>