<div class="flex-container" style="">
<div class="flexslider">
<div class="bannerbg1"></div>
<?php if(isset($hdpArr) && $hdpArr):?>
  <ul class="slides">
  	<?php  foreach ($hdpArr as $v):?>
    <li flex-link="<?php echo $v->url ?>" flex-title="<?php echo $v->title;?>" >
    <a href="<?php echo $v->url ?>">
      <img src="<?php echo urlimg('718x317',$v->filepath); ?>"  title="<?php echo $v->title;?>" alt= '<?php echo $v->title;?>'/>
    </a>
    <div class="flex-caption"><h3><?php echo $v->title;?></h3>
  	<?php echo $v->description;?>
    </div>
    </li>
    <?php endforeach;?>
  </ul>
      <?php endif;?>
<div class="d2"></div>
</div>

</div>
      