<div style="display:none;">
<?php 
$timezone = date_default_timezone_get();
$date = date('m/d/Y h:i:s a', time());
echo "Current time: " . $date . " (" . $timezone . ")". "\n";
echo "Memory usage: " . round(memory_get_usage()/1024,2) . "KB\n";
?>
</div>


<?php global $basePath ?>
<script type="text/javascript">var basePath = '<?php echo plain($basePath) ?>';</script>
<script language="javascript" src="<?php echo url('scripts/jquery-1.7.2.min.js') ?>" type="text/javascript"></script>
<script language="javascript" src="<?php echo url('scripts/jquery-ui-1.8.19.custom.min.js') ?>" type="text/javascript" ></script>
<?php if (isset($_SESSION['preview'])): ?>
<script language="javascript" src="<?php echo url('scripts/preview.js') ?>" type="text/javascript"></script>
<?php endif ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/front.js';?>" type="text/javascript"></script>
<script src="<?php echo $tpldir. '/javascripts/after_body.js';?>" type="text/javascript"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45096481-1', 'auto');
  ga('send', 'pageview');

</script>
<script>
$.fn.center = function () {
    this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) + 
                                                $(window).scrollTop()) + "px");
    this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) + 
                                                $(window).scrollLeft()) + "px");
    this.css("position","absolute");
    return this;
};

$(function() {
<!--	--><?php //if(!isset($_SESSION['promote'])):?>
//	$('#overlay').show();
//	$('#wholesale-box').center().show();
//	<?php //$_SESSION['promote'] = 1;?>
<!--	--><?php //endif;?>
//	$(window).resize(function() {
//		$('#wholesale-box').center();
//	});

//	$('#wholesale-link').click(function(event){
//		event.preventDefault();
//		$('#overlay').show();
//		$('#wholesale-box').center().fadeIn();
//	});

//	$('#confirm-btn').click(function(event){
//		event.preventDefault();
//		$.ajax({
//			type: "POST",
//	        url: "<?php //echo url('user/addwholesaleuser');?>//",
//	    	data: $("#wholesale-box form").serialize(), // serializes the form's elements.
//	        success: function(data) {
//				var ret = $.parseJSON(data);
//	       		if (ret.success) {
//	       			$('#wholesale-box form').hide();
//	       			$('#alert_info').hide();
//					$('#wholesale-box #message').show();
//					$('#confirm-btn').hide();
//	       		} else {
//		       		alert(ret.message);
//	       		}
//	       }
//		});
//	});

//	$('#cancel-btn').click(function(event){
//		event.preventDefault();
//		$('#overlay').hide();
//		$('#wholesale-box').fadeOut();
//	});
});
</script>