<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/header.phtml'); ?>


<div class="main-content">

<div class="w-head">
	<h1>Password Forgotten</h1>
</div>
<div class="user_edit">

		<p>Enter your user name and email address below. We'll send you an email message containing your new password.</p>
		<?php echo themeMessages() ?>
<form method="post" action="<?php echo url('user/getPassword/')?>">

		<table>
			<tbody>
			<tr><th>Email:<em class="required">*</em></th>
			<td><input type="text" value="" name="email" /></td>
			<td><button type="submit" class="button"><span><span>Submit</span></span></button></td></tr>
			</tbody>
		</table>
</form>


</div>


</div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>