<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php $this->render('parts/header.phtml');?>

<div class="main-content">
<div class="general">

<?php $this->render('modules/slider.phtml');?>

<ul class="san">
  <li><a href="<?php echo url('babydoll.html');?>"><img alt="babydoll lingerie" src="<?php echo $this->themeResourceURI('images/left.jpg');?>" /></a></li>
  <li><a href="<?php echo url('corsets.html');?>"><img alt="sexy corsets" src="<?php echo $this->themeResourceURI('images/center.jpg');?>" /></a></li>
  <li class="last"><a href="<?php echo url('teddies.html');?>"><img alt="teddy lingerie" src="<?php echo $this->themeResourceURI('images/right.jpg');?>" /></a></li>
</ul>
<br class="clear" />
<div class="homepage-spotlight-footer">
<div class="sml left-headline">Sexy lingerie is more than an undergarment!</div>
<div class="mid">From our sheer, sexy corsets to robes, from babydoll lingerie to camisoles, our sexy lingerie is pure sensuality. All come in as many colors, styles, and accessory options as you could desire. 
</div>
<div class="sml right-button"><a class="shopping-button" href="<?php echo url('sexy-lingerie.html');?>">SHOP NOW</a></div>
</div>
</div>
</div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml');?>

<script src="<?php echo $tpldir. '/javascripts/jquery.flexslider.js';?>" type="text/javascript"></script>
<script type="text/javascript">
// Can also be used with $(document).ready()
$(window).load(function() {
    $('.flexslider').flexslider(
		{controlNav: "thumbnails",slideshowSpeed: 30000000, animationDuration: 600}
	);
	$('.flex-caption').each(function(){
		var flexabstract = $('p.abstract', $(this));
		var flexdetail = $('p.detail', $(this));
		if(!(flexabstract.length||flexdetail.length)){
			$('h3', $(this)).css({'display':'none'});
		}
		});
});
</script>

</body>
</html>