<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user; ?>
<?php $this->render('parts/header.phtml'); ?>
<div class="main-content">
<div><img class="checkout_process_indicator" src="<?php echo $this->themeResourceURI('images/checkout_process_04.jpg');?>" alt="1" height="60" width="952"></div>
<div class="general">
<div class="main-block">
    <div class="w-head">
        <h2><span>Payment Result</span></h2>
    </div>

<div class="shoppingContainers user_edit">
<?php echo themeMessages(); ?>
<div class="widget inner">

        <?php foreach (getMessages() as $message): echo ''; endforeach;?>
        <table cellspacing="0" cellpadding="0" class="order-callback"  style="width:100%">
        <tbody>
        <?php if (isset($orderInfo)): ?>
            <tr>
                <th width="20%">Order No:</th>
                <td width="30%"><?php echo isset($orderInfo->number)? $orderInfo->number : null;?></td>
                <th width="20%">Create at:</th>
                <td width="30%"><?php echo isset($orderInfo->created)? date('F d, Y H:i:s',$orderInfo->created) : null;?></td>
            </tr>
            <tr>
                <th width="20%">Shipping Method:</th>
                <td width="30%"><?php echo isset($orderInfo->shipping->name)? $orderInfo->shipping->name : null;?></td>
                <th>Payment Method:</th>
                <td><?php echo isset($orderInfo->payment->name) ? $orderInfo->payment->name : null;?></td>
            </tr>

            <tr>
                <th>Payable total:</th>
                <td><div><?php echo isset($orderInfo->pay_amount) ? c($orderInfo->pay_amount) : null?></div></td>
                <th>Payment Status</th>
                
                 <td>
                 <?php 
                 if($orderInfo->status_payment==0):echo 'Not Paid';
                 elseif($orderInfo->status_payment==1):echo 'Paid';
                 elseif($orderInfo->status_payment==2):echo 'Partially Refunded';
                 elseif($orderInfo->status_payment==3):echo 'Refunded';
                 endif;?>
				 <?php if(!isset($orderInfo->payment->online) || $orderInfo->payment->online) : echo isset($submitform) ? $submitform : ''; endif;?></td>
            </tr>
         <?php endif;?>
        </tbody>
        </table>
        <div style="margin:10px auto">
                	<form action="<?php echo $user->uid ? url('order/info/'.$orderInfo->oid) : url('user/login');?>">
                		<input type="hidden" class="button light" value="View Your Order Information"/>
                		<button type="submit" class="button"><span><span>View Your Order Information</span></span></button>
                	</form>
        </div>
    </div>
</div>

</div>
</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>