<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php $this->render('parts/header.phtml');?>

<div class="main-content">
<div class="general-">

<?php $this->render('modules/slider.phtml');?> 
<div class="clears"/></div>
<!--  slider2 -->
<div id="slider2">
			<div id="kicker-row">
				<div id="kickerblock">
				<div style="position: absolute; bottom: 68px; font-size: 20px; text-transform: uppercase; width: 120px; right: 0px; text-align: center;">
					<p style="font-size: 14px; font-weight: bold; color: rgb(173, 0, 141);">Fabulous</p>
					<h4 style="">Babydoll</h4>
				</div>
					<a href="<?php echo url('babydoll.html');?>"><img src="<?php echo $this->themeResourceURI('images/babydoll-lingerie.jpg');?>" title="Fabulous Babydoll" alt="Babydoll Lingerie"/></a>
			 	</div>
				<div id="kickerblock">
					<a href="<?php echo url('sexy-dresses.html');?>"><img src="<?php echo $this->themeResourceURI('images/sexy-dresses.jpg');?>" title="Hot Sexy Dresses" alt="Sexy Dresses"/></a>
					
			 	</div>
				<div id="kickerblock-last">
					<div style="font-size: 20px; position: absolute; left: 0px; top: 10px; text-align: center; text-transform: uppercase; width: 100px;">
						<p style="color: rgb(173, 0, 141); text-align: left; font-size: 12px; margin-bottom: 50px; padding-left: 10px; width: 150px; font-weight: bold;">Timeless Trends</p>
						<h4 style="margin-left: 10px;">Sexy Corsets</h4>
					</div>
					<a href="<?php echo url('corsets.html')?>"><img src="<?php echo $this->themeResourceURI('images/sexy-corsets.jpg');?>" title="Sexy Corsets" alt="Sexy Corsets"/></a>
			 	</div>
			</div>
</div>


<!-- best seller -->
<div id="bestSellerContainer">
        <div id="bestSellerContent" style="height:300px;position:relative;">
            <div id="bestSellerHeader">
                <img id="bestSellerImage" src="<?php echo $this->themeResourceURI('images/BestSeller-header.jpg');?>"/>
            </div>
       <?php $this->render('modules/new-arrival.phtml');?>
       </div>
</div>
    
<br class="clear" />
<div id="bestSellerHeader">
                <img id="bestSellerImage" src="<?php echo $this->themeResourceURI('images/BRANDS.jpg');?>"/>
            </div>


<ul  class="trademark">
<li><a href="<?php echo url('+brand-coquette.html');?>"><img src="<?php echo $this->themeResourceURI('images/coquetteLogo.png');?>"/></a></li>
<li><a href="<?php echo url('+brand-seven-til-midnight.html');?>"><img src="<?php echo $this->themeResourceURI('images/seventilmidnight.png');?>" /></a></li>
<li><a href="<?php echo url('+brand-be-wicked.html');?>"><img src="<?php echo $this->themeResourceURI('images/BE_logo.png');?>"/></a></li>
<li><a href="<?php echo url('+brand-shirley-of-hollywood.html');?>"><img src="<?php echo $this->themeResourceURI('images/shirleyofhollywood.png');?>"/></a></li>
<li style="margin-right:0; padding:0;"><a href="<?php echo url('+brand-elegant-moments.html');?>"><img src="<?php echo $this->themeResourceURI('images/howcool_logo.png');?>" /></a></li>
<li><a href="<?php echo url('+brand-escante.html');?>"><img src="<?php echo $this->themeResourceURI('images/121218_4_escante_ouv.png');?>" /></a></li> 
<li><a href="<?php echo url('+brand-allure-leather.html');?>"><img src="<?php echo $this->themeResourceURI('images/logo111.png');?>"/></a></li>
<li><a href="<?php echo url('+brand-g-world-intimates.html');?>"><img src="<?php echo $this->themeResourceURI('images/GworldLogo.png');?>"/></a></li>
</ul>


</div>
</div>


<?php echo $this->render('parts/footer.phtml'); ?>


<?php echo $this->render('parts/after_body.phtml'); ?>


<script src="<?php echo $tpldir. '/javascripts/jquery.flexslider.js';?>" type="text/javascript"></script>
<script type="text/javascript">
// Can also be used with $(document).ready()
$(window).load(function() {
    $('.flexslider').flexslider(
		{controlNav: "thumbnails",slideshowSpeed: 6000000, animationDuration: 600}
	);
	$('.flex-caption').each(function(){
		var flexabstract = $('p.abstract', $(this));
		var flexdetail = $('p.detail', $(this));
		if(!(flexabstract.length&&flexdetail.length)){
			$('h3', $(this)).css({'display':'none'});
		}
	});
});

</script>

</body>
</html>