<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/header.phtml'); ?>

<div class="main-content">
<div class="widget fancy">

<div class="w-head">
<h1></h1>
</div>

	<div class="user-forms">

<!-- User Login -->        	
          <form action="<?php echo url('user/login');?>" method="post">
            <div class="user-login">
                <h1>LOG-IN REGISTERED USERS</h1>
                <div class="user-forms-border">
                <p style="margin-left:8px;">Enter your email and password below to access your order status and manage your account. </p>
                <?php echo themeMessages() ?>
                <div id="client_message" style="display:none"></div>
					<div class="login_content">
	                    <div class="name">
	                    	<label><strong>Email:</strong></label><br/>
	                    	<input type="text" value="" name="username"  class="elmbBlur"/>
	                    </div>
	                    <div class="passwd">
	                    	<label><strong>Password:</strong></label><br/>
	                    	<input type="password" value="" name="password"  class="elmbBlur"/>
					        
	                    </div>
						<div class="login-forgetpw">
						<a href="<?php echo url('user/getPassword')?>">Forgot Your Password? </a>
						</div>
	                </div>
                </div>
              <div class="clear"></div>

	            <div class="login-submit">
	            <input type="hidden" class="login-submit button" value="Sign In"/>
	            <button class="button"><span><span>LOG-IN</span></span></button>
	            </div>

            </div>

        </form>
<!-- User Login End -->

<!-- User Register -->
            <div class="user-register">
	        <form action="<?php echo url('user/register');?>" method="post" name="regForm" onsubmit="javascript:return checkRegister()">
                <h1>NEW USERS</h1>
                <div class="user-forms-border">
		                <div class="register_content">
		                    <div class="name">
			                    <label><strong>Username:</strong><em  style="color:#CF0275;">*</em></label><br /> 
			                    <input type="text"  name="username"<?php if (isset($_POST['username'])) echo ' value="' . $_POST['username'] . '"' ?> class="elmbBlur"/>
		                    </div>
		                    <div class="email">
			                    <label><strong>E-mail:</strong><em  style="color:#CF0275;">*</em></label> <br />
			                    <input type="text" name="email"<?php if (isset($_POST['email'])) echo ' value="' . $_POST['email'] . '"' ?> class="elmbBlur"/>
		                    </div>
		                    <div class="passwd">
			                    <label><strong>Password:</strong><em  style="color:#CF0275;">*</em></label> <br />
			                    <input type="password"  name="password"  class="elmbBlur"/>
		                    </div>
		                    <div class="cfm-passwd">
		                    	<label><strong>Confirm Password:</strong><em  style="color:#CF0275;">*</em></label> <br />
		                    	<input type="password"  name="confirm_password"  class="elmbBlur"/>
		                    </div>
				    
		                </div>
				<p class="required">* Required Fields</p>
		        </div>
		        
		        <div class="register-submit">
					<input type="hidden" class="register-submit button" value="create an account" />
					<button class="button"><span><span>REGISTER</span></span></button>
				</div>
	           </form>
        	</div>
<!-- User Register End -->

	  </div>
     </div>
    </div>


<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>