<div id="leftNavTitle">
            <a><font class="Categtt" style=""><span><?php echo $termInfo->name;?></span></font> </a>
</div>

<div id="cat-lists" class="widget">
<?php $isTag = isset($termInfo) && $termInfo->vid == Taxonomy_Model::TYPE_TAG;?>
<div class="side-subcat-div">
<?php if(isset($category)): foreach($category as $k=>$v):?>
    <ul><li class="top-cat" ><a href="<?php echo url(categoryURL($v->path_alias));?>" class="<?php if(isset($termInfo) && $v->name == $termInfo->name)  echo 'red'?>"><?php echo ucwords($v->name);?></a></li>
<?php foreach($v->sub as $k2=>$v2):?>
		<li><a href="<?php echo url(categoryURL($v2->path_alias));?>" <?php if(isset($termInfo) && $v2->name == $termInfo->name)  echo 'class="red"'?>><?php echo ucwords($v2->name);?></a></li>
<?php endforeach;?>
	</ul>
<?php endforeach;endif;?>
</div>
</div>