<div class="cart-list" id="cart">
<h2>Shopping Cart</h2>
<form class="form-cartpost" id="itemsForm" method="post" action="<?php echo url('cart/cartpost');?>">
<input id="cart_submit" type="hidden" name="checkout"/>
<table class="cart-list-table" cellspacing="0" cellpadding="0">
	<thead>
		<tr>
             <th width="50%" class="">ITEM NAME</th>
             <th width="15%">ITEM PRICE</th>
             <th width="20%" class="prQuant">QUANTITY</th>
             <th width="15%" class="prAmount">PRICE</th>
        </tr>
    </thead>
<tbody>     
<?php if ($cartInfo->product) :
foreach ($cartInfo->product as $k => $v): ?>
<tr id="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>" class="" valign="top">
    <td class="prName">
        <a href="<?php echo url($v->url);?>" title="S<?php echo isset($v->name) ? $v->name : null ?>"><img class="product_img" alt="<?php echo isset($v->name) ? $v->name : null ?>" title="<?php echo isset($v->name) ? $v->name : null ?>" src="<?php echo urlimg('60x90', $v->filepath) ?>"></a>
		<input type="hidden" class="checkitem" name="cart_item_id_checked[]" checked value="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>"/>
		<h4><a href="<?php echo url($v->url);?>" title="<?php echo isset($v->name) ? $v->name : null ?>"><?php echo isset($v->name) ? $v->name : null ?></a></h4>
<?php if(isset($v->data) && $v->data):
	  	foreach($v->data as $dk => $dv):
			echo '<p class="prAttr">'.$dk.'&nbsp;-&nbsp;'.$dv.'</p>';
		endforeach;
      else: echo '&nbsp;';
      endif;?>
	  <a href="<?php echo url('cart/deleteproductfromcart/'.$v->cart_item_id);?>" title="Remove" class="remove ir"><img src="<?php echo $this->themeResourceURI('images/no.png');?>" class="vam"/>Remove</a>
    </td>
    <td class="prPrice">
		<p class="listPrice"><del><?php echo isset($v->list_price) ? c($v->list_price) : null;?></del></p>
		<p class="price"><?php echo isset($v->price) ? c($v->price) : null;?></p>
   </td>
    <td class="prQuant">
		<input type="hidden" value="<?php echo isset($v->pid) ? $v->pid : null ?>" name="pids[]"/>
        <input type="hidden" value="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>" name="cart_item_ids[]"/>
    	<input value="<?php echo isset($v->qty) ? $v->qty : null ?>" name="qtys[]" size="3" alt="<?php echo isset($v->qty) ? $v->qty : null ?>" id="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>" class="ajax_qty elmbBlur" title="<?php echo $v->sell_min ? $v->sell_min : 0 ?>,<?php echo $v->sell_max ? $v->sell_max : 0 ?>" rel="<?php echo isset($v->price) ? $v->price : null ?>"/>
    </td>
    <td class="prAmount">
        <span class="payPrice"><span class="numVal"><?php echo isset($v->qty) ? c($v->price * $v->qty) : null;?></span></span>
    </td>
</tr>

<?php endforeach; endif;?>
</tbody>

<tfoot>
<tr class="scTotalSaving">
      <td height="31" colspan="2" class="blank"></td>
      <td width="24%" align="right"><strong>YOUR TOTAL SAVINGS:</strong></td>
	<td class="total" width="10%"><strong> -<span class="numVal"><?php echo isset($cartInfo->total_save_amount) ? c($cartInfo->total_save_amount) : null?></span></strong></td>
</tr>
<tr class="scSumAmount">
     <td class="cart-funcs" colspan="2"><a title="Continue Shopping" class="textbtn contShopping left" href="<?php echo url('browse/all.html');?>">Shop More</a> <a href="<?php echo url('cart/');?>" class="textbtn contShopping left">Update Cart</a> <a href="javascript:submit_shopping_cart('delete')" class="textbtn contShopping left clearcartBtn">Clear Cart</a></td>
<td class="total"><strong>CART TOTAL</strong></td>
<td class="total"><strong class="totalPrice"><span class="numVal"><?php echo isset($cartInfo->goods_amount) ? c($cartInfo->goods_amount) : null?></span></strong></td>
</tr>
<tr class="last">
<td colspan="4" class="checkout-types"  align="right"><?php if(isset($this->user) && $this->user->uid):?>
	<a title="Proceed to Checkout" class="checkoutBtn button" href="javascript:submit_shopping_cart('checkout')">Check Out</a>
<?php else:?>
    <a title="Proceed to Checkout" class="checkoutBtn button" href="<?php echo url('user/login/')?>">Check Out</a>
<?php endif?></td>
</tr>
</tfoot>
</table>

</form>
</div>