<div class="widget">
<div class="w-head" style="margin-top:20px;">
<h1 style="margin-left:0;">Welcome, <span class="header-uname"><?php echo ($user->nickname == '') ? $user->name : $user->nickname;?>!</span></h1>
</div>

<div class="w-content">
<div class="uc-welcome">
    <p class="welcome">Welcome to our member center! We will be happy to Serve you!</p>
    <p class="last_login">Your last login time:<?php echo date('m-d-Y',$user->login_timestamp);?></p>
</div>
<div class="widgetinner">
<div class="w-head">
<h3>User Information</h3>
</div>
<div class="uc-wrapper">
    <div class="statistics">
        <p>Your Integral: <?php if(isset($user->points)) echo $user->points;?></p>
        <p>Your total orders' transactions: <?php if(isset($orderscount)) echo $orderscount?> </p>
        <p>View your <a href="<?php echo url('order/list/')?>"><strong>order history</strong></a></p>
    </div>
</div>
</div>
</div>
</div>
