<?php echo $this->render('before_body.phtml'); ?>
<body>
<?php echo $this->render('header.phtml'); ?>

<div class="bodyer">

  <h1 id="breadcrumb"><a href="http://www.iwantlingerie.com/">Home</a>&nbsp;&gt;&nbsp;<a href="<?php echo url('usr/getPassword')?>">Password Forgotten</a></h1>

<div id="wrapper-m">
<div class="widget w-forgetPwd">
<form method="post" action="<?php echo url('user/getPassword/')?>">
	<h2 class="top">
		Password Forgotten		<a class="big block fr" href="<?php echo url('user/login')?>">&lt;&lt; Back</a>
	</h2>
	<div class="body">
		<p>Enter your user name and email address below. We'll send you an email message containing your new password.</p>
		
		<?php echo themeMessages() ?>
		
		<p><span class="label">Email address: </span><span class="red">*</span>
			<span style="position: relative;">
				<input type="text" value="" name="email" class="input elmbBlur">
			</span>
			<button type="submit" class="textbtn">Submit</button>
		</p>
	</div>
	<p class="bottom"><a class="big block fr" href="<?php echo url('user/login')?>">&lt;&lt; Back</a></p>

</form>
</div>
</div>
</div>


<?php echo $this->render('footer.phtml'); ?>
</body>
<?php echo $this->render('after_body.phtml'); ?>
</html>