<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>
<div class="main-content">
<?php $this->render('modules/ads_topslot.phtml')?>
<?php $this->render('parts/breadcrumb.phtml')?>
<div class="general cat">

<?php $this->render('contents/c_intro.phtml');?>

<div class="main-block">
<div class="widget" id="productlist">
<div class="w-head cat-filters"> 
<?php $this->render('contents/c_filter_form.phtml');?>
<div class="widget w-resultSortBar" id="resultSortBar">
	<div class="all-items" style="margin-right:30px;float:left;text-transform: capitalize;">
<?php echo ($page - 1)* $pageRows + 1;?> - 	
<?php echo ($productCount < $page * $pageRows)? ($productCount - ($page - 1)* $pageRows) : $page * $pageRows;?>
 of all
 <?php echo $productCount;?> Items</div>
	<?php $this->render('contents/c_sortoptions.phtml')?>
	<?php $this->render('contents/c_viewoptions.phtml')?>
 	<?php $this->render('modules/pagination.phtml');?>
</div>
</div>
<?php $this->render('contents/c_productlist.phtml');?>
<br class="clear"/>
<div class="widget w-resultSortBar" id="resultSortBar" style="padding-top:10px;margin-top:10px;">
	<?php $this->render('contents/c_sortoptions.phtml');?>
	<?php $this->render('modules/pagination.phtml');?>
</div>
</div>

<!-- extral intro for this category -->
<?php if(isset($docvar3)):?>
<div class="advanced_intro"><?php echo $docvar3;?></div>
<!-- end of extral intro -->
<?php endif;?>
<?php echo $this->render('comments/popular_review.phtml');?>
</div>

<?php $this->render('parts/body_left.phtml'); ?>

</div>
<div class="general_bottom"></div>
</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml');?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/productlist.js'; ?>" type="text/javascript"></script>
</body>
</html>