<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user; ?>
<?php $this->render('parts/header.phtml'); ?>
<div class="main-content">
<div class="widget fancy">
  <table width="100%" cellpadding="0" cellspacing="0">
    <tbody><tr>
      <td width="20%"><span class="step_count"><font><font>1.</font><font>Shopping Cart</font></font></span></td>
      <td width="7%"><span class="arrow spirit"></span></td>
      <td width="20%"><span class="step_count step_count_active"><font><font>2.</font><font>Place Order</font></font></span></td>
      <td width="7%"><span class="arrow spirit"></span></td>
      <td width="20%"><span class="step_count"><font><font>3.</font><font>Payment</font></font></span></td>
      <td width="6%"><span class="arrow spirit"></span></td>
      <td width="20%"><span class="step_count"><font><font>4.</font><font>Payment Completed</font></font></span></td>
    </tr>
  </tbody>
  </table>
</div>
<div class="general">


<?php if(count(getMessages(false)) > 0):?>
<div class="result_box"> <?php echo themeMessages(); ?></div>
<?php endif;?>

<div id="client_message" style="display:none"></div>
<form action="" method="post" name="checkoutForm" class="disable_on_submit" onsubmit="javascript: return checkCartShipping()">
    <input type="hidden" name="pids" id="pids" value="<?php echo $pids;?>"/>
    <input type="hidden" name="goods_amount" id="goods_amount" value = "<?php echo isset($cartInfo->goods_amount) ? $cartInfo->goods_amount : '0'; ?>"/>
	<input type="hidden" name="goods_number" id="goods_number" value = "<?php echo isset($cartInfo->goods_number) ? $cartInfo->goods_number : '0'; ?>"/>
	<input type="hidden" name="goods_weight" id="goods_weight" value = "<?php echo isset($cartInfo->goods_weight) ? $cartInfo->goods_weight : '0'; ?>"/>
	<input type="hidden" name="fromcart" value="<?php echo isset($fromcart) ? $fromcart : 0?>"/>
	<input type="hidden" name="ordertoken" value="<?php echo isset($ordertoken) ? $ordertoken : 0?>"/>
	<input type="hidden" id="delivery_cid" name="delivery_cid" />
	<input type="hidden" id="delivery_pid" name="delivery_pid" />

<?php $this->render('contents/checkout_shipaddress.phtml');?>
<?php $this->render('contents/checkout_shipmethod.phtml');?>
<?php $this->render('contents/checkout_paymethod.phtml');?>
<?php $this->render('contents/checkout_cartamount.phtml');?>




</form>
</div>
</div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/manage_address.js'?>" type="text/javascript"></script>
<?php echo $scripts;?>
</body>
</html>