<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/header.phtml'); ?>


<div class="main-content">
<div class="widget">
<div class="user_edit user_edit1">
<div class="w-head">
	<h2>Password Forgotten</h2>
</div>

<?php if(count(getMessages(false)) > 0):?>
<div class="result_box"><?php echo themeMessages(); ?></div>
<?php endif;?>

		<p>Enter your user name and email address below. We'll send you an email message containing your new password.</p>
		<form method="post" action="<?php echo url('user/getPassword/')?>">

		<table width="100%">
			<tbody>
			<tr><th width="12%" align="left">Email address: *</th>
			<td width="19%"><input type="text" value="" name="email" class="elmbBlur"/></td>
			<td width="69%"><button type="submit" class="button">Submit</button></td></tr>
			</tbody>
		</table>
</form>
</div>
</div>


</div>

<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>