<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php $this->render('parts/header.phtml');?>

<div class="main-content">
<?php $this->render('parts/breadcrumb.phtml')?>
<div class="general">
<div id="prodcut-channels" class="main-block">

<?php $this->render('contents/search_intro.phtml');?>
<?php $this->render('contents/search_filter_form.phtml');?>
<div class="widget" id="productlist">

<div class="widget w-resultSortBar">
	<div class="f_left num_show">We found <span class="b" id="products-num"><?php echo $productCount;?></span> items for your choices.</div>
	<?php $this->render('contents/c_sortoptions.phtml');?>
	<?php $this->render('contents/search_viewoptions.phtml')?>
</div>
<br class="clears" />
<?php $this->render('modules/pagination.phtml');?>

<?php $this->render('contents/c_productlist.phtml');?>
<br class="clears"/>

<?php $this->render('modules/pagination.phtml');?>

<br class="clears"/>

</div>

<!-- extral intro for this category -->
<?php if(isset($docvar3)):?>
<div class="advanced_intro"><?php echo $docvar3;?></div>
<!-- end of extral intro -->
<?php endif;?>
<?php echo $this->render('contents/c_comments.phtml');?>
</div>

<?php $this->render('parts/body_left.phtml'); ?>
</div>
</div>

<?php echo $this->render('parts/footer.phtml'); ?>
</body>
<?php echo $this->render('parts/after_body.phtml'); ?>
</html>