<div class="body-left">

<div id="wrapper-left">

<div id="cat-lists" class="widget">

<div class="w-head ordinary">
	<h2 class="side-subcat-title">Articles </h2>
</div>
<div class="side-subcat-div">
<?php if(isset($helpList)):foreach($helpList as $k=>$article_list):?>

    <ul><li><?php echo ucwords($k);?></li>
<?php foreach ($article_list as $v):?>
		<li><a href="<?php echo url($v->url)?>" class="<?php if($articleInfo->title == $v->title) echo 'red'?>"><?php echo ucwords($v->title);?></a></li>
<?php endforeach;?>
	</ul>
<?php endforeach;endif;?>
</div>

<a class="more" title="Visit Article Center" href="<?php echo url('articletype/all.html')?>">All &gt;&gt;</a>

</div>
</div>
<?php ?>
</div>