<div class="body-left">

<div id="wrapper-left">

<div id="cat-lists" class="widget">

<div class="w-head ordinary">
	<h2 class="side-subcat-title">User Home</h2>
</div>
<div class="side-subcat-div">
    <ul><li>My Orders</li>
		<li><a href="<?php echo url('order/list/first');?>">Order History</a></li>
	</ul>
    <ul><li>Account settings</li>
        <li><a href="<?php echo url('user/panel');?>">Member Home</a></li>
        <li><a href="<?php echo url('user/info');?>">Personal Information</a></li>
        <li><a href="<?php echo url('user/pwd');?>">Change Password</a></li>
        <li><a href="<?php echo url('user/logout');?>">Exit</a></li>
    </ul>	
</div>

</div>
</div>
<?php ?>
</div>