<div class="cart-list">
<form class="form-cartpost" id="itemsForm" method="post" action="<?php echo url('cart/cartpost');?>">
<input id="cart_submit" type="hidden" name="checkout"/>
<table class="cart-list-table" cellspacing="0" cellpadding="0">
	<thead>
		<tr>
             <th width="3%" rowspan="1" class="a-center"></th>
             <th width="5%" class="prDesc"></th>
             <th width="40%" class="">ITEM NAME</th>
             <th width="13%" style="text-align:center;">Unit price</th>
             <th width="20%" class="prQuant" style="text-align:center;">QUANTITY</th>
             <th width="8%" class="prAmount" style="text-align:center;">Subtotal</th>
        </tr>
    </thead>
<tbody>     
<?php if ($cartInfo->product) :
foreach ($cartInfo->product as $k => $v): ?>
<tr id="cartitem_<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>" class="cart-item-tr <?php if(isset($v->stock_qty) && ($v->stock_qty < $v->qty)){echo 'disable';}?>" valign="top">
   <td class="a-center"><a href="<?php echo url('cart/deleteproductfromcart/'.$v->cart_item_id);?>" title="Remove" class="remove ir"><img src="<?php echo $this->themeResourceURI('images/btn_trash.gif');?>" /></a></td>
    <td class="prImage">
    	<a href="<?php echo url($v->url);?>" title="<?php echo isset($v->name) ? $v->name : null ?>"><img alt="<?php echo isset($v->name) ? $v->name : null ?>" title="<?php echo isset($v->name) ? $v->name : null ?>" src="<?php echo urlimg('60x90', $v->filepath) ?>"/></a>
    </td>
    <td class="prName" style="text-align:left;">
		<input type="hidden" class="checkitem" name="cart_item_id_checked[]" checked value="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>"/>
		<h4><a href="<?php echo url($v->url);?>" title="<?php echo isset($v->name) ? $v->name : null ?>"><?php echo isset($v->name) ? $v->name : null ?></a></h4>
<?php if(isset($v->data) && $v->data):
	  	foreach($v->data as $dk => $dv):
			echo '<p class="prAttr">'.$dk.'&nbsp;-&nbsp;'.$dv.'</p>';
		endforeach;
      else: echo '&nbsp;';
      endif;?>
    </td>
    <td class="prPrice ar">
		<p class="listPrice"><del><?php echo isset($v->list_price) ? c($v->list_price) : null;?></del></p>
		<p class="price"><?php echo isset($v->price) ? c($v->price) : null;?></p>
   </td>
    <td class="prQuant ar" >
		<input type="hidden" value="<?php echo isset($v->pid) ? $v->pid : null ?>" name="pids[]"/>
        <input type="hidden" value="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>" name="cart_item_ids[]"/>
    	<input value="<?php echo isset($v->qty) ? $v->qty : null ?>" name="qtys[]" size="3" alt="<?php echo isset($v->qty) ? $v->qty : null ?>" id="<?php echo isset($v->cart_item_id) ? $v->cart_item_id : null ?>" class="ajax_qty elmbBlur" title="<?php echo $v->sell_min ? $v->sell_min : 0 ?>,<?php echo $v->sell_max ? $v->sell_max : 0 ?>" rel="<?php echo isset($v->price) ? $v->price : null ?>"/>
    	<?php if(isset($v->stock_qty) && ($v->stock_qty < $v->qty)):?>
		<?php if($v->stock_qty > 0):?>
		<p class="error_notice">Only <?php echo $v->stock_qty?> items left.</p>
		<?php else:?>
		<p class="error_notice">Out of stock.</p>
		<?php endif;?>
		<?php else:?>
		<p class="error_notice" style="display:none;"></p>
		<?php endif;?>
    </td>
    <td class="prAmount ar">
        <span class="payPrice"><span class="numVal"><?php echo isset($v->qty) ? c($v->price * $v->qty) : null;?></span></span>
    </td>
</tr>
<?php endforeach; endif;?>
<tr style="background:none repeat scroll 0 0 #F2F2F2;">
    <td colspan="2"><a title="Continue Shopping" href="<?php echo url('browse/all.html');?>">Shop More</a></td>
    <td colspan="4" style="text-align:right;"><a href="<?php echo url('cart');?>" class="button contShopping left">Update Cart</a></td>
</tr>
</tbody>

<tfoot>
<tr class="scTotalItems">
<td rowspan="4" colspan="3" align="center"><img src="<?php echo $this->themeResourceURI('images/jt.png');?>" /></td>
<td colspan="2" class="total ar">TOTAL ITEMS:</td>
<td class="total ar">
	<?php if ($cartInfo->product){ echo count($cartInfo->product);} ?>
</td>
</tr>

<tr class="scTotalSaving ar">
	<td class="total ar" colspan="2">TOTAL SAVINGS:</td>
	<td class="total ar"><span class="numVal"><?php echo isset($cartInfo->total_save_amount) ? c($cartInfo->total_save_amount) : null?></span></td>
</tr>
<tr class="srcSumAmount">
<td colspan="2" class="total ar">
	<strong>CART TOTAL</strong>
</td>
<td class="total ar">
	<strong class="totalPrice"><span class="numVal"><?php echo isset($cartInfo->goods_amount) ? c($cartInfo->goods_amount) : null?></span></strong>
</td>
</tr>
<tr class="last">
<td colspan="3" class="checkout-types"  align="right"><?php if(isset($this->user) && $this->user->uid):?>
	<a title="Proceed to Checkout" class="checkoutBtn button <?php if ($cartInfo->lacking){echo 'disabled';}?>" href="javascript:submit_shopping_cart('checkout')">Proceed to Checkout</a>
<?php else:?>
    <a title="Proceed to Checkout" class="checkoutBtn button <?php if ($cartInfo->lacking){echo 'disabled';}?>" href="<?php echo url('user/login/')?>">Proceed to Checkout</a>
<?php endif?></td>
</tr>
</tfoot>
</table>

</form>
</div>