<div id="product-abstract">
<h1 id="prHead"><?php echo $product->name;?></h1>

<?php $this->render('contents/p_orderprice.phtml');?>
<?php $this->render('contents/p_fields.phtml');?>

<div class="product-overview" >
<ul class="product-dimension">
   <li id="detail-params" class="select">Details</li>
   <li id="sizechart">Size Chart</li>
</ul>
<div class="clear"></div>

<div class="detail-params show-item select">
<div class="params">
<?php if($product->brand):?>
<div class="param">Brand: &nbsp;<a href="<?php echo url('+'.$product->brand->path_alias.'.html');?>"><?php echo isset ($product->brand->name) ? $product->brand->name : '' ;?></a></div>
<?php endif;?>
<?php if($product->number):?>
<div class="param">Product SN: &nbsp;<label id="p_sn"><?php echo  isset($product->number) ? $product->number : '';?></label></div>
<?php endif;?>
</div>
<div class="availability">Avilability: &nbsp;<?php if ($product->status):?>In Stock<?php else:?>Not Availabile<?php endif;?></div>
<?php $this->render('contents/p_parameters.phtml')?>
</div>

<?php if(isset($product->brand) && isset($product->brand->size_chart)):?>
<div class="sizechart show-item">
<?php echo $product->brand->size_chart;?>
</div>
<?php endif;?>

</div>

<?php $this->render('contents/p_related.phtml'); ?>

</div>

<!-- 
<div class="params">
<?php if($product->brand):?>
<div class="param">Brand: &nbsp;<?php echo isset ($product->brand->name) ? $product->brand->name : null ;?></div>
<?php endif;?>
<?php if($product->number):?>
<div class="param">Product SN: &nbsp;<label id="p_sn"><?php echo  isset($product->number) ? $product->number : null;?></label></div>
<?php endif;?>
</div>
<div class="availability">Avilability: &nbsp;<?php if ($product->status):?>In Stock<?php else:?>Not Availabile<?php endif;?></div>
<?php $this->render('contents/p_parameters.phtml')?>
<?php echo $this->render('contents/p_related.phtml'); ?>
 
</div>
-->