<?php if(isset($recommandProductList) && $recommandProductList):?>

<div id="p-recommend" class="p-widget fl">
<h2>You'll Also Love</h2>
<div class="grid">
  <?php shuffle($recommandProductList);
    $recommand_count = 0;
    foreach ($recommandProductList as $v):
      if(!isset($v))
      	continue;
      if($recommand_count >= 4)
        break;
      $recommand_count++;?>
<dl><dt><a title="<?php echo $v->name;?>" href="<?php echo url($v->url) ?>"><img alt="<?php echo $v->name;?>" src="<?php echo urlimg('188x340',$v->filepath)?>"></a></dt>
      	<dd class="prodName"><a href="<?php echo url($v->url);?>" title="<?php echo $v->name;?>"><?php echo $v->name;?></a></dd>
      	<dd class="oldPrice"><?php echo isset($v->list_price)? c($v->list_price) : null;?></dd>
      	<dd class="price"><?php echo isset($v->price)? c($v->price) : null;?></dd>
</dl>
<?php endforeach;?>
</div>
</div>
<?php endif;?>