<div class="widgetfancy">
<div class="w-head" style="margin-top:20px;">
<h1 style="margin-left:0;">User Information</h1>
</div>

            <div class="uc-wrapper w-content">

             <?php echo themeMessages() ?>
            <form action="" method="post">
        		<div class="user_edit">
                  <table>
                    <tbody>
                      <tr>
                        <th>Username:</th>
                        <th>Nickname:</th>
                     </tr>
                      <tr>
                        <td><input type="text" readonly="readonly" value="<?php echo isset($user->name) ? $user->name : null ?>" class="elmbBlur input readonly"></td>
                        <td><input type="text" name="nickname" value="<?php echo isset($user->nickname) ? $user->nickname : null ?>" title="Nickname"/></td>
                      </tr>
                      <tr>
                        <th>Birthday:<span class="explanation required">*</span><span style="padding-left:5px; font-style:italic; color:#777;font-weight:normal;">Format : YYYY-MM-DD</span></th>
                        <th>E-mail:<span class="explanation required">*</span></th>
                      </tr>
                     <tr>

                        <td><input type="text" name="birthday" value="<?php if (isset($user) && $user->birthday != '') echo plain(substr($user->birthday, 0, 4) . '-' . intval(substr($user->birthday, 4, 2)) . '-' . intval(substr($user->birthday, 6, 2))) ?>"  class="elmbBlur input" title="Birthday"/></td>
                        <td><input type="text" name="email" value="<?php echo isset($user->email) ? $user->email : null ?>"  class="non-empty elmbBlur input" title="Email can't for empty"/></td>
                      </tr>
                      <tr>
                        <th>Telephone:</th>
                        <th>Mobile:</th>
                      </tr>
                      <tr>
                        <td><input type="text" name="phone" value="<?php echo isset($user->phone) ? $user->phone : null ?>" class="elmbBlur input"/></td>
                        <td><input type="text" name="mobile" value="<?php echo isset($user->mobile) ? $user->mobile : null ?>" class="elmbBlur input"/></td>
                      </tr>
                      <tr>
                        <th>Region:</th>
                        <th>Postcode:</th>
                      </tr>
                      <tr>
                        <td><input type="text" name="area" value="<?php echo isset($user->area) ? $user->area : null ?>" class="elmbBlur input"/></td>
                        <td><input type="text" name="postcode" value="<?php echo isset($user->postcode) ? $user->postcode : null ?>" class="elmbBlur input"/></td>
                      </tr>

                    </tbody>
                  </table>
                  <div class="Save-Reset">
                  <button class="button" type="submit"><span><span>Save Changes</span></span></button>
	              <button class="button" type="reset"><span><span>Reset Form</span></span></button>
                  </div>
               </div>
                </form>
            </div>
</div>