<?php global $basePath ?>
<script type="text/javascript">
var basePath = '<?php echo plain($basePath) ?>';
</script>
<script language="javascript" src="<?php echo url('scripts/jquery-1.7.2.min.js') ?>" type="text/javascript"></script>
<script language="javascript" src="<?php echo url('scripts/jquery-ui-1.8.19.custom.min.js') ?>" type="text/javascript" ></script>
<?php if (isset($_SESSION['preview'])): ?>
<script language="javascript" src="<?php echo url('scripts/preview.js') ?>" type="text/javascript"></script>
<?php endif ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/front.js';?>" type="text/javascript"></script>
<script src="<?php echo $tpldir .'/javascripts/jquery.KinSlideshow-1.1.js';?>" type="text/javascript"></script>
<script src="<?php echo $tpldir. '/javascripts/after_body.js';?>" type="text/javascript"></script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30273846-2']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>