<ul class="The_bank">
            <li><a href="#"><img width="51" height="32" alt="" src="<?php echo $tpldir ?>/images/tu_1.gif"></a></li>
            <li><a href="#"><img width="51" height="32" alt="" src="<?php echo $tpldir ?>/images/tu_2.gif"></a></li>
            <li><a href="#"><img width="51" height="32" alt="" src="<?php echo $tpldir ?>/images/tu_3.gif"></a></li>
            <li><a href="#"><img width="51" height="32" alt="" src="<?php echo $tpldir ?>/images/tu_4.gif"></a></li>
            <li><a href="#"><img width="51" height="32" alt="" src="<?php echo $tpldir ?>/images/tu_5.gif"></a></li>
            <li><a href="#"><img width="51" height="32" alt="" src="<?php echo $tpldir ?>/images/tu_6.gif"></a></li>
            <li><a href="#"><img width="51" height="32" alt="" src="<?php echo $tpldir ?>/images/tu_7.gif"></a></li>
            <li><a href="#"><img width="51" height="32" alt="" src="<?php echo $tpldir ?>/images/tu_8.gif"></a></li>
            <li><a href="#"><img width="51" height="32" alt="" src="<?php echo $tpldir ?>/images/tu_9.gif"></a></li>
</ul>