<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title><?php echo plain(isset($docTitle)? $docTitle : 'Sexy clothing Wholesale corset & lingerie wholesaler & wholesale clubwear and babydoll'); ?></title><?php 
if (isset($docKeywords)): ?><meta name="keywords" content="<?php echo plain($docKeywords) ?>" /><?php 
else:?><meta name="keywords" content="<?php echo 'Wholesale corset,Lingerie wholesaler,Wholesale clubwear,sexy clothing,babydoll wholesale' ?>" /><?php 
endif ?><?php if (isset($docDescription)): ?><meta name="description" content="<?php echo plain($docDescription) ?>" /><?php 
else:?><meta name="description" content="<?php echo 'Cheap wholesale corset & lingerie wholesaler, wholesale club wear, sex clothing, naughty and sexy girls lingerie including baby doll wholesale,bridal lingerie and corsets' ?>" /><?php 
endif; ?><?php echo isset($metas) ? $metas : null ?><?php echo $styles ?>
<link href="<?php echo $tpldir ?>/css/fashion-tribe.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $tpldir ?>/css/MagicZoom.css" rel="stylesheet" type="text/css" /></head>
