<?php if(isset($mostCommentedProducts)&& count($mostCommentedProducts) > 0 ):?>
<div class="widget w-catfeaturedContainer"> 
	<h2 class="clearfix">
		<span>Reviews Of Popular Products</span>
		<?php if(isset($showSeeAllLink) && $showSeeAllLink === true):?><a href="<?php echo url('review/' . $termInfo->path_alias . '.html');?>" class="allContents">See All Products Reviews >></a>
		<?php endif;?>
	</h2>
</div>
<?php foreach ($mostCommentedProducts as $k=>$v):?>
<div class="w-productList w-grid w-featuredCatContents">
<dl>
	<?php if($v->popularComment):?>
		<dt>
		<a href="<?php echo url($v->url);?>" title="<?php echo $v->name?>">
		<img width="98" height="138" class="allborder" title = "<?php echo $v->name?>" src="<?php echo urlimg('118x178',$v->filepath)?>">
		<em class="iconDiscount"><?php echo round((1 - $v->sell_price / $v->list_price) * 100, 0);?></em></a>
		</dt>
		<dd>
			<h4 class="featureTitle"><span class="star starS<?php echo $v->popularComment->grade?>"><em><?php echo $v->popularComment->grade?> stars of 5</em></span><span style="padding-left:20px;"><?php echo $v->popularComment->subject;?></span></h4>
			<p class="featureMeta">By <strong><?php echo $v->popularComment->nickname;?><span class="time" style="font-size:x-small; font-weight:normal; font-style:italic;"> , <?php echo date('M d, Y', $v->popularComment->timestamp);?></span></strong></p>
			<p class="prodMark">	
				 This review is from: &nbsp;&nbsp;<span class="prod">
				<?php echo '<a href="'.url('browse/' . $termInfo->path_alias . '.html').'">'.$termInfo->name.'</a> > '?> 
				<a href="<?php echo url($v->url);?>" title="<?php echo $v->name?>"><?php echo $v->name?></a></span>
				(<a rel="nofollow" href="<?php echo url($v->url.'#prReviews')?>"> <?php echo $v->comments_count;?></a>)
			</p>
			<div class="featuredContent"><div class="contentInfo"><p><?php echo $v->popularComment->comment;?></p></div></div>
		</dd>
	<?php endif;?>
	</dl>
</div><?php endforeach;?>
<?php endif;?>