<?php echo $this->render('before_body.phtml'); ?>
<body>
<?php echo $this->render('header.phtml'); ?>

<div class="bodyer">

  <h1 id="breadcrumb"><a href="http://www.iwantlingerie.com/">Home</a>&nbsp;&gt;&nbsp;<a href="<?php echo url('usr/editPassword')?>">Reset Password</a></h1>

<div id="wrapper-m">
<div class="widget w-forgetPwd">
<form method="post" action="<?php echo url('user/editPassword/')?>">
	<h2 class="top">
		Create New Password		<a class="big block fr" href="<?php echo url('')?>">&lt;&lt; Return Home</a>
	</h2>
	<div class="body">
		<p>Welcome back <?php echo $username?>! Please set new password below for future login.</p>
		
		<?php echo themeMessages()?>
		
			<input type="hidden" name="token" value="<?php echo $token?>">
			<input type="hidden" name="username" value="<?php echo $username?>">
			
		<p><span class="label">Password：</span><span class="red">*</span>
			<span style="position: relative;">
				<input type="password"  name="newpwd"  class="elmbBlur">
			</span>
		</p>
		<p><span class="label">Confirm Password: </span><span class="red">*</span>
			<span style="position: relative;">
				<input type="password"  name="newpwd2"  class="elmbBlur"/>
			</span>
			<button type="submit" class="textbtn">Submit</button>
		</p>
	</div>
	<p class="bottom"><a class="big block fr" href="<?php echo url('user/login')?>">&lt;&lt; Return Home</a></p>

</form>
</div>
</div>
</div>


<?php echo $this->render('footer.phtml'); ?>
</body>
<?php echo $this->render('after_body.phtml'); ?>
</html>