<?php echo $this->render('before_body.phtml'); ?>
<body>
<?php echo $this->render('header.phtml'); ?>
<div class="bodyer ">

<h1 id="breadcrumb"><?php echo themeBreadcrumb() ?></h1>


<div id ="wrapper" class="prPage">
<div class="w-prodImages vThumbnails" id="wrapper-t-l">
	<div id="w-featurePics">
    	<a title="" href="<?php echo url('images/'.$product->bigfilepath);?>" target="_blank">
			<img id="main-display-pic" height="500" src="<?php echo url('images/'.$product->bigfilepath);?>">
		</a>
	<div style="position: absolute; cursor: pointer; top: -9999px; width: 133.333px; height: 120px; left: 0px;" id="detailImgLen"></div></div>
	
	
	
	<div id="w-prodthumbnails">
	<div id="thumbnailsUp">
		<a href="javascript:void(0)" class="hasItem">previous</a>
	</div>
	<div id="prodthumbnails">


                  <?php if($product->fid):?>
                    <a href="<?php echo url('images/'.$product->filepath);?>"  class="current" style="margin-top: 0px;" rel="zoom1" rev="<?php echo urlimg('345x335', $product->filepath); ?>"><img width="65" height="85" src="<?php echo urlimg('118x178', $product->filepath) ?>" border="0" /></a>
                  <?php endif;?>
                  <?php
                    foreach ($product->files as $i => $file):
                  ?>
					<a href="<?php echo url('images/'.$file->filepath);?>"  <?php if($product->filepath == $file->filepath){echo 'class="current"';}?> rel="zoom1" style="margin-top: 0px;" rev="<?php echo urlimg('345x335', $file->filepath); ?>"><img width="65" height="85" src="<?php echo urlimg('118x178', $file->filepath) ?>" alt="<?php echo isset($file->alt)? plain($file->alt):null; ?>" border="0" /></a>
                  <?php endforeach ?>
	</div>
	<div id="thumbnailsDown"><a href="javascript:void(0)" class="hasItem">next</a></div>
	</div>
		<div class="spacer-10"></div>
		<!--  BOF note display -->
      	    
        	<div class="widget"> </div>
    	    	<!--  EOF note display -->	
	<div class="spacer-10"></div>
</div>


<div itemtype="http://schema.org/Product" itemscope="" id="wrapper-t-r">
			<!-- widget-prod-s4-info_3 -->
<?php list($product_item_name, $product_item_id) = split(',', $product->name);?>
<h1 itemprop="name" id="prHead"><?php echo $product_item_name;?></h1>
<p class="prodItemId">Item ID # <?php echo $product_item_id;?></p>

<p class="prodItemSummary"><?php echo $product->summary;?></p>

<ul class="widget w-prSocial">
	<li id="prRate">
	
	<?php if(isset($product->pid) && $product->pid):?>
        <span class="star starS5"><?php echo widgetCallFunction('fivestars', 'getaveragestars', $product->pid)?></span>
    <?php endif;?>
		<a class="small gray" href="">(<span>123</span> reviews)</a></li>
    <li>
    	<!-- Will enable this feature Later -->
        <!--
        <a class="textbtnGray" href="#write_a_review" style="margin-bottom:5px;">Write a review</a>
        <a class="textbtnGray" href="#ask_a_question" style="margin-bottom:5px;">Ask a question</a>
        -->
    </li>
	<li id="socialShare">
                      <div class="addthis_toolbox addthis_default_style addthis_16x16_style " id="divAddThis">
                      
                      <!-- AddThis Button BEGIN -->
                      <div class="addthis_toolbox addthis_default_style ">
                      <a class="addthis_button_preferred_1"></a>
                      <a class="addthis_button_preferred_2"></a>
                      <a class="addthis_button_preferred_3"></a>
                      <a class="addthis_button_preferred_4"></a>
                      <a class="addthis_button_compact"></a>
                      <a class="addthis_counter addthis_bubble_style"></a>
                      </div>
                      <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4f911222039d9281"></script>
                      <!-- AddThis Button END -->
                      
                      <div class="atclear"></div></div>
	</li>
</ul>
<div class="widget w-prOrderInfo">
	<table class="prPrice">
		<tbody>
			<tr>
				<th>List Price:</th>
				<td><span class="currencysymbol"><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?></span></td>
				<td><del><?php echo isset($product->list_price) ? c($product->list_price) : null;?></del></td>
						</tr>
			<tr itemtype="http://schema.org/Offer" itemscope="">
				<th class="black b">Price:</th>
				<td>
					<div style="position:relative;" id="prodCurSelector" class="left">
						<div class="currencysymbol current" id="chosedCur"><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?></div>
					</div>
				</td>
				<td><strong itemprop="price" class="salePrice"><?php echo isset($product->price) ? c($product->price):null;?></strong></td>
			</tr>
			<tr class="savingPrice">
				<th>SAVE:</th>
				<td class="currencysymbol"><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?></td>
				<td>
				  <?php if (isset($product->price) && isset($product->list_price))
				    echo c($product->list_price - $product->price);
				  ?>
				</td>
			</tr>
		</tbody>
	</table>
	<!-- widget-product-feature-info -->
		
	<!-- widget-product-feature-info_eof -->
</div>
<form name="cart_quantity_frm" method="post" class="widget w-prOrder w-prOrderNew" action="<?php echo url('cart/productpost');?>" id="prOrder">
    <input type="hidden" value="<?php echo isset($product->pid) ? $product->pid : null ?>" name="pid">
	<div id="errorInfo" class="errorInfo">Please complete your selection(s) before adding to cart.<em></em></div>
	<div class="clearfix prOrderOptions">

	<table id="tb" class="table-prOrderOpts">
		<tbody>
		
<?php foreach ($product->fields as $fieldName => $field):
    if(!empty($product->{'field_' . $fieldName})):
?>
        <tr><th><?php echo plain($field->name); ?>:</th>
			<td>
				<div class="fl">
				
  <?php if ($field->multiple){
        if($field->required==1){
          $sel_cont = ' class=" non-empty" title="'.$field->name.' not empty"';
        }else{
          $sel_cont = '';
        }
              echo'<select name="'.$fieldName.'" onchange="selectAttr(\''.$field->field_name.'\',this.value)" '.$sel_cont.'>';
              echo '<option value="">Please Select</option>';
              foreach ($product->{'field_' . $fieldName} as $k => $v){
                if($v){
                  if(isset($field->default_value) && $field->default_value && $field->default_value == $v ){
                      echo '<option value="'.$v.'" selected="selected">'.$v.'</option>';
                  }else{
                  echo '<option value="'.$v.'">'.$v.'</option>';
                  }
                }
              }
                echo '</select>';
                if(isset($field->default_value) && $field->default_value && in_array($field->default_value,$product->{'field_' . $fieldName}) ){
                  echo '<input type="hidden" value="'.$field->default_value.'" name="data['.$field->name.']" id="attr_'.$fieldName.'">';
                }else{
                  echo '<input id="attr_'.$fieldName.'" type="hidden" value="" name="data['.$field->name.']">';
                }
    }else{
              echo isset($product->{'field_' . $fieldName}) ? plain($product->{'field_' . $fieldName}) : null;
              echo '<input type="hidden" id="attr_'.$field->field_name.'" value="'.plain($product->{'field_' . $fieldName}).'" name="data['.$field->name.']">';
    }
            ?>
        		</div>
        	</td>
        </tr>
<?php
    endif;
  endforeach; ?>
		<tr><th>Quantity: </th>
		<td>
			<div class="fl">
				<input type="text" size="3"  class="numcheck" value="<?php echo isset($product->sell_min) && $product->sell_min ? $product->sell_min : 1 ?>" name="qty" title="<?php echo isset($product->sell_min) ? $product->sell_min : 0 ?>,<?php echo isset($product->sell_max) ? $product->sell_max : 0 ?>" value="1" />  Unit(s)
			</div>
		</td></tr>
	</tbody>
</table>			
	<div class="actions orderBtnV2">
		<a href="javascript:void(0);">
			<input type="submit" value="" alt="" src="<?php echo $tpldir ?>/images/transparent.gif" class="litb-btn add2cartPending" name="cart">
		</a>
	</div>
  </div>
</form>


<!-- widget-product-extra-info_2 -->
<section class="widget w-prExtras">
<div style="border-top: 1px solid rgb(221, 221, 221); padding-top: 5px;">
<p style="font-weight: bold; margin-bottom: 0pt; color: rgb(0, 0, 0);">We ship to <a target="_blank" href="#" class="u">over 200 countries worldwide</a>.</p>
<p style="margin: 0pt;"><strong>Shipping Time:</strong> 3-8 business days. </p>
</div>
</section>

	</div>

  <div class="product_details">
  

        <div id="wrapper-l">
		<!-- Start of Recommend Products -->
		<div class="widget w-prProm black">
		<h2 class="fancyHeading clearfix"><span class="current">Popular Products In this Category</span></h2>
		<div class="widget w-grid">
                <?php echo $this->render('bestproductlist.phtml'); ?>
        </div>
        <!-- End of Recommand Products -->

		<!-- Start of Product Description Section -->
			<div id="w-prodSecTabs" class="widget w-prodSecTabs"> 
				<h2 class="fancyHeading clearfix" id="fancyHeading">
					<a class="current">About This Product</a>
					<!-- Now Disable Customer Reviews, Enable Later -->
					<!--  <a class="pageAnchor" href="#customer_reviews">Customer Reviews</a>
					<span class="separator">|</span>
					<a class="pageAnchor" href="#ask_a_question">Customer Q&amp;A</a> -->
				</h2>
				<section class="w-pbg big_ section">
                    <div>
                      <span class="b_" style="font-size: 13px; color: rgb(102, 102, 102);">
                      <strong> Product Summary: </strong>
                      <?php echo $product->summary;?>
					  <?php echo (isset($docvar4) && $docvar4 != '') ? '<br><strong>Tips:</strong>'.$docvar4 : null; ?>
                      </span>
                    </div>
                    <div class="clear"></div>				
				</section>
			</div>

		<div class="widget" id="w-productDescription">
			<!-- Parameters Section Start -->
			<h2 class="blue line_180">Parameters:&nbsp;</h2>
			<div class="pad_10px pad_l_28px big relative section">
				<table width="709" cellspacing="0" cellpadding="0" border="0" class="opacity layout">
				<tbody><tr>
				<td width="709" class="big black">
				<div class="section">
                          <?php if($product->brand):?>

                        <strong class="label">Brand: &nbsp;</strong> <?php echo isset ($product->brand->name) ? $product->brand->name : null ;?> <br>
                          <?php endif;?>
                          <?php if($product->number):?>
                        <strong class="label">Code: &nbsp;</strong><?php echo  isset($product->number) ? $product->number : null;?><br>
                          <?php endif;?>
                          <?php if($product->field_color):?>
                        <strong class="label">Colors: &nbsp;</strong>
                          <?php
                            $corlorLists="";
                            foreach ($product->field_color as $c) :
                              $corlorLists.=(' '.$c);
                            endforeach;
                            echo $corlorLists;
                          ?>
                        <br>
                          <?php endif;?>
                          <?php if($product->field_size):?>
                        <strong class="label">Sizes: &nbsp;</strong>
                          <?php
                  	        $sizeLists='';
                  	        foreach ($product->field_size as $s) :
                  	          $sizeLists.=(' '.$s);
                  	        endforeach;
                  	        echo $sizeLists;
                          ?>
                        <br>
                          <?php endif;?>
                        <strong class="label">Status: &nbsp;</strong><?php if ($product->status):?>In stock, usually ships in 24 hours<?php else:?>Under the frame<?php endif;?><br>
					<br>
				</div>
				</td>
				</tr>
				</tbody>
				</table>
			</div>
			<!-- End of Parameters Section -->

			<!-- Detailed Description Section -->
			<h2 class="blue line_180">Detailed Descriptions:&nbsp;</h2>
			<div class="pad_10px pad_l_28px big relative section">
			
              <?php if($product->fid):?>
              <p><span><?php echo $product->name;?></span></p>
              <?php endif;?>
              <p><?php echo isset($product->description)? $product->description : null;?></p>
              <?php if($product->fid):?>
			  <div class="banner"><img src="<?php echo url('/images/'.$product->filepath); ?>" border="0" alt="<?php echo $product->name;?>" /></div>
			  <br/>
              <?php
                endif;
                if(isset($product->files) && $product->files):
                  foreach ($product->files as $i => $file):
                    if(isset($file->alt) && $file->alt):
              ?>
              							<p><?php echo plain($file->alt);?></p><br/>
              <?php
                    else:
                          echo '<p>&nbsp;</p>';
                   endif;
              ?>
                            <div class="banner"><img src="<?php echo url('/images/'.$product->filepath);?>" alt="<?php echo isset($file->alt)? plain($file->alt):null; ?>" border="0" /></div>
              <?php
                  endforeach;
                endif;
              ?>

			</div>
			<!-- end of Detailed Description Section -->


			<!-- Delivery information start -->
			
			<div id="Category_Description2" class="pad_10px pad_l_28px big">
				<section>
					<div id="description-dress-tpl2">
                    <div id="shipping-information">
                    <img width="695" height="59" src="<?php echo $tpldir ?>/images/ps4.jpg">
                    <ul class="packge-shipp">
                           <li>
                                <img width="325" height="176" src="<?php echo $tpldir ?>/images/package.jpg">
                                <p>
                                    <span>Package</span>
                                    <br>
                                    A lining bag, sturdy cardboard box and measuring tape accompany the dresses.
                               	</p>
                    	    <em></em>
                            </li>
                        	<li>
                                <img width="325" height="176" src="<?php echo $tpldir ?>/images/shipping.jpg">
                                <p>
                                    <span>Shipping</span>
                                    <br>
                            	We ship worldwide through fast and reliable delivery partners.
                                </p>
                    	    <em></em>
                            </li>
                    </ul>
                    </div>

                    </div>
                </section>
                </div>	
                
                <!-- Delivery Information End -->
                
                
				<div class="clear"></div>
			</div>


            <?php if (Bl_Config::get('isOpen')):?>
            <div class="Title_head_two margin clear">Product Reviews</div>
            <div class="Reviews">
                <ul class="time">
<?php
if($commentList) :
foreach($commentList as $v) : ?>
                    <li>
                        <div class="Rating"><span class="left"><?php echo $v->subject?> <?php echo widgetCallFunction('fivestars', 'getcommentstars', $v->cid)?></span> <span class="right">time: <?php echo date('m.d.Y', $v->timestamp) ?></span></div>
                        <div class="clear"><?php echo $v->comment?></div>
                    </li>
<?php
endforeach;
endif;
?>
                </ul>
                <div class="View_All">View All (<span><?php echo $product->visits?></span>)  Comment(<span><?php echo $commentCount?></span>)</div>
                <div class="Write">
                <form action="<?php echo url('comment/insert');?>" method="post"  name="guestBookForm"  onsubmit="javascript:return checkGuestBook()">
                    <input type="hidden" name="comment_token" value="<?php echo isset($comment_token) ? $comment_token : null?>" />
                    <div class="top">Write a Review</div>
                    <ul class="star_ul">
                        <li><label><input type="radio" name="fivestarsvalue" id="radio" value="5" checked></label><img src="<?php echo $tpldir ?>/images/star2.gif" alt=""></li>
                        <li><label><input type="radio" name="fivestarsvalue" id="radio" value="4"></label><img src="<?php echo $tpldir ?>/images/star3.gif" alt=""></li>
                        <li><label><input type="radio" name="fivestarsvalue" id="radio" value="3"></label><img src="<?php echo $tpldir ?>/images/star4.gif" alt=""></li>
                        <li><label><input type="radio" name="fivestarsvalue" id="radio" value="2"></label><img src="<?php echo $tpldir ?>/images/star5.gif" alt=""></li>
                        <li><label><input type="radio" name="fivestarsvalue" id="radio" value="1"></label><img src="<?php echo $tpldir ?>/images/star6.gif" alt=""></li>
                    </ul>
                    <div class="clear">
                    <input type="hidden" name="pid" value="<?php echo isset($product->pid) ? $product->pid : null?>">
                        <ul>
                            <li><span>name：</span><strong>*</strong><input type="text" class="text" value="<?php echo plain($user->nickname !== '' ? $user->nickname : $user->name) ?>" name="nickname" ></li>
                            <li><span>email：</span><strong>*</strong><input type="text" class="text" value=""  name="subject"></li>
                            <li><span>Content：</span><strong>*</strong><textarea name="comment" id="textarea" cols="82" rows="2" ></textarea></li>
                        </ul>
                        <input type="submit" class="buttom" value="">
                    </div>
                    </form>
                </div>
            </div>
           <?php endif;?>

        </div>
        
    </div>
    
    
<div id="wrapper-r">
<!-- widget-prod-recommend-s4_4 -->
<div class="w-prRecommend">
  <?php echo $this->render('recommand.phtml'); ?>
</div>
<!-- widget-related-product-V2_eof -->
</div>
    
    
    
</div>
</div>
<?php echo $this->render('footer.phtml'); ?>
</body>



<?php echo $this->render('after_body.phtml'); ?>
<?php if(count($product->files)>=4):?>
<script type="text/javascript" src=" <?php echo $tpldir; ?>/javascripts/jcarousellite_1.0.1.pack.js"></script>
<?php endif;?>
<script type="text/javascript">
$(function(){
<?php if(count($product->files)>=4):?>
    $(".thumbScroll").jCarouselLite({
          btnNext: ".arrow_left",
          btnPrev: ".arrow_right",
          speed: 800,
          scroll: 1,
          visible: 4
      });
<?php endif;?>
});
function selectAttr(name,val){
    $("#attr_"+name).val(val);
  }
</script>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js' ?>" type="text/javascript"></script>
</html>