<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user; ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>
<div class="main-content">
<?php $this->render('modules/ads_topslot.phtml');?>
<h1 id="breadcrumb"><a href="<?php echo url("");?>">Home</a>&nbsp;&gt;&nbsp; Check Out</h1>
<div class="widget fancy">
    <div class="w-head">
        <h2><span>Check Out</span></h2>
    </div>
<div class="messag">
<?php echo themeMessages(); ?>

<div id="client_message" style="display:none"></div>
<form action="" method="post" name="checkoutForm" class="disable_on_submit" onsubmit="javascript: return checkCartShipping()">
    <input type="hidden" name="pids" id="pids" value="<?php echo $pids;?>"/>
    <input type="hidden" name="goods_amount" id="goods_amount" value = "<?php echo isset($cartInfo->goods_amount) ? $cartInfo->goods_amount : '0'; ?>"/>
	<input type="hidden" name="goods_number" id="goods_number" value = "<?php echo isset($cartInfo->goods_number) ? $cartInfo->goods_number : '0'; ?>"/>
	<input type="hidden" name="goods_weight" id="goods_weight" value = "<?php echo isset($cartInfo->goods_weight) ? $cartInfo->goods_weight : '0'; ?>"/>
	<input type="hidden" name="fromcart" value="<?php echo isset($fromcart) ? $fromcart : 0?>"/>
	<input type="hidden" name="ordertoken" value="<?php echo isset($ordertoken) ? $ordertoken : 0?>"/>
	<input type="hidden" id="delivery_cid" name="delivery_cid" />
	<input type="hidden" id="delivery_pid" name="delivery_pid" />
<?php $this->render('contents/checkout_shipaddress.phtml');?>
<?php $this->render('contents/checkout_shipmethod.phtml');?>
<?php $this->render('contents/checkout_paymethod.phtml');?>
</form>
<div><img src="<?php echo url('templates/babydoll-lingerie.net/images/shop-with-confidence-title2.jpg');?>" /></div>
</div>
<div class="rightSidePositioner">
<div class="panelSummary">
<h2>Order Summary</h2>


<?php
if ($cartInfo->product) :
foreach ($cartInfo->product as $k => $v) : ?>

<div class="itemRow">
<div class="col1">
 <a href="<?php echo url($v->url);?>"><img height="85" alt="<?php echo isset($v->name) ? $v->name : null ?>" title="<?php echo isset($v->name) ? $v->name : null ?>" src="<?php echo urlimg('118x178', $v->filepath) ?>"/></a></div>
<div class="col2">
		<h5><a class="openAjaxLayer" href="<?php echo $v->url;?>" data-layerwidth="672"><?php echo isset($v->name) ? $v->name : null ?></a></h5>
		<div class="variantDetails">
		 <?php 	if(isset($v->data) && $v->data):
		 			foreach($v->data as $dk => $dv):
						echo $dk.': <span class="'.$dk.'_NAME-value">'.$dv.'</span><br />';
					endforeach;
				else:
					echo '&nbsp;';
				endif;?>
         Qty:<span class="ITEM_QUANTITY-value"><?php echo isset($v->qty) ? $v->qty : null ?></span>
		</div>
</div>

<div class="col3"><span class="ITEM_TOTAL-value"><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?>&nbsp;<?php echo isset($v->qty) ? c($v->price * $v->qty) : null ?></span></div>
<div class="clr"></div>
</div>
<?php endforeach;
endif;
?>


<?php $this->render('contents/checkout_cartamount.phtml');?>

</div>
    <div class="clear"></div>
    <div style="margin-top:30px;"><img src="<?php echo url('templates/babydoll-lingerie.net/images/getseal.gif');?>"/></div>
    </div>
</div>
</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/manage_address.js'?>" type="text/javascript"></script>
</body>
</html>