<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>


<div class="main-content">
<?php $this->render('modules/ads_topslot.phtml')?>
<h1 id="breadcrumb"><a href="<?php echo url("");?>">Home</a>&nbsp;&gt;&nbsp; Password Recovery</h1>


<div class="main-block1" style="margin-top:10px;">

<div class="widget fancy">
<div class="w-head">
	<h2>Create New Password</h2>
	</div>
		<?php echo themeMessages()?>
	<div class="user_edit">
<div style="background-color:#CCFFCC"><?php echo themeMessages(); ?></div>
<h4>Password Forgotten</h4>
       <div style="padding:10px 20px;">
		<p>Welcome back <?php echo $username?>! Please set new password below for future login.</p>
		<form method="post" action="<?php echo url('user/editPassword/')?>">	
			<input type="hidden" name="token" value="<?php echo $token?>"/>
			<input type="hidden" name="username" value="<?php echo $username?>"/>
		<table><tbody>
		<tr>
			<td><input type="password"  name="newpwd"  class="elmbBlur"/></td>
			<th align="left" style="padding:10px 0 0 10px"><span class="red">*</span>Password</th>
		</tr>
		<tr>
			<td><input type="password"  name="newpwd2"  class="elmbBlur"/></td>
			<th align="left" style="padding:10px 0 0 10px"><span class="red">*</span>Confirm Password</th>
		</tr>
		<tr><td align="right" class="td-buttons"><button type="submit" class="button">Submit</button></td><th></th></tr>
		</tbody>
		</table>


</form>
</div>

</div>
</div>


</div>
</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>