<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<div class="main-content">
<?php $this->render('modules/ads_topslot.phtml');?>
<?php $this->render('parts/breadcrumb.phtml')?>

<div class="general cat">

<?php $this->render('parts/body_left.phtml'); ?>

<div class="main-block">
<div class="widget" id="productlist">
<div class="w-head cat-filters"> 
<?php $this->render('contents/c_filter_form.phtml');?>
<div class="widget w-resultSortBar">
	<?php $this->render('contents/c_sortoptions.phtml')?>

	<?php $this->render('contents/c_viewoptions.phtml')?>
</div>
</div>
<?php $this->render('contents/c_productlist.phtml');?>
</div>
<div class="clear"></div>
<?php /*$this->render('contents/c_intro.phtml');*/?>

<!-- extral intro for this category -->
<?php if(isset($docvar3)):?>
<div class="advanced_intro"><?php echo $docvar3;?></div>
<!-- end of extral intro -->
<?php endif;?>

</div>



</div>
<div class="general_bottom"></div>
</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
</body>
<?php echo $this->render('parts/after_body.phtml'); ?>
</html>