<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php $this->render('parts/before_body.phtml'); ?>
<body>
<?php global $user ?>
<?php $this->render('parts/top_bar.phtml');?>
<div class="container">
<?php $this->render('parts/header.phtml'); ?>


<div class="main-content">
<div class="main-block1">
<?php $this->render('modules/ads_topslot.phtml');?>
<h1 id="breadcrumb"><a href="<?php echo url("");?>">Home</a>&nbsp;&gt;&nbsp; Login</h1>
    <?php echo themeMessages() ?>
	<div class="user-forms">
            <div class="user-login">
                <h1>Returning Customer</h1>
                <div class="user-forms-border">
                <h3>Sign in to your account for a fast, easy checkout. </h3>

                <form action="<?php echo url('user/login');?>" method="post">
					<div class="login_content">
	                    <div class="name">
	                    	<input type="text" value="" name="username"  class="elmbBlur"/><a style="color:#F22E9C;padding-left:5px;">*<span>Username/Email:</span></a>
	                    </div>
	                    <div class="passwd">
	                    	<input type="password" value="" name="password"  class="elmbBlur"/><a style="color:#F22E9C;padding-left:5px;">*<span>Password:</span></a>
	                    </div>
	                    <div>
                    	<div class="login-forgetpw"><a href="<?php echo url('user/getpassword')?>">Forget Password? </a></div>
	                    <div class="login-submit">
	                    <input type="submit" class="login-submit" value="Sign In"/>
			    </div>
	                </div>
                   </div>
                </form>
                </div>
            </div>
           <img src="<?php echo url('templates/babydoll-lingerie.net/images/txt-or.gif');?>" />
            <div class="user-register">
                <h1>New Customer</h1>
                <div class="user-forms-border">
                <h3 class="emphasis">Creating an account is so easy and has many benefits.</h3>
                <?php echo themeMessages() ?>
                <div id="client_message" style="display:none"></div>
                <form action="<?php echo url('user/register');?>" method="post" name="regForm" onsubmit="javascript:return checkRegister()">
                <div class="register_content">
                    <div class="name">
	                    <input type="text"  name="username"<?php if (isset($_POST['username'])) echo ' value="' . $_POST['username'] . '"' ?> class="elmbBlur"/><a style="color:#F22E9C;padding-left:5px;">*<span>Username:</span> </a>
	                    <div class="smallfont">Less than 12 characters</div>
                    </div>
                    <div class="email">
	                    <input type="text" name="email"<?php if (isset($_POST['email'])) echo ' value="' . $_POST['email'] . '"' ?> class="elmbBlur"/><a style="color:#F22E9C;padding-left:5px;">*<span>E-mail:</span> </a>
                    </div>
                    <div class="passwd">
	                    <input type="password"  name="password"  class="elmbBlur"/><a style="color:#F22E9C;padding-left:5px;">*<span>Password:</span></a>
                    </div>
                    <div class="cfm-passwd">
                    	<input type="password"  name="confirm_password"  class="elmbBlur"/><a style="color:#F22E9C;padding-left:5px;">*<span>Confirm Password:</span> </a>
                    </div>
                    <div class="register-submit">
                    	<input type="submit" class="register-submit" value="create an account" />
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
       <div class="user-help"><img src="<?php echo url('templates/babydoll-lingerie.net/images/signin-instructions.png');?>"/></div>
</div>
</div>
</div>
<?php echo $this->render('parts/footer.phtml'); ?>
<?php echo $this->render('parts/after_body.phtml'); ?>
<script language="javascript" src="<?php echo $tpldir . '/javascripts/common.js'; ?>" type="text/javascript"></script>
</body>
</html>