<fieldset class="widget inner" id="shipMethod">
	<div class="w-head">
		<h4>
			<span>Shipping Method</span>
		</h4>
	</div>
	<div class="main-section">
		<p style="display:none;" class="warning">No Shipping Method Available At This Time</p>
		<table class="tb-shippingMethod" cellspacing="0" cellpadding="0" style="padding:10px 10px;">
		  <thead>
				<tr>
					<th width="152" height="35" valign="top">Shipping Method</th>
				  <th width="425" valign="top">Estimated Shipping Time</th>
				  <th width="94" valign="top">Shipping Cost</th>
				</tr>
				</thead>
			<tbody>
				<?php $first = true; if (!empty($shippingList)): ?>
				<?php foreach ($shippingList as $name => $shippingInfo): ?>
				<tr>
					<th valign="top" class="nowrap"><input type="radio" onclick="changeShipping(this.value)" name="shipping_method" value="<?php echo $shippingInfo['name'];?>" id="radio-<?php echo $shippingInfo['name'];?>" <?php if ($first){echo "checked"; $first = false;}?>>
					<strong><?php echo $shippingInfo['displayName'];?></strong></th>
					<td><?php echo $shippingInfo['description'];?></td>
					<td valign="top" class="nowrap">
						<span id="shipping-count-<?php echo $shippingInfo['name'];?>" class="chargeFee red"><?php echo $shippingInfo['shippingFee'];?></span>
					</td>
				</tr>
				<?php endforeach;?>
				<?php endif;?>
			</tbody>
		</table>
		<div class="extraInfo">	
		</div>
	</div>
</fieldset>