<fieldset class="widget inner" id="choosePymt">
	<div class="w-head">
		<h4>
			<span>Payment Method</span>
		</h4>
	</div>
	<div class="main-section">
		<table class="cart tb-paymentMethod" cellspacing="0" cellpadding="0" style="padding:10px 10px;">
        <tbody>
          <tr>
              <th width="125" height="50" align="left">
              <input type="radio" onclick="changePayment(this.value)" name="payment_method" value="paypal" id="radio1"/>
              <strong>PayPal</strong></th>
              <td width="546">PayPal is the largest online purchasing platform,<span style="color:#F22E9C;">Credit Card/Debt Card User can currently use this option for your payment.</span></td>
          </tr>
          <tr>
              <th height="50" align="left"><input type="radio" onclick="changePayment(this.value)" name="payment_method" value="western"/><strong>Western Union</strong></th>
              <td>The world's leading money transfer company, 3-5 days delay might occur using this payment method.</td>
          </tr>
          <tr>
              <th height="50" align="left"><input type="radio" onclick="changePayment(this.value)" name="payment_method" value="wiretransfer"/><strong>Wire Transfer</strong></th>
              <td>Directly Transfer Money to us, you may need pay extra wire transfer fees to the bank. 5-7 days delay might occur using this payment method.</td>
          </tr>
        </tbody>
        </table> 
<input type="submit" class="checkoutBtn button" id="orderFormSubmit" value="Place Your Order"  name="checkout"/>
	</div>
</fieldset>