<?php $product->price = isset($product->price)?$product->price:$product->sell_price;?>
<div class="price" id="salePrice"><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?>: <?php echo isset($product->price) ? c($product->price):null;?></div>

<div class="prices">
	<span class="listPrice">List Price: <?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD';?>
		<del><?php echo isset($product->list_price) ? c($product->list_price) : null;?></del>
	</span>
	<span class="savingPrice">
			SAVE:<?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD';?> <?php 
					if (isset($product->price) && isset($product->list_price)) echo c($product->list_price - $product->price);?>
	</span>

</div>