<div class="widget">
<h2>Order Information</h2>

<div class="w-content">
<div class="widget inner">

<h4>Order Summary</h4>

	<table>
                    <tbody>
	<tr>
		<th align="left">Order No:</th>
    	<td><?php echo $orderInfo->number;?></td>

		<th align="left">Order Status:</th>
		<td><?php
  if($orderInfo->status==0): echo 'Pending';
  elseif($orderInfo->status==1): echo 'Processing';
  elseif($orderInfo->status==2): echo 'Shipped';
  elseif($orderInfo->status==-1): echo 'Removed';
  elseif($orderInfo->status==-2): echo 'Deleted';
  endif;
?></td>
	</tr>
	<tr>
		<th align="left">Payment Status:</th>
		<td><?php
  if($orderInfo->status_payment==0):
     echo 'Not Paid';
  elseif($orderInfo->status_payment==1):
     echo 'Paid';
  endif;
?></td>
		<th align="left">Create at :</th>
		<td><?php echo date('Y-m-d H:i:s',$orderInfo->created);?></td>
	</tr>
	<tr>
		<th align="left">Payable total:</th>
		<td class="emphasis"><?php echo c($orderInfo->pay_amount);?></td>
		<th align="left">Delivery Number:</th>
		<td><?php echo isset($orderInfo->data['shipping_no']) ? plain($orderInfo->data['shipping_no']) : 'non-delivery'; ?></td>
	</tr>
	</tbody>
	</table>
</div>

<div class="widget inner">
                  <h4>Order Detail</h4>

	<table cellspacing="2" cellpadding="0" class="u-order-tbl">
		<thead>
		<tr>
		<th>Image</th>
		<th>Item Description</th>
		<th>Quantity</th>
		<th>Unit Price</th>
		<th>Sub Total</th>
		</tr>
		</thead>
		<tbody>
<?php if (isset($orderInfo->items)):
  foreach ($orderInfo->items as $k => $v):?>
		<tr>
		<td><a href="<?php echo url($v->url);?>"><img src="<?php echo urlimg('60x90', $v->filepath) ?>" alt="" /></a></td>
		<td><a href="<?php echo url($v->url);?>"><?php echo isset($v->name) ? $v->name : null ?></a>
          <?php if(isset($v->data) && count($v->data)>0 && is_array($v->data)):
                foreach($v->data as $dk => $dv):
                echo '<p><strong>'. $dk. ':</strong> &nbsp;&nbsp;<span>' . $dv . '</p>';
               endforeach;
         else:
                    echo null;
                 endif;
          ?></td>
        <td align="center"><span><?php echo isset($v->qty) ? $v->qty : null ?></span></td>
		<td align="center"><span class="emphasis"><?php echo isset($v->pay_price) ? c($v->pay_price) : null; ?></span></td>
		<td align="center"><span class="emphasis"><?php echo isset($v->pay_price) ? c($v->qty * $v->pay_price) : null; ?></span></td>
		</tr>
<?php endforeach;endif;?>

        </tbody>
        <tfoot>
        
        <tr>
                        <td colspan="4" align="right">Subtotal:</td>
                        <td width="12%" align="right" class="sumval"><?php echo c($orderInfo->total_amount);?></td>
	</tr>
<?php if (isset($orderInfo)):
      	if (isset($orderInfo->fees)) :?>
           
<?php foreach ($orderInfo->fees as $fee) :
		if ($fee->fee_value) :?>
		<tr>
		<td colspan="4" align="right"><?php echo $fee->fee_key?></td>
        <td class="sumval" align="right"><?php echo c($fee->fee_value) ?></td>
        </tr>
<?php endif;endforeach;
      	endif;
      endif ?>
      <tr><td colspan="4" align="right">Total Payment:</td>
      <td align="right" class="sumval"><?php if (isset($orderInfo->pay_amount)) echo c($orderInfo->pay_amount) ?></td></tr>
		</tfoot>
	</table>
</div>

<div class="widget inner">
                  <h4>Payment Information</h4>
                  <table>
<tbody>
	<tr>
		<th>Payment method:</th>
        <td><?php echo isset($paymentList[$orderInfo->payment_method]->name) ? $paymentList[$orderInfo->payment_method]->name : null?></td>
		<th>Payment Status:</th>
		<td><?php if($orderInfo->status_payment==0):echo 'Not Paid';elseif($orderInfo->status_payment==1):echo 'Paid';endif;?></td>
		<td class="payment"><?php if($orderInfo->status_payment==0):?><?php echo $submitform; endif;?></td>
	</tr>
</tbody>
</table>
</div>

<div class="widget inner">
                  <h4>Shipping Information</h4>
                  <table>
                    <tbody>
<tr>
				<th>Delivery Method:</th>
        		<td><?php if (isset($shippingList[$orderInfo->shipping_method]->name)):
	        		  if(strtoupper($shippingList[$orderInfo->shipping_method]->name) == 'UPS'):
	        		    echo 'Expedited Shipping';
	        		  elseif(strtoupper($shippingList[$orderInfo->shipping_method]->name) == 'EMS'):
	        		    echo 'Standard Shipping';
	        		  else:
	        		    echo $shippingList[$orderInfo->shipping_method]->name;
	        		  endif;
        		  endif;?></td>
        		<th>Delivery Costs:</th>
				<td><?php echo isset($orderInfo->fees['shipping']->fee_value) ? c($orderInfo->fees['shipping']->fee_value) : ''; ?></td>
</tr>
                    </tbody>
                  </table>
        </div>

<div class="widget inner">
                  <h4>Shipping Address</h4>
                  <table>
                    <tbody>
                      <tr>
	<th align="left">First Name:</th>
    <td><?php echo isset($orderInfo->delivery_first_name) ? $orderInfo->delivery_first_name : '--'; ?></td>
	<th>Last Name:</th>
	<td><?php echo isset($orderInfo->delivery_last_name) ? $orderInfo->delivery_last_name : '--'; ?></td>
</tr>
<tr>
	<th align="left" class="pad-tb-8">Address:</th>
        <td colspan="3"><?php echo isset($orderInfo->delivery_address) ? $orderInfo->delivery_address : '--'; ?></td>

</tr>
<tr>
	<th align="left">City:</th>
	<td><?php echo isset($orderInfo->delivery_city) ? $orderInfo->delivery_city : ''; ?></td>
	<th>State/Province:</th>
    <td><?php echo isset($orderInfo->delivery_province) ? $orderInfo->delivery_province : '--'; ?></td>
</tr>
<tr>
	<th align="left">Country:</th>
	<td><?php echo isset($orderInfo->delivery_country) ? $orderInfo->delivery_country : '--'; ?></td>
	<th align="left">Postal/Zip Code:</th>
    <td><?php echo isset($orderInfo->delivery_postcode) ? $orderInfo->delivery_postcode : '--'; ?></td>
</tr>
<tr>
	<th align="left">Telphone:</th>
	<td><?php echo isset($orderInfo->delivery_phone) ? $orderInfo->delivery_phone : '--'; ?></td>
	<th align="left">Mobile Phone:</th>
    <td><?php echo isset($orderInfo->delivery_mobile) ? $orderInfo->delivery_mobile : '--'; ?></td>

</tr>
<tr>
	<th align="left">Email Address:</th>
	<td><?php echo isset($orderInfo->delivery_email) ? $orderInfo->delivery_email : '--'; ?></td>
	<th align="left">Delivery Time:</th>
	<td><?php echo isset($orderInfo->delivery_time) ? $orderInfo->delivery_time : '--'; ?></td>
</tr>
</tbody></table>
        </div>
        </div>
</div>