<div class="widget">

<h2>Welcome, <span class="header-uname"><?php echo ($user->nickname == '') ? $user->name : $user->nickname;?>!</span></h2>

<div class="w-content">


<div class="widget inner">
     <h4>Welcome, <span class="header-uname">iamnemo!</span></h4>
<div class="uc-welcome">
    <p class="welcome">Welcome to our member center! Any questions please feel free to contact us.</p>
    <p class="last_login">Your last login time:<?php echo date('m-d-Y',$user->login_timestamp);?></p>
</div>
</div>
<div class="widget inner">

<h4>User Information</h4>


<div class="uc-wrapper">
    <div class="statistics">
        <p>Your Integral: <?php if(isset($user->points)) echo $user->points;?></p>
        <p>Your total orders' transactions: <?php if(isset($orderscount)) echo $orderscount?> </p>
        <p>View your <a href="<?php echo url('order/list/')?>"><strong>order history</strong></a></p>
    </div>
</div>
</div>
</div>
</div>