<div class="widget">
<h2>User information</h2>

             <?php echo themeMessages() ?>
            	
            <div class="Password-modification">
            <h4>Modify User information</h4>

            <div class="w-content">

            	<p>* Required Fields </p>
            <form action="" method="post">
        		<div class="user_edit">
                  <table cellspacing="1" cellpadding="3">
                    <tbody>
                      <tr>
                        
                        <td width="167"><input type="text" readonly="readonly" value="<?php echo isset($user->name) ? $user->name : null ?>" class="elmbBlur input readonly"></td>
			<th width="71" valign="bottom">Username</th>
			<td width="194"></td>
			 </tr>
                      <tr>
                        <td><input type="text" name="nickname" value="<?php echo isset($user->nickname) ? $user->nickname : null ?>" title="Nickname"/></td>
			<th>Nickname</th>
			<td></td>
                      </tr>
                      <tr>
                        <td><input type="text" name="birthday" value="<?php if (isset($user) && $user->birthday != '') echo plain(substr($user->birthday, 0, 4) . '-' . intval(substr($user->birthday, 4, 2)) . '-' . intval(substr($user->birthday, 6, 2))) ?>"  class="elmbBlur input" title="Birthday"/></td>
			<th valign="bottom" >Birthday</th>
			<td align="left" valign="bottom"><span style="color :#F22E9C;">*Format:YYYY-MM-DD</span></td>
                      </tr>
                     <tr>
                        
                        <td><input type="text" name="email" value="<?php echo isset($user->email) ? $user->email : null ?>"  class="non-empty elmbBlur input" title="Email can't for empty"/></td>
			<th valign="bottom"><span style="color :#F22E9C;">*</span>E-mail:</th><td></td>
                      </tr>
                      <tr>
                        <td><input type="text" name="phone" value="<?php echo isset($user->phone) ? $user->phone : null ?>" class="elmbBlur input"/></td>
			<th valign="bottom">Telephone</th>
			<td></td>
                      </tr>
                      <tr>
                        <td><input type="text" name="mobile" value="<?php echo isset($user->mobile) ? $user->mobile : null ?>" class="elmbBlur input"/></td>
			<th valign="bottom">Mobile</th>
			<td></td>
                      </tr>
                      <tr>
                        <td><input type="text" name="area" value="<?php echo isset($user->area) ? $user->area : null ?>" class="elmbBlur input"/></td>
			<th valign="bottom">Region</th>
			<td></td>
                      </tr>
                      <tr>
                        <td><input type="text" name="postcode" value="<?php echo isset($user->postcode) ? $user->postcode : null ?>" class="elmbBlur input"/></td>
			<th valign="bottom">Postcode</th>
			<td></td>
                      </tr>
                     <tr>
                        <td height="20" colspan="3">
	                        <button class="button" type="submit">Save Changes</button>
	                        <button class="button1" type="reset">Reset Form</button>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                </form>
            </div>
</div>
</div>