<div id="pRate">
	<?php if(isset($product->pid) && $product->pid):
        echo widgetCallFunction('fivestars', 'getaveragestars', $product->pid, true);
    endif;?>
    <a href="#prReviews">(<span itemprop="reviewCount"><?php echo $commentCount;?></span> Reviews)</a>
    <a class="button button-small toogleWriteReview" href="#write-a-review" style="margin-bottom:5px;">Write a Review</a>
</div>