<?php if(isset($disProductList) && $disProductList):?>
<div class="widget">
<div class="w-head">
<h2>Discounted Products</h2>
<a class="more tiny" href="<?php echo url('discounted.html');?>">&gt; View All Discounted Products</a>
</div>
<div id="p_discounted" class="grid">
<?php
	$item_count = 0;
    	foreach ($disProductList as $v):
        $item_count++;
?>
<dl>
	<dt><a title="<?php echo $v->name;?>" href="<?php echo url($v->url);?>" title="<?php echo $v->name;?>">
		<img alt="<?php echo $v->name;?>" title="<?php echo $v->name;?>" src="<?php echo urlimg('180x270', $v->filepath);?>">
      	</a>
    </dt>
    <dd class="prodName"><a href="<?php echo url($v->url);?>" title="<?php echo $v->name;?>"><?php echo str_replace(',', ', ', $v->name);?><br /><s><?php echo isset($v->list_price)? c($v->list_price) : null;?></s>&nbsp;&nbsp;<strong style="color:#F22E9C;"><?php echo isset($v->price)? c($v->price) : null;?></strong></a></dd>
</dl>
<?php if($item_count % 4 == 0): echo '<br class="clear">';endif;endforeach;?>
</div>
</div>
<?php endif;?>
<div class="clear"></div>