<div class="c_viewoptions filter">
    <div class="showType">
    <label>Display Items Per Page:</label>
    <ul>
    <?php if (isset($pageRows) && $pageRows == 'all'):?>
    	<li><a class="select" href="javascript:void(0)">60</a></li>
    	<li>all</li>
    	<?php else:?>
    	<li>60</li>
    	<li><a class="select" href="javascript:void(0)">all</a></li>
    	<?php endif;?>
    </ul>
    </div>
</div>