<div class="scCartAmountSum">
<table id="subTotal" cellspacing="0" cellpadding="0">
	<!-- Grand Total -->
	<tfoot>
		<tr id="cartAmount">
			<td class="blank"></td>
			<th>Grand Total:</th>
			<td><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?><strong id="order_amount"><?php echo isset($cartInfo->goods_amount) ? c($cartInfo->goods_amount) : null?></strong></td>
		</tr>
	</tfoot>
	<tbody>
		<tr>
			<td width="54%" class="blank"></td>
			<th width="29%">Subtotal <?php if ($cartInfo->product){echo '(' . count($cartInfo->product) . ' item)';} ?>:</th>
			<td width="17%"><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?><strong id="ot_subtotal"><?php echo isset($cartInfo->goods_amount) ? c($cartInfo->goods_amount) : null?></strong></td>
		</tr>
		<tr id="shippingCharges">
			<td class="blank"></td>
			<th>(+) Shipping Charges:</th>
			<td><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?><strong id="shipping_money"><?php echo c(0);?></strong></td>
		</tr>
		<tr id="paymentCharge">
			<td class="blank"></td>
			<th>(+) Payment Fee:</th>
			<td><?php echo isset($_SESSION['currency'])? $_SESSION['currency']: 'USD'?><strong id="payment_money"><?php echo c(0);?></strong></td>
		</tr>

	</tbody>
</table>
</div>