<?php if(isset($recommandProductList) && $recommandProductList):?>

<div id="p-recommend" class="p-widget fl">
<h3>RECOMMENDED PRODUCTS</h3>
<div class="productlist grid">
  <?php shuffle($recommandProductList);
    $recommand_count = 0;
    foreach ($recommandProductList as $v):
      if(!isset($v))
      	continue;
      if($recommand_count >= 3)
        break;
      $recommand_count++;?>
<dl><dt><a title="<?php echo $v->name;?>" href="<?php echo url($v->url) ?>"><img alt="" src="<?php echo urlimg('180x270',$v->filepath)?>"></a></dt>
<dd><a title="<?php echo $v->name;?>" href="<?php echo url($v->url) ?>"><?php echo $v->name;?></a></dd>
<dd class="oldPrice"><?php echo isset($v->list_price)? c($v->list_price) : null;?></dd>
<dd class="price"><?php echo isset($v->price)? c($v->price) : null;?></dd>

</dl>
<?php endforeach;?>
</div>
</div>
<?php endif;?>