<div class="p-social">
	<div id="socialShare">
        <div class="addthis_toolbox addthis_default_style addthis_16x16_style " id="divAddThis">
        <!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_default_style "><a class="addthis_button_preferred_1"></a><a class="addthis_button_preferred_2"></a><a class="addthis_button_preferred_3"></a><a class="addthis_button_preferred_4"></a><a class="addthis_button_compact"></a><a class="addthis_counter addthis_bubble_style"></a></div>
        <!-- AddThis Button END -->
        <div class="atclear"></div></div>
	</div>
</div>