      <div class="logo"><a href="<?php echo url('');?>"><img src="<?php echo themeResourceURI('images/logo.jpg')?>" /></a></div>
      <div class="search">
      <form action="<?php echo url('pitems');?>" method="post">
           <input name="keyword" id="search_keyword" type="text" class="text" value="<?php echo isset($search_keywords) ? plain($search_keywords) : 'sexy lingerie';?>" onfocus="if(this.value=='What would you like to save on today'){this.value='';}"  onblur="if(this.value==''){this.value='sexy lingerie';}" />
           <a id="header_search_keyword" href="javascript:void(0)"><button type="submit"></button></a>
      </form>
     </div>
	<div id="utility" class="innercontainer">
   <img src="<?php echo themeResourceURI('images/shipping_top.jpg')?>" />
	<div id="shoppingCart">
           <img src="<?php echo themeResourceURI('images/cart.jpg')?>" />
		   <span>Cart&nbsp;<em class="cart_item_number"><?php echo isset($goodsInCart)? $goodsInCart : 0; ?></em> &nbsp;Item</span><br />
		<a class="button top-checkout" href="<?php echo url('cart');?>" style="">Check Out</a>
	</div>

	
		<div id="welcome_section">
		<div class="currency">
			<dl id="cur_selector" class="dropdown">
			<dt></dt>
			<dd>
			<ul>
<?php	if ($currencyList && count($currencyList) >0) :
            foreach ($currencyList as $k => $v) :
                if ($v->visible) :?>
             	<li><a title="<?php echo $v->name ?>" class="flag <?php echo $v->name?>" rel="nofollow" href="#" target="_top"><?php echo $v->name; ?></a></li>
<?php 			endif;
            endforeach;
         endif; ?>
            </ul>
            </dd>
		</dl>
		</div>
	</div>


</div>
<div class="clears"></div>
