<div class="widget w-prOrderInfo">
	<div class="w-bp w-popularTags" id="popularTags">
		<h3>Popular Searches</h3>
		<div class="side-subcat-div">
			<ul class="popular-search-list">
			<?php 
			foreach ($tagsList as $k=>$v):
			  if ($v->visible == 1):?>
			  <li><a href="<?php echo url(categoryURL($v->path_alias));?>"><?php echo $v->name;?></a></li>
			<?php 
			  endif;
			  endforeach;?>
			</ul>
		</div>
	</div>
</div>